### ISSUE TITLE
Translate the Nutrition Task completed text in Child Home visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1007]
- [x] Include the Swahili translation for the complete task for the Nutrition task (when applicable). I have included below for simplicity:

Normal  = Kawaida
Moderate  = Dhaifu
Severe = Dhaifu sana

![Screenshot_20191118-124708_WAJA](https://user-images.githubusercontent.com/20777928/69042251-f59a5a00-0a01-11ea-8bd3-bf2d9cefd9fb.jpg)

**Comment by allan-allay** [comment]
- Fixed in https://github.com/OpenSRP/opensrp-client-chw/pull/1023
- Handled translations for selected dropdown values when evaluating the subtitle in the **Malaria prevention** and **Nutrition status** tasks

**Comment by msschroeder** [comment]
lgtm
