### ISSUE TITLE
Investigate syncing issue on one supervisor tablet

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1013]
2. One supervisor cannot finish syncing. Hawi took the device back home with him where he has excellent wifi. He has been trying to sync it for a while now. It keeps showing syncing, syncing, syncing, but it never finishes syncing. No sync failed or sync successful message. This is the device that we are going to get the data export from. It is the supervisor who has 17 CHWs and is trying to sync the most number of households. He said his observation with this one supervisor is that they upgraded to the latest version, so Hawi's hunch is that it might be due to the incompatibility of the two versions.

**Comment by rkodev** [comment]
@cafootitt this issue is the same as  https://github.com/OpenSRP/opensrp-client-chw/issues/1012.

I will be closing this one

**Comment by cafootitt** [comment]
ok
