### ISSUE TITLE
Tallies in reports seem to mismatch the side menu tallies of children

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1014]
3. Total number of children in the reporting tally always seems to be a few off from the tally shown in the side menu. Even after manual refresh where it shows the reporting indicators were successfully updated, the tally is still off. I explained that it could be a delay after the children are registered, because those events need to be processed before they can be included in the reporting tallies, but he insisted that all of their registrations happened in September and October, so it shouldn't be because of that.

**Comment by allan-allay** [comment]
Took a look at the query that returns the **Total U5 children** and found the counts are off because of the incorrect computation of children who are registered through PNC registration. 
Suggested fix: Account for PNC registered children whose date of birth is at least a month ago. 
> `(( ifnull(entry_point,'') <> 'PNC' ) or (ifnull(entry_point,'') = 'PNC' and date(ec_child.dob, '+28 days') <= date())) `

**Comment by rkodev** [comment]
@allan-allay this has been resolved in the last release

**Comment by allan-allay** [comment]
Awesome. Thanks, @rkodev :+1:

**Comment by cafootitt** [comment]
v1.0.11 Togo release candidate

lgtm
