### ISSUE TITLE
Create a data model diagram to represent the data model of WCARO apps

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1016]
It would be good to create a diagram that represents the data model of WCARO modules. This will help us in future when designing Canopy dashboards and also for PM and stakeholder understanding, esp. as we look to deploying the modules with other partners in west africa.

**Comment by rkodev** [comment]
https://docs.google.com/document/d/1pTILOSRexh7xJOJuVCBB8LRBdNB8s7OHHMPcUMQoFYg/edit#heading=h.sem8j5jno4lu
