### ISSUE TITLE
Remove constraints from all phone number and national ID fields in ALL west africa apps

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1039]
Please see the corresponding updates in the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=2138554527).

- [x] Remove constraint from {national_id} in Add Family form
- [x] Remove constraint from {national_id} in Add Family Member form
- [x] Remove constraint from {phone_number} and {other_phone_number} (but please make sure that still only digits are allowed) in Add Family form
- [x] Remove constraint from {phone_number} and {other_phone_number} (but please make sure that still only digits are allowed) in Add Family Member form
- [x] Remove constraint from {phone_number} and {other_phone_number} (but please make sure that still only digits are allowed) in Add Family Member form
- [x] Apply the same changes to the "Edit" versions of these forms
- [x] Remove constraint from {phone_number} and {other_phone_number} (but please make sure that still only digits are allowed) in Change Family Head widget
- [x] Remove constraint from {phone_number} and {other_phone_number} (but please make sure that still only digits are allowed) in Change Primary Caregiver widget

**Comment by cafootitt** [comment]
v1.0.11 Togo release candidate

- [ ] Constraint from {phone_number} and {other_phone_number} fields in **French** Add Family form not removed
- [ ] Constraint from {phone_number} and {other_phone_number} fields in **French** Add Family Member form not removed

**Comment by AnnieMungai** [comment]
v1.0.11 Togo (4th Dec Version)

Constraint from {phone_number} and {other_phone_number} fields in French Add Family form and Add Family Member form removed. 

Its good to go now!
