### ISSUE TITLE
French Strings- on the child list - Gender in English

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-chw#1056]
v1.0.11 Togo release candidate

The gender on the child list  on the french version is stated in English. 
![Screenshot_2019-12-04-12-02-26-97](https://user-images.githubusercontent.com/58034047/70128793-950c4d80-168e-11ea-98c5-d9cdc96ea36b.png)

**Comment by cafootitt** [comment]
lgtm
