### ISSUE TITLE
App crashes when editing a child home visit

### ISSUE THREAD

**Issue by rkodev** [OpenSRP/opensrp-client-chw#1066]
The app crashed twice and took me back to the login page in a span of about an hr. This is happening especially when recording a child visit vaccination.
 
When recording the child visit, on vaccinations, the save button seems inactive and does not redirect you after saving but when you go back the vaccines entered has been saved.

**Comment by rkodev** [comment]
Similar issue to recording immunization in ANC page. Update the implementation issue. Save button now works and the resolved crash when recording immunization

**Comment by AnnieMungai** [comment]
Ver: 1.0.2 (18th Dec 2019)

Looks great!
