### ISSUE TITLE
Editing TT Immunization and IPTP-SP is disabling Save

### ISSUE THREAD

**Issue by rkodev** [OpenSRP/opensrp-client-chw#1073]
User Story: ANC schedule looks good
The app crashed when I tried registering a woman for an ANC home visit.
ANC visit immunization – save button doesn’t redirect to another page but when you go back it shows the data entered has been saved.

Editing TT Immunization and IPTP-SP more than once freezes the save button

**Comment by rkodev** [comment]
Known issue with recycling fragments in Android. Switched to use Android Support fragments and provide an alternative to the dismiss action

**Comment by AnnieMungai** [comment]
Ver: 1.0.2 (18th Dec)
Looks good!
