### ISSUE TITLE
Add, remove and adjust vaccines [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1088]
#### Changes to vaccines in Child Home Visit form:
- [x] Add typhoid conjugate to 9 month group
- [x] Remove MenA vaccine from the 9 month group
- [x] Remove rota 3 from 14 week group
- [x] Remove Rubella 1 and 2 vaccines from the 9 and 15 month vaccine groups, respectively
- Data dictionary link: https://drive.google.com/open?id=1yGuNHYoPq8OsjTPV4XiBj_FSNaQjIeVeNkKMe7SVKv8

#### Changes to service schedules (**Note: this can be skipped for January since it's not very visible or distracting in user testing**)
- [x] Change the overdue period for all vaccine tasks to + 5 days from the due date (from the current 2 weeks)
- Service schedule link: https://drive.google.com/open?id=1z5cb3zqy6zlF6y3ziE4SGlIPoHLF8OWVpUvWHQ0eOBw (I don't think this has been updated yet) 

#### Medical history indicators adjustments
- [x] Adjust the Fully Immunized - 1 Year calculation to reflect the Typhoid addition and Rota 3, Rubella 1, and MenA removals
- [x] Adjust the Fully Immunized - 2 Years calculation to reflect the Rubella 2 removal
- Original issue: https://github.com/OpenSRP/opensrp-client-chw/issues/49 and related issue for Guinea, Togo, DRC, Chad adjustments: https://github.com/OpenSRP/opensrp-client-chw/issues/414

#### Job aids indicator Adjustments  (**Note: this can be skipped for January since it's not very visible or distracting in user testing**)
- [x] Adjust the “Children (0-23 months) up to date on immunizations” indicator in the Job Aids Dashboard to reflect the added and removed vaccines listed above (i.e. at 14 week — remove rota 3; at 9 month — add typhoid conjugate, remove MenA, remove rubella 1; at 15 month — remove rubella 2)
- Original reporting indicator issue: https://github.com/OpenSRP/opensrp-client-chw/issues/162

#### Upcoming services and Medical history
- [x] Changes to the vaccines should also impact what shows up in Upcoming Services and Medical History, along the same lines of additions and removals

**Comment by rowo** [comment]
@rkodev On 14 week, I'm only seeing the IPV vaccine (I think I should be seeing OPV3, Penta3 and PCV3 as well — these are also missing from the medical history). I also filled out "Underfive Me Sasuan, 1y 3m" to have complete immunizations but don't see the 1 year fully immunized badge on him.

**Comment by rkodev** [comment]
@rowo To test OPV 3 and Penta 3 you will need to ensure there are 28 days between OPV 2 / Penta 2 and the next vaccine.  So for this issue ensure that the 10 weeks vaccines are recorded at least 28 days before today. 
Is it possible you missed the 10w vaccines?

**Comment by rowo** [comment]
@rkodev yes sounds like there's a good chance of that

**Comment by AnnieMungai** [comment]
Version 0.0.1 (29th Jan 2020)

Looks good. Correct vaccines added and the others removed (unnecessary ones).
