### ISSUE TITLE
Assigning new primary caregiver during other family member registration is broken

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#109]
I registered another family member and marked that they were primary caregiver. The caregiver status correctly showed up in the members list. Then I immediately registered another family member and marked them as primary caregiver. In the members list, the primary caregiver status should have changed from the previous person to the new person i registered, but instead, the primary caregiver status wasn't shown for any member in the list.

**Comment by rkodev** [comment]
fixed

**Comment by cagulas** [comment]
lgtm
