### ISSUE TITLE
Remove ANC and PNC registers/workflows [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1090]
- [x] Remove/hide the ANC and PNC registers from the side menu
  <img src="https://user-images.githubusercontent.com/1584163/72229905-ed811580-357f-11ea-9084-c162ec8f3cda.png" width="300">
- [x] Remove/hide the ANC Registration form from the profile pages of women or reproductive age
  <img src="https://user-images.githubusercontent.com/1584163/72229867-bd397700-357f-11ea-973d-c440d72f8085.png" width="300">
- [x] Remove/hide the ANC and PNC indicators in the Job Aids Dashboard (~~@cafootitt can you confirm these are the ones to remove? Is WRA an ANC indicator? Are indicators in the data dictionary or another doc?~~) **Updated: indicators to remove are in a spreadsheet: https://docs.google.com/spreadsheets/d/1q9YiWqjLiToTd0--Q8CbwhBwwcNDspbDxVrUfDm8VGU/edit#gid=1138838325 under ANC and PNC tabs. The "Order of indicators" tab provides an simplified view of what indicators remain.**

**Comment by cafootitt** [comment]
@rowo Everything in the ANC  and PNC tabs here: https://docs.google.com/spreadsheets/d/1q9YiWqjLiToTd0--Q8CbwhBwwcNDspbDxVrUfDm8VGU/edit#gid=1138838325 are the indicators for removal.

**Comment by rowo** [comment]
@rkodev I think this passes. For the 17 Jan release, ANC and PNC are removed from the menu. I still see ANC registration form (for editing) in an ANC woman, but not for the WRA — I think that's okay if the data gets cleaned up for what we do in Liberia for that week. The job aids looks good.

**Comment by rkodev** [comment]
@rowo I have completed data filtering on this. Everything should work fine for the LMH app

**Comment by AnnieMungai** [comment]
App Version: 0.0.1 (24th Jan)
Looks good!
