### ISSUE TITLE
Remove WASH check form from family profile [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1091]
<img src="https://user-images.githubusercontent.com/1584163/72229980-844dd200-3580-11ea-8eca-81c3499d1fec.png" width="300">

No more WASH form

**Comment by rowo** [comment]
@rkodev I still see the WASH check in due tasks for families. For example, the Susan family in chaone user.

**Comment by rkodev** [comment]
@rowo This has been fixed. Should not have any wash check

**Comment by AnnieMungai** [comment]
Version 0.0.1 (29th Jan 2020)

Looks good!
