### ISSUE TITLE
Check on Undo button bug [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1139]
<img src="https://user-images.githubusercontent.com/1584163/74457442-3e717b80-4e56-11ea-9186-f2bf23a64b92.png" width="333">

Talking about the child profile Undo button for child home visit.

Expected behavior: Undo button is tappable to open an confirmation that verifies that the user wants to undo and discard the task.

Actual behavior: nothing happens

This happens on my Nokia phone and happened on the Samsung A10s in the field in Liberia.

**Comment by rkodev** [comment]
@rowo on this issue there was a bug, you are not allowed to undo a visit not done after 24hrs so the button was still active but the undo had been disabled

**Comment by AnnieMungai** [comment]
App ver 0.0.2 (26th Feb 2020)

The undo button not active after 24hrs. Looks good!
