### ISSUE TITLE
Remove sick child and routine HH forms [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1148]
Client wants to remove these forms so they have time to properly design them.

These forms were added via two issues in January: https://github.com/OpenSRP/opensrp-client-chw/issues/1094 and https://github.com/OpenSRP/opensrp-client-chw/issues/1093.

The changes are:
- Remove the Routine HH form from being assigned to families every month, much like WASH was removed in https://github.com/OpenSRP/opensrp-client-chw/issues/1091
  ![Untitled-1](https://user-images.githubusercontent.com/1584163/74899380-c1b93280-536a-11ea-98a2-1b658b4f0fce.png)
- Remove the sick child form from the profile dropdown. If it doesn't exist, the sick child row shouldn't appear on child profiles either.
  ![sickremove](https://user-images.githubusercontent.com/1584163/74899521-26748d00-536b-11ea-88ef-4d47a632206e.png)

**Comment by rkodev** [comment]
@rowo this should be removed but the old data may still show up for users

**Comment by rowo** [comment]
This looks complete, although a child "Nasma Dahn, 5" is not loading for me. Could that be related to that user having a previous sick visit and the app is now confused? Does it work for you @AnnieMungai ?

<img src="https://user-images.githubusercontent.com/1584163/75484343-993ac500-5976-11ea-9734-43c24075fad1.png" width="200">
<img src="https://user-images.githubusercontent.com/1584163/75484349-9dff7900-5976-11ea-8172-fe2b39e3c1b4.png" width="200">

**Comment by AnnieMungai** [comment]
@rowo you were right, Nasma Dahn profile is not loading but it is the only one. All others are loading. 

App ver 0.0.2 (26th Feb 2020)

Everything looks good to me!
