### ISSUE TITLE
Rough ballpark estimate for P2P data transfer upgrades and configuration [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1152]
We want a very rough estimate (+/- 2 weeks) for this feature. Matt (Ona) and Nick (LMH) don't think we should do it now, but the program team says it's a top 3 item, so at least we should have an estimate to discuss. 

**Currently:** P2P supports transferring data from CHA --> CHSS 

**LMH wants:**
- Add one more level to the data flow i.e. CHA --> CHSS --> M&E person (this is who will actually have internet)
- CHA should be able to submit to another CHA (I'm assuming both inside and outside the  facility-area)
- CHSS should be able to submit to another CHSS (I'm assuming both in the same parent area)

There are issues around data security and privacy. There are issues around data conflicts/duplication. We don't need to R&D those too much — for now we just need an overall estimate for R&Ding this and building a solution. If there's a big red flag you see immediately, please comment.

**The context:** Rivercess will have no network connection at the CHA level and almost none at the CHA level. It's only at the next level (which they call the M&E level), that data will get to be syncable to the cloud. We are recommending that we work together to figure out some workarounds for the pilot period and push back on doing this anytime soon.

**Comment by ekigamba** [comment]
@rowo We had a discussion with @rkodev about the LOE:
- Enabling sync between: (4 hours)
  - CHA to CHA
  - CHSS to CHSS

- Issues around data privacy and security - It seems any previous issues have been resolved or confirmed as
- Issues around data conflicts/duplication:
   - Any data conflict issues that might arise are platform wide(OpenSRP) and affect the UUID generated for the events & clients
   - Data duplication issues will arise on the server-side in case CHAs sync data to the server. This is a known issue. However, will not cause data duplicates on the client devices. The LOE for R&D for this will be discussed later

 with @githengi  to come up with a plan

@rkodev can confirm and add onto the above.

**Comment by rowo** [comment]
@ekigamba Thanks, I think this is sufficient for now.

**Comment by rowo** [comment]
@ekigamba @rkodev One more question as I'm writing a reply.. the use case here is for data connectivity problems (a CHA shares a closer-to-the-CHSS CHA, who in turn might pass it down the line to a CHSS who has connectivity). So, it makes sense to avoid keeping clients on the device who are there only for this purpose — we'd need a way to remove those "not my area" clients. Thoughts on this?

**Comment by rowo** [comment]
Going to close this now. We don't need this but the key issue here doesn't seem to be data transfer but getting records off devices once the transfer is complete (since the transfer here is more for daisy chaining data so it can reach connectivity and not for sharing real data)
