### ISSUE TITLE
DRC app release assets for Play Store

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1167]
- [x] A short description of the app (up to 80 characters)

"Household enumeration, child health, ANC and PNC community workflows"

- [x] Full description of the app (up to 4000 characters)

"CFC-RTM was developed for DRC's Ministry of Health, as part of UNICEF’s Child-friendly Communities (CFC) program. The app is used by Community Health Workers (CHWs) and their supervisors to enumerate all households in their catchment area and provide routine child health, antenatal care (ANC), and postnatal care (PNC) services in the community.

CFC-RTM is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers."

- [x] Hi-res app icon (512x512 pixels) @rowo
- [x] Feature graphic for the app (1024x500 pixels) @rowo
- [x] 3 screenshots of the app (please use the same three screenshots from previous 3 apps on play store - either Togo, Guinea, or Liberia)

@rowo Please see these issues for DRC logo and assets from other apps:
https://github.com/OpenSRP/opensrp-client-chw/issues/523
https://github.com/OpenSRP/opensrp-client-chw/issues/391

Can we have this by EOD March 6th?

**Comment by rowo** [comment]
I think that should be doable.

**Comment by rowo** [comment]
@cafootitt 

![drc-cfc-icon](https://user-images.githubusercontent.com/1584163/76484211-7fc26000-63ef-11ea-9f6a-d865560e5510.png)
![drc-cfc-playstore-feature-graphic](https://user-images.githubusercontent.com/1584163/76484212-805af680-63ef-11ea-8bd2-fb5ebbdc3e06.png)

**Comment by cafootitt** [comment]
Thanks @rowo 

@rkodev Everything is sitting here for when we need to post to the Play Store.

**Comment by ndegwamartin** [comment]
@cafootitt @rkodev could we also get screenshots of various pages for Playstore? I would recommend the _Login page, register page, profile page_ and _navigation_. and or any other important page

Check out example for TChad [here](https://github.com/OpenSRP/opensrp-client-chw/issues/1464)
