### ISSUE TITLE
Build a new Wcaro app flavor for trainings

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1170]
Logo:  @rowo can you create a simple UNICEF logo for this app? Same dimensions as the ones found here (https://github.com/OpenSRP/opensrp-client-chw/issues/391), but only the UNICEF part.

Name: CFC-RTM Training

This would point to the staging server by default.

**Comment by rkodev** [comment]
Changed items for the training app
- [ ] Create a training app variant
- [ ] Change app name and Login screen
- [ ] Change app icon to be generic UNICEF logo

**Comment by cafootitt** [comment]
Closing, too outdated and not being requested anymore.
