### ISSUE TITLE
Fix toaster message info icons in the IMCI form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1186]
I'm noticing that a lot of the toaster messages just repeat the same info in the info icon. In some cases, there is no additional info, so the info icon isn't needed. In this case, the asterisks denote that there is additional information to read, so there should be an info icon there, but we need to do some copy-editing in the data dictionary to ensure the correct info icon messages align with the correct toaster message labels. 

I'll work with @AnnieMungai on this to reflect these changes in the data dictionary first before we hand this issue over to the engineering team.

![Screen_Shot_2020-03-23_at_5_00_15_PM](https://user-images.githubusercontent.com/3488986/77342290-de5cd780-6d27-11ea-8e7c-9680a7a6502c.jpg)

**Comment by allan-allay** [comment]
Hi @cafootitt It is possible to have the toaster messages without the info icon. 
Removing the additional info text in the form will have this effect.

**Comment by cafootitt** [comment]
@allan-allay Ok great, thanks.

**Comment by cafootitt** [comment]
Closing, too outdated.
