### ISSUE TITLE
(Added since scoping) Update contact information in RapidPro 

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1202]
- [x] When an update is made to the phone number, the primary caregiver, or head of household field, this information will sync with information on RapidPro contacts

**Comment by HusnaHariz** [comment]
This update is only performed against existing contacts in this [nifi PG](https://nifi-production.ona.io/nifi/?processGroupId=82c13435-bedd-1fa3-d2ad-f2880e91f93f&componentIds=). We don't need to trigger a flow on the rapidpro side, as the same nifi flow used to create a new contact can be reused. So with the current implementation we are not using [this update rapidpro flow](https://rapidpro.ona.io/flow/editor_next/59bd2c8f-f904-45b7-abda-7c5d3424faf1/) and can therefore be archived.
