### ISSUE TITLE
Icons do not all fit on the screen of All Families register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1267]
Currently, when you have a lot of family members in other services/registers (i.e. ANC, child, Malaria) there are a lot of icons on the All Families register and they start to overlap. Is there a way we update how the icons are done to avoid this?
![image](https://user-images.githubusercontent.com/20777928/87968256-ca07cc00-cac8-11ea-9657-397b7cb430d4.png)

**Comment by rowo** [comment]
This calls for the need to truncate the icons. The two ways we can do this is either just stop at a max number or just show the icons and add a (+ #) icon after. So for example [icon][icon][icon][+3]. I think Google Docs does this when there's a lot of people on a doc.

**Comment by msschroeder** [comment]
Cool. Thanks Roger. @row Would you be able to provide a mock up example of what this might look like - even from other projects?

**Comment by rowo** [comment]
@msschroeder something like this:

![WCARO - Family Register](https://user-images.githubusercontent.com/1584163/88748257-93603000-d11e-11ea-8a40-809c15355f3b.png)

**Comment by ellykits** [comment]
We have set maximum number of icons to be 3. Any number greater than that is counted after the + sign. See below comparison.
![Screenshot_1597754036](https://user-images.githubusercontent.com/26865532/90514087-5ad5d400-e169-11ea-9da4-0052bd46535b.png)
![Screenshot_1597754485](https://user-images.githubusercontent.com/26865532/90514095-5d382e00-e169-11ea-9839-53e0363364d4.png)

**Comment by msschroeder** [comment]
@ellykits That is correct
