### ISSUE TITLE
Users cannot log in on OpenSRP BA Stage

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1272]
### Issue
Two users assigned to a locations on OpenMRS cannot log in. They are `Log in Failed: User team information was not accessible. Try again`. I don't know why this is occurring. I was able to replicate it.

### To replicate
1. Download the Waja App - July 17th version 
2. Change the URL to BA Stage
3. Log in with provided usernames

**Comment by cafootitt** [comment]
@msschroeder Do both of the users have team assignments in OpenMRS?

**Comment by msschroeder** [comment]
@cafootitt Yes, they have team locations.
