### ISSUE TITLE
CHW App crashing when creating a referral from ANC, PNC, Family planning registers (device/OS specific)

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1278]
**Device Samsung SM-T350
1.5GB RAM
16GB 
Quad-core 1.2 GHz**

**Steps**
1. Click on a register (ANC, PNC, Family planing)
2. Choose a client
3. Click on fab and choose Refer to facility
4. Choose a Reason for Referal

08-17 15:57:01.714   272   272 D SurfaceFlinger: FRAMEBUFFER_TARGET
08-17 15:57:01.718   625   690 E WindowManager: Unhandled exception in Window Manager
08-17 15:57:01.718   625   690 E WindowManager: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
08-17 15:57:01.718   625   690 E WindowManager: 	at java.util.ArrayList.get(ArrayList.java:411)
08-17 15:57:01.718   625   690 E WindowManager: 	at com.android.server.wm.WindowAnimator.updateAppWindowsLocked(WindowAnimator.java:230)
08-17 15:57:01.718   625   690 E WindowManager: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:999)
08-17 15:57:01.718   625   690 E WindowManager: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
08-17 15:57:01.718   625   690 E WindowManager: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:185)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:928)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:637)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:751)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.os.Looper.loop(Looper.java:154)
08-17 15:57:01.718   625   690 E WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-17 15:57:01.718   625   690 E WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
08-17 15:57:01.756  2279  2279 I DMT-DropBoxReceiver: Received : android.intent.action.DROPBOX_ENTRY_ADDED

**Comment by msschroeder** [comment]
@Mstjamush Is this still an issue? It seems to work fine on the device used by client.

**Comment by Mstjamush** [comment]
@msschroeder This was fixed
