### ISSUE TITLE
CHW App crashing when creating a referral from Malaria registers (device/OS specific) 

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1279]
**Device Samsung SM-T350
1.5GB RAM
16GB
Quad-core 1.2 GHz**

**Steps**
Click on a register (ANC, PNC, Family planing)
Choose a client
Click on fab and choose Refer to facility

08-17 15:36:42.577 11349 11349 D TextView: setTypeface with style : 0
08-17 15:36:42.582 11349 11349 D AndroidRuntime: Shutting down VM
08-17 15:36:42.583 11349 11349 E AndroidRuntime: FATAL EXCEPTION: main
08-17 15:36:42.583 11349 11349 E AndroidRuntime: Process: org.smartregister.chw.ba, PID: 11349
08-17 15:36:42.583 11349 11349 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.chw.ba/org.smartregister.chw.activity.ReferralRegistrationActivity}: java.lang.IllegalStateException: findViewById(R.id.loadIndicatorText) must not be null
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6823)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: Caused by: java.lang.IllegalStateException: findViewById(R.id.loadIndicatorText) must not be null
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at org.smartregister.chw.referral.activity.BaseIssueReferralActivity.onCreate(BaseIssueReferralActivity.kt:88)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at org.smartregister.chw.activity.ReferralRegistrationActivity.onCreate(ReferralRegistrationActivity.java:34)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6977)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
08-17 15:36:42.583 11349 11349 E AndroidRuntime: 	... 9 more

**Comment by msschroeder** [comment]
@Mstjamush Is this still an issue? It seems to work fine on the device used by client.

**Comment by Mstjamush** [comment]
@msschroeder This was fixed
