### ISSUE TITLE
A user on OpenMRS is no longer attached to her previous location

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1282]
Issue Background:
I was wondering if there is a way to know if any data has been submitted to the production server for bphilip (username) associated with Uyovu HC (in Geita Regiona) at Village Sublocation (Mtukula A1).

Jhpiego is reporting that she sync some data back to the server, but when you clear the cache and resync - nothing happens. And they are expecting data.
I have checked the following:
1. I logged into the account, The sync is working - but no data
2. I logged into the account, logged out, and still no data syncing
3. The account is collecting data and registered to a location on OpenMRS Production server
4. I check Canopy - which has the data coming from OpenSRP. There is definitely data submitted by bphilipo.

Findings:
- Data was indeed synced by a provider named bphilipo but with a different location id other than the current one. Possibly this user was reassigned to a new location after they had synced their previous data. We presume this is the reason why you were able to retrieve the data via canopy for that user, regardless of their current location.
- Querying the database returns data for provider bphilipo with location ID as b1d61877-cafa-4515-ab90-6e0239747c35 whereas their current location ID is different. The current location for that particular provider returns no data at the time of writing this message.
- The location UUID b1d61877-cafa-4515-ab90-6e0239747c35 that was used to sync the data for some reason does no longer exists on openmrs. It may have possibly been removed, archived or updated.

Resolution:
- Run a script on the database to update the old location_id with the current location id of the provider bphilipo. This will cause the events to be synced using the new location id.

Note: Data is synced by locations for CHW and, if the locations are tampered with/updated between syncs then sync is affected. Like in the case where you move a provider to a new location, data will not be synced to their new location using the old location id.

### Problem to be solved:
We need to figure out why the data were synced with a different location id.

**Comment by msschroeder** [comment]
@ellykits What is the LOE for this?

**Comment by msschroeder** [comment]
@allan-allay This is also occurring for the following users: 
- `bmichael` seems have changed location id from `6af6a917-6eb8-48d5-a1f5-02db78eed81f` to `f521b985-8833-402d-9c75-b1d4990394e0` from Canopy investigations form data pulled from OpenSRP
- `jdeusi` - It is not clear if the locations changed ids from Canopy. We will need to further investigate this. When you log in it does not sync.
-  `nnyagindu` - It is not clear if the locations changed ids from Canopy. We will need to further investigate this. When you log in it does not sync.

**Comment by allan-allay** [comment]
Hi, @msschroeder. I looked into this issue some more and came to the following conclusions. 

1. All the users were previously assigned to different locations. Their locations were subsequently changed. 
2. The prior locations appear to have been deleted at some point hence why they don't exist currently 
3. Updating the `locationID` in the old events will allow the old data to be synced back to the devices, but I am not fully sure of the consequences/side effects in Canopy. 

Here are a couple of team member history screenshots from OpenMRS

----
![team_member_changed_michael](https://user-images.githubusercontent.com/16164649/91353418-edbee000-e7f3-11ea-95db-58f4ffe00faf.png)
![team_member_history_joyce](https://user-images.githubusercontent.com/16164649/91353423-eef00d00-e7f3-11ea-9a37-024c96c017a4.png)
![team_member_history_betha](https://user-images.githubusercontent.com/16164649/91353424-ef88a380-e7f3-11ea-9eb1-e67435c58acb.png)
![team_member_history_nyamist](https://user-images.githubusercontent.com/16164649/91353427-f0213a00-e7f3-11ea-9a2d-a0693cb077a5.png)

**Comment by msschroeder** [comment]
@allan-allay From my understanding, this says we added them as a team member and then changed the location on Nov 5 last year. However, this syncing issue was reported with the last update. I don't this this quite explains the issue. There was a change in location between July and August that I mentioned for one of them.

**Comment by msschroeder** [comment]
Closing issue. Thanks for your help!
