### ISSUE TITLE
Newly Registered Family does not appear on the All Families Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1294]
## Issue
The client has encountered the follow bug:
- When you register a family in Kiswahili and go back to the All Families register, they do not appear.
- If the Family has a child or was registered for ANC, the child or pregnant mother will appear in the Child or ANC register respectfully. You can access the family through the linkage in the profile to the Family (Family Tasks) from the ANC or Child register.

## Comments
I have not been able to replicate this. I am trying to get more information from the client to try and replicate this.
Issue is row 44 of spreadsheet - https://docs.google.com/spreadsheets/d/1I_0ivbfBJbmjQgtY2uOy61j0i5ua4zI_8gY95CF3aW8/edit?usp=sharing

**Comment by Mstjamush** [comment]
@msschroeder 
This is a lag in saving. It's taking a couple of minutes to save edits or new family/member actions. It's not specific to language too.

**Comment by msschroeder** [comment]
@ellykits Here is a good example:

4 families which are missing in All Family register (Ntibasima, Kolohoze, Alexandeli and John-please note there are two families with the same name John)

- The family which is missing in ALL Family register is NTIBASIMA Family
- The pregnant mother SEVERA MAHIGA NTIBASIMA is visible in ANC register as well as the two under 5 children(JETRUDA OPTATUS NTIBASIMA and CHIZA OPTATUS NTIBASIMA)
- If you select a pregnant mother in ANC register  and select Go to family’s profile you will find that NTIBASIMA family exists with all members in it but it is not visible in All family register

**Comment by ellykits** [comment]
@msschroeder This issue was reported by LMH and was resolved. Check it out here[Family disappearing from family Register](https://github.com/OpenSRP/opensrp-client-chw/issues/1283)

**Comment by msschroeder** [comment]
Looks good to me
