### ISSUE TITLE
HF - Several fields are not translated to Swahili

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1298]
Translations :
	a) The heading ("All Clients") and gender on the All Clients Register is in English
	b) Most fields in th Malaria Registration are in English
	c) Family profile, the Family name e.g Obrien Family which should be Kaya ya Obrien is in English
	d) Details on Family Member profile are mixed English and Swahili
	etc

**Comment by msschroeder** [comment]
@Mstjamush Some of these are related to Transifex translations, but I was wondering what you mean by Malaria Registration are in English (Malaria Registration is only done on the CHW app). Do you mean the Malaria Diagnostic Form?

**Comment by msschroeder** [comment]
Looks good to me

**Comment by msschroeder** [comment]
I am going to close this issue and add to the other issue created by Elly
