### ISSUE TITLE
Include the community responder module on the side panel

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1317]
### Issue
Currently, the community responder module is not visible from the side panel on the CHW app. 

### To replicate
1. Open the side panel
2. No community responder module appears

**Comment by allan-allay** [comment]
This requires merging of the following PRs: 

- https://github.com/OpenSRP/opensrp-client-chw-anc/pull/437 ✅ Done

> - [ ] Merge PR 

- https://github.com/OpenSRP/opensrp-client-chw-core/pull/221 

> - [ ] Fixed tests failing due to Out of memory errors/memory leaks
> 
> - [ ] Add tests *WIP*

>  - [ ] Merge PR 

- https://github.com/OpenSRP/opensrp-client-chw/pull/1212

> - [ ] Add tests *WIP*

>  - [ ] Merge PR

**Comment by msschroeder** [comment]
Looks good to me
