### ISSUE TITLE
App crashes first time you open the Add Family form in French

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1324]
Steps to replicate:

- Log in
- Change app language to French
- Open Add Family form
- Allow the app to access device files
- App crashes right after I do the above step
- I log back in and I can open the form again and it doesn't crash this time.

**Comment by allan-allay** [comment]
Was not able to recreate this. @cafootitt Is this still happening with the latest versions of the APK we've shared?
<img src="https://user-images.githubusercontent.com/16164649/93303441-20ad3000-f804-11ea-8455-6e15ffaf8321.gif" align="left" height="600" width="300" >

**Comment by cafootitt** [comment]
@allan-allay Yes, it was still happening. I was using the Samsung device, not an emulator. Do you have a Samsung device to test, or is there a way to view the crash log from this?

**Comment by cafootitt** [comment]
Can't be replicated - but let's turn on crash logs.

**Comment by rkodev** [comment]
@cafootitt @dubdabasoduba  This is an API issue with native forms. `com.vijay.jsonwizard.utils.PropertyManager#getDeviceId` breaks on Andorid 10. We do need to remove the method from native forms as this is a restrcted API

**Comment by dubdabasoduba** [comment]
I will be sharing the PR that removes this.

**Comment by cafootitt** [comment]
Sept 23 release - lgtm
