### ISSUE TITLE
"Early initiation of breastfeeding (1 hr)?" question is missing from the Add Child under 5 form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1326]
Steps to replicate:

- Register a family
- Open registration form to register a new child
- The "Early initiation of breastfeeding (1 hr)?" (variable name: early_bf_1hr) is missing

**Comment by allan-allay** [comment]
Traced the issue to changes in Native forms related to the date calculations responsible for showing `Early initiation of breastfeeding (1 hr)?` on the form i.e. Relevance calculations to show the field where `(dob < 6)`.

**Comment by allan-allay** [comment]
Fixed in this Native Forms issue https://github.com/OpenSRP/opensrp-client-native-form/issues/483

**Comment by cafootitt** [comment]
Lgtm - 15 Sept debug release
