### ISSUE TITLE
App switches back to English by itself

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1327]
I'm not sure if this happens consistently, but I've definitely noticed how the app switches back to English sometimes. What's more, the side menu remains in French, but the register views change to English.

Steps I took when I noticed the app switch to English:
- Registered a family, including the family head, 2 year old boy, and 25 year old woman
- Did the WASH check form
- Went to child's profile and completed the child home visit form
- Viewed the child's medical history page
- Navigated back to child's family page
- Navigated to family register view
- That's when I noticed some things had changed back to English, but not everything, and the language selection in the side menu showed English.

**Comment by cafootitt** [comment]
Can't replicate right now - dev

**Comment by rkodev** [comment]
@cafootitt Was able to reproduce this issue. When the app has a default language setting of English and you switch it to French, the app would revert to English at times. 
1. Login when using a phone set to use the English language
2. Switch to French
3. Logout and remove the app from the background
4. Log back in. (Issue with the language translations as part of the app is in French but it  reverts to English when you navigate away)

**Comment by cafootitt** [comment]
This is happening because we don't persist the language preference. This will be saved as a settings on the DB, so we'll have it in the next release.

**Comment by cafootitt** [comment]
@rkodev I'm noticing this issue again with the 15 Feb 2021 DRC release candidate you shared with me. In this case, the app crashed, and when I logged back in, the language was back to English.

**Comment by cafootitt** [comment]
THis seems to be fixed. When the app crashed, the language was still set to French upon logging back in.
