### ISSUE TITLE
ANC Registration menu item opens Pregnancy Outcome form instead

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1328]
Steps to replicate (done while app was in French):

- Register a family, and register a 25 year old woman
- Go to the woman's profile view and click on the "ANC Registration" or "Enregistrement CPN" option
- The pregnancy outcome form opens instead of the ANC Registration form

Note, this is a really urgent bug to fix, because I'm unable to register a pregnant women, therefore, I'm not able to test anything in the ANC or PNC registers, so it blocks about 50% of app QA.

**Comment by allan-allay** [comment]
Discovered EDD and GA calculations/relevance weren't working as expected as a result of a Native Forms bug documented here https://github.com/OpenSRP/opensrp-client-native-form/issues/483

**Comment by cafootitt** [comment]
Lgtm - release shared 15 Sept
