### ISSUE TITLE
Exclusive Breastfeeding schedules are 1 month off

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1332]
Steps to replicate:

- Register a 2 day old child
- Home visit should show exclusive breastfeeding at 0 months task, instead it shows 1 month

Steps to replicate:

- Register a 6 month old child
- Home visit should NOT show any exclusive breastfeeding task, as the last BF task expires at 6 months of age; instead it shows exclusive bf 5 months is due

Reminder of the exclusive breastfeeding task schedule

Task | Trigger Event | Trigger Date | Due | Overdue | Expiry
-- | -- | -- | -- | -- | --
Exclusive breastfeeding 0 months | Child Registration | Child's DOB | Child's DOB | Child's DOB + 2 weeks | Child's DOB + 1 month
Exclusive breastfeeding 1 month | Child Registration | Child's DOB | Child's DOB + 1 month | Child's DOB + 1 month + 2 weeks | Child's DOB + 2 months
Exclusive breastfeeding 2 months | Child Registration | Child's DOB | Child's DOB + 2 months | Child's DOB + 2 months + 2 weeks | Child's DOB + 3 months
Exclusive breastfeeding 3 months | Child Registration | Child's DOB | Child's DOB + 3 months | Child's DOB + 3 months + 2 weeks | Child's DOB + 4 months
Exclusive breastfeeding 4 months | Child Registration | Child's DOB | Child's DOB + 4 months | Child's DOB + 4 months + 2 weeks | Child's DOB + 5 months
Exclusive breastfeeding 5 months | Child Registration | Child's DOB | Child's DOB + 5 months | Child's DOB + 5 months + 2 weeks | Child's DOB + 6 months

**Comment by allan-allay** [comment]
The alert status turns to `expired` 24 hours after the date they turn 6 months.

**Comment by cafootitt** [comment]
Ok, let's change it to expired at 6 months exactly, not 24 hours after.

**Comment by cafootitt** [comment]
Sept 17 release - lgtm
