### ISSUE TITLE
Fix icon that indicates more children are in the family

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1335]
![Screenshot_20200913-151833_CFC-RTM - RDC](https://user-images.githubusercontent.com/3488986/93023155-e7e34000-f5e4-11ea-9cfd-34fb866ff35e.jpg)

Not sure what this is supposed to be, but it doesn't look like it's appearing correctly.

**Comment by rkodev** [comment]
@cafootitt Getting this image in tested devices. Please share the device specs you tested on / or the AVD details, it looks like a dimensions problem

![Screenshot_1600766166](https://user-images.githubusercontent.com/43806892/93869231-332bdb80-fcd4-11ea-8233-c3bca1c3101c.png)

**Comment by cafootitt** [comment]
Samsung Galaxy A10

**Comment by cafootitt** [comment]
This is much improved, so I'm closing this for now. In future, we can improve this more I think:

![Screenshot_20200923-145654_CFC-RTM - RDC](https://user-images.githubusercontent.com/3488986/94022614-321aad00-fdad-11ea-9cd4-103c49c1085e.jpg)
