### ISSUE TITLE
Bug: cannot submit visit form

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-chw#1348]
I cannot submit a visit form 

Steps:

- I created a new family with child Eva (1y 1m).
- I hit record visit 
- I filled out the at birth immunization form with a date a few days after birth and hit save 
- I cannot hit submit. The button is greyed out - the only option to leave the page and lose the data entered

**Comment by paulinembabu** [comment]
@isabelcshaw  the way the Home visits  are designed you have to fill out all the Vaccines that the child is Eligible for to be able to submit the visit.
