### ISSUE TITLE
HF - Translation issues

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1353]
Untranslated pages
	a) Male profile page (head of family registered for FP)
	b) All clients home page is un-translated 
	c) PNC homepage and PNC profile page
	d) Child homepage
	e) FP homepage and profile page
	f) Service Activity - Review CHW Services All-CHW services...the months are in English
	g) Stock usage report- items are in English

![Screenshot_20200916-174416](https://user-images.githubusercontent.com/29072646/93584338-d5cf1c00-f9ad-11ea-84df-0091fb65454f.jpg)
![Screenshot_20200916-174646](https://user-images.githubusercontent.com/29072646/93584349-d8ca0c80-f9ad-11ea-8c5e-d3081efd9801.jpg)Tra
![Screenshot_20200916-175131](https://user-images.githubusercontent.com/29072646/93584352-d962a300-f9ad-11ea-9e89-fef0f0e4b53a.jpg)sn
![Screenshot_20200918-124634_Kituoni](https://user-images.githubusercontent.com/29072646/93584356-d9fb3980-f9ad-11ea-8e5d-6c994cb9977e.jpg)
![Screenshot_20200918-124703_Kituoni](https://user-images.githubusercontent.com/29072646/93584360-db2c6680-f9ad-11ea-905c-6ff9c9fce8fb.jpg)
![Screenshot_20200918-124727_Kituoni](https://user-images.githubusercontent.com/29072646/93584362-dbc4fd00-f9ad-11ea-8d96-3ef7318cd41b.jpg)
![Screenshot_20200918-124747_Kituoni](https://user-images.githubusercontent.com/29072646/93584367-dc5d9380-f9ad-11ea-8029-24cd488f33a8.jpg)
![Screenshot_20200918-124756_Kituoni](https://user-images.githubusercontent.com/29072646/93584368-dcf62a00-f9ad-11ea-98e7-ce4e916b7f28.jpg)
![Screenshot_20200918-124824_Kituoni](https://user-images.githubusercontent.com/29072646/93584369-dcf62a00-f9ad-11ea-87e6-18880212f941.jpg)
![Screenshot_20200918-124853_Kituoni](https://user-images.githubusercontent.com/29072646/93584370-dd8ec080-f9ad-11ea-9d03-5557787a5b6b.jpg)

**Comment by ndegwamartin** [comment]
@Mstjamush looks like dates are a bulk of the missing translations right?

**Comment by ndegwamartin** [comment]
I think the dates needs some special handling within the app logic as they are not part of the translatable Transifex string values cc @msschroeder

**Comment by ellykits** [comment]
Fixed
![Screenshot_1602234827](https://user-images.githubusercontent.com/26865532/95565475-ee6ca800-0a28-11eb-8425-a5b7220b3dd8.png)
![Screenshot_1602234858](https://user-images.githubusercontent.com/26865532/95565495-f75d7980-0a28-11eb-8feb-3452c09d992b.png)
![Screenshot_1602234877](https://user-images.githubusercontent.com/26865532/95565525-03493b80-0a29-11eb-9a03-11c0cc5fa3c9.png)
![Screenshot_1602234983](https://user-images.githubusercontent.com/26865532/95565749-4acfc780-0a29-11eb-88d0-639ae9aa299b.png)
![Screenshot_1602235062](https://user-images.githubusercontent.com/26865532/95565909-823e7400-0a29-11eb-8465-9b798e2b4be7.png)

**Comment by msschroeder** [comment]
Closing because added to https://github.com/OpenSRP/opensrp-client-chw-core/issues/300
