### ISSUE TITLE
Translations issues

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1372]
Translations Issues

1. The whole of the Community Responders module is not translated to Swahili
2. When one clicks on the Community Responders and  click back, Registers, Service Activity, Community Responders and Stock usage report change to being in English   
![Screenshot_20201001-105041](https://user-images.githubusercontent.com/29072646/94809889-eba3fe80-03fb-11eb-99ab-1d74dc39f8f8.jpg)
![Screenshot_20201001-105129](https://user-images.githubusercontent.com/29072646/94809893-ef378580-03fb-11eb-947c-07f8630b8920.jpg)

**Comment by msschroeder** [comment]
Some of these translations need to be done in transifex. However, it is not clear if there are any others are form related. The client is working on these translations ASAP

**Comment by ellykits** [comment]
As reported by @Mstjamush The issue here is a translation bug and not necessary a transifex issue. But is now resolved @msschroeder

**Comment by ellykits** [comment]
As reported by @Mstjamush The issue here is a translation bug and not necessary a transifex issue. But is now resolved @msschroeder

**Comment by msschroeder** [comment]
Issue number 2 seems resolved

**Comment by msschroeder** [comment]
Closing - added the remaining community responder issues to https://github.com/OpenSRP/opensrp-client-chw-core/issues/300
