### ISSUE TITLE
Move "marital status" question from the ANC Registration form to the Add Family and Add Family Member forms

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1385]
Please remove the "marital status" question from the ANC Registration form and instead add the question to the Add Family and Add Family Member forms.

See ANC [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=0), ANC Registration tab, rows 15-19

See Family/Child [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=213855452), Add Family tab, rows 42-46, and see Add Family Member tab, rows 32-36

**Comment by cafootitt** [comment]
Fails QA

I tested on the 27 Oct release of the chad app pointing to wcaro stage.

I noticed that the marital status question has NOT been removed from the ANC registration form.

I was unable to test the add family and add family member forms due to this issue: #1458

**Comment by rkodev** [comment]
-- PR merged in  Oct 28th

**Comment by cafootitt** [comment]
V0.0.2 - lgtm!
