### ISSUE TITLE
[DRC only] Add "Lingala" language to the language dropdown

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1392]
The DRC deployment requires a new language for users, the local language Lingala. This already exists as a language in Transifex, so I will add that language to the relevant libraries in Transifex, so that the DRC team can start adding translations. This issue is about adding that language dropdown option to the app, so that users can switch to Lingala.

- [ ] **opensrp-client-chw**
- [ ] **opensrp-client-chw-core**
- [ ] android-p2p-sync
- [ ] opensrp-client-chw-anc
- [ ] opensrp-client-chw-anc PNC
- [ ] opensrp-client-core
- [ ] opensrp-client-family
- [ ] opensrp-client-native-form
- [ ] opensrp-client-reporting
- [ ] opensrp-unicef-wcaro

**Comment by rkodev** [comment]
@cafootitt the small label is for adding Lingala as an option. The actual translation would still be provided by transifex.

**Comment by cafootitt** [comment]
Moved this to the ice box column for now. The client is finding it challenging to find volunteer Lingala translators in the govt, so it is now not known if and when the translators will be available to do this.

**Comment by cafootitt** [comment]
Closing, this is indefinitely on hold.
