### ISSUE TITLE
Fix icon for remove family

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#140]
Looks like there are two dots appearing in the icon. This is on the remove member action page.

![screenshot_20190219-131814](https://user-images.githubusercontent.com/3488986/53008165-d27a5400-3449-11e9-99c3-86a15668e92b.png)

**Comment by ladleo** [comment]
I don't see any dots, if you can provide a screenshot with the dots it will be extremely helpful.

**Comment by cagulas** [comment]
Check the screenshot in the above comment. The last icon on the screenshot.

**Comment by ladleo** [comment]
![rowavatar_family](https://user-images.githubusercontent.com/10863335/54617101-c1852880-4a71-11e9-9256-71b279979ba3.png)
The dots are part of the icon.

**Comment by cagulas** [comment]
Ok, let's leave this for now then
