### ISSUE TITLE
New (small) design needs for UNICEF WCARO deployments

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1402]
As discussed on the phone this week:

- [x] Icon for delivery kit given to pregnant women. See picture below. There are two types of delivery kits - either with the yellow outline or the blue outline.

![delivery kit](https://user-images.githubusercontent.com/3488986/95480468-d98a0900-0983-11eb-9902-ca26c1518756.jpg)

- [x] New icon for minimum dietary diversity that includes fruits, vegetables, and cereals, in addition to the animal products currently pictured

- [x] Icon for family kit given to families on a quarterly basis. See picture below. Similar to delivery kit, but green outline

![kit familaux](https://user-images.githubusercontent.com/3488986/95480814-3eddfa00-0984-11eb-9cff-fedef62b9cfd.jpg)

- [x] Icon or some other way to designate children who are physically challenged. They like the idea of just adding the "PHYSICALLY CHALLENGED" label to the child's row and profile view, see below. They're happy to go with this.

![image001](https://user-images.githubusercontent.com/3488986/95481095-86fd1c80-0984-11eb-9941-216d9f08710b.jpg)
![image002](https://user-images.githubusercontent.com/3488986/95481096-8795b300-0984-11eb-8aa0-75f774d15f9f.jpg)

- [x] Combine all baby danger signs into one scrolling image, similar to mother danger signs. Also, add the danger sign label beneath each picture. Baby danger signs are in this [folder](https://drive.google.com/drive/u/1/folders/1ZSsEvcJLicAL8Q9RohYD3hMAIqHphh3Z). Also in that folder, find a spreadsheet that has the exact text for the labels for the danger signs as well as the order they should appear in the image. Please note there are two fast breathing images - please use whichever one is higher res. Finally, there is a danger sign for "Low or high temperature", but these are two different images (High temperature and Low temperature). Would it be possible to combine these side by side? The client doesn't have an image that represents both.

- [x] Edit LMP. The client expressed that they're happy with the approach to add a confirmation step before saving the form.

**Comment by cafootitt** [comment]
@rowo Can we get the new icon for dietary diversity first and by end of this week, so by COB on Oct 16th. I need Qazi to pick up this issue next, so the go-live is not blocked.

**Comment by cafootitt** [comment]
@rowo I just got off the phone with Unicef, and they decided that all of the above issues are critical for the go-live, so can you finish this issue by COB on Oct 16th?

**Comment by rowo** [comment]
@cafootitt For the baby danger signs image, I'm not sure what size the mother one was exported at, so I included a few resolutions in the [folder](https://drive.google.com/drive/u/1/folders/1ZSsEvcJLicAL8Q9RohYD3hMAIqHphh3Z) at "baby-danger-signs-1x.."

**Comment by rowo** [comment]
@cafootitt for dietary diversity, do you think [this image](https://drive.google.com/file/d/1AHNwphH4Ex5s82QnaZoD7WNaPmrLR0bp/view?usp=sharing) fulfills the needs?
![form-dietaryDiversification3](https://user-images.githubusercontent.com/1584163/95906840-ac18d300-0d68-11eb-8a43-7585fb4144d8.png)

**Comment by cafootitt** [comment]
@rowo thanks for this. I'll double check with unicef that the cow is ok for all of those countries. It looks good to me otherwise.

**Comment by rowo** [comment]
@cafootitt here are the kit bags, also in the [icon folder](https://drive.google.com/drive/u/0/folders/1XMVd5PJEZEanMs57tBgEWbhVJbRBNYG3)

![form-kit-accouchment-yellow](https://user-images.githubusercontent.com/1584163/96002979-c05fdd00-0e07-11eb-8ac4-b53fabdc231f.png)
![form-kit-cpn-blue](https://user-images.githubusercontent.com/1584163/96002981-c0f87380-0e07-11eb-8845-63cfd449e8ef.png)
![form-kit-pcime-green](https://user-images.githubusercontent.com/1584163/96002982-c0f87380-0e07-11eb-9e01-34d07d206531.png)

**Comment by cafootitt** [comment]
Many thanks
