### ISSUE TITLE
Add label for children who are physically challenged to the family member list and child profile view

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1427]
There is a yes/no field for whether or not the child is physically disabled in the child registration form (field name = physically_challenged).

Right now, there is no way to view this information except going back to the registration form. The client is asking that we show a visual indicator of their status, and we've settled on the below solution:

- [x] Similar to the "FAMILY HEAD" and "PRIMARY CAREGIVER" labels, add a label for "PHYSICALLY CHALLENGED" to the child's row in the family member list:

![image](https://user-images.githubusercontent.com/3488986/96173331-a9aca980-0f1f-11eb-9b1a-cd76f12c2112.png)

- [x] Similar to the "FAMILY HEAD" and "PRIMARY CAREGIVER" labels, add a label for "PHYSICALLY CHALLENGED" to the child's profile view. Please match the sizing and spacing as the "FAMILY HEAD" and "PRIMARY CAREGIVER" labels:

![image](https://user-images.githubusercontent.com/3488986/96173479-d6f95780-0f1f-11eb-85d5-f76c4bd7efdb.png)

**Comment by cafootitt** [comment]
Has 3 PRs - family, core, client - will be submitted by COB 8 Dec.

**Comment by cafootitt** [comment]
19 Jan 2021 build, v1.0.3 - drc - lgtm.

@qaziabubakar Can you please share the key for the string and the library it's in, so I can look it up in transifex?

**Comment by qaziabubakar-vd** [comment]
> 19 Jan 2021 build, v1.0.3 - drc - lgtm.
> 
> @qaziabubakar Can you please share the key for the string and the library it's in, so I can look it up in transifex?

@cafootitt The key for the string is `"physically_challenged"` and it's placed in client-chw-core

**Comment by cafootitt** [comment]
Great, I have translated the string in Transifex.
