### ISSUE TITLE
Bug: native form string not available for translation in Transifex

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1435]
The string in native form "Please select one option" is not available to translate to French. I've searched for this string in the chw and native form libraries on Transifex, but I can't find it. 

![Screenshot_20201016-130327_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/96287667-31ef8500-0fda-11eb-93ef-882bbb2d6e27.jpg)

**Comment by cafootitt** [comment]
Can add this on strings inventory - should appear in Transifex then.

**Comment by cafootitt** [comment]
@qaziabubakar Can you please share with me the library and string key for this, so that I can find this in Transifex? Just confirming you added this string to the main native form library folder?

**Comment by cafootitt** [comment]
I found the key `select_one_option` in the client-chw project in Transifex. Should this be moved to the client-native-form library instead?

**Comment by qaziabubakar-vd** [comment]
> I found the key `select_one_option` in the client-chw project in Transifex. Should this be moved to the client-native-form library instead?

@cafootitt Yes, it's best that we move into client-native-form library. I can create a PR for this in native-forms and remove it from client-chw if that sounds good to you.

**Comment by cafootitt** [comment]
Thanks, I have added the translation to the native form library on transifex.
