### ISSUE TITLE
Note still displays in Birth Certification when no longer relevant

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#145]
If you change your answers in the Birth Certification service widget, the note "Instruct the caregiver to have the birth registered with the civil registrar." still shows after it's no longer relevant.

**Comment by cagulas** [comment]
Maybe good issue to pick up when doing https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/209

**Comment by mahmud6390** [comment]
@cagulas i am trying to reproduce this issue with latest changes but can't.would you please check the video about my reproduction path is ok or i am missing any step?
[issue_145.mp4.tar.gz](https://github.com/OpenSRP/opensrp-client-chw/files/2977968/issue_145.mp4.tar.gz)

**Comment by mahmud6390** [comment]
pending PR #230

**Comment by cagulas** [comment]
fixed
