### ISSUE TITLE
Create assets to post Chad apk to play store

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1464]
- [x] A short description of the app (up to 80 characters)

"Household enumeration, child health, ANC and PNC community workflows"

- [x] Full description of the app (up to 4000 characters)

"CFC-RTM is part of UNICEF’s Child-friendly Communities (CFC) program. The app is used by Community Health Workers (CHWs) and their supervisors to enumerate all households in their catchment area and provide routine child health, antenatal care (ANC), and postnatal care (PNC) services in the community.

CFC-RTM is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers."

- [x] Hi-res app icon (512x512 pixels) @rowo
- [x] Feature graphic for the app (1024x500 pixels) @rowo
- [x] 3 screenshots of the app (please use the same three screenshots from previous 3 apps on play store - either Togo, Guinea, or Liberia)

@rowo Please see these issues for Chad logo and assets from other apps:
https://github.com/OpenSRP/opensrp-client-chw/issues/523
https://github.com/OpenSRP/opensrp-client-chw/issues/391

Can we have this by COB on Friday, Nov 6th?

**Comment by rowo** [comment]
![chad-app-icon](https://user-images.githubusercontent.com/1584163/98324496-6abbc200-1fba-11eb-8f1b-a5296582d70e.png)

![chad-cfc-playstore-feature-graphic](https://user-images.githubusercontent.com/1584163/98324523-7e672880-1fba-11eb-8c74-bd7419553fa8.png)

**Comment by cafootitt** [comment]
Thanks Roger

**Comment by rkodev** [comment]
Sample Screenshot
![Screenshot_1604733366](https://user-images.githubusercontent.com/43806892/98434766-ad2cee00-20e3-11eb-9151-afb719d5fd30.png)
![Screenshot_1604733759](https://user-images.githubusercontent.com/43806892/98434767-af8f4800-20e3-11eb-863f-9a0927de6917.png)
![Screenshot_1604733765](https://user-images.githubusercontent.com/43806892/98434769-b28a3880-20e3-11eb-85c9-78b47567e2af.png)
![Screenshot_1604733790](https://user-images.githubusercontent.com/43806892/98434771-b453fc00-20e3-11eb-9079-8395c5213a52.png)
![Screenshot_1603119841](https://user-images.githubusercontent.com/43806892/98434773-b6b65600-20e3-11eb-8b8b-0776895a139a.png)
