### ISSUE TITLE
Clean up on the minimum dietary diversity task in DRC flavor

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1542]
Original implementation issue: https://github.com/OpenSRP/opensrp-client-chw/issues/1388

### English version:

- [x] Please correct the question label. It should be: `Has the child received, in the previous 24 hours, any animal products (e.g. eggs, liver, milk), fruits, vegetables, or cereals?`

![Screenshot_20201112-155944_CFC-RTM - RDC](https://user-images.githubusercontent.com/3488986/98996606-0d2ff400-252b-11eb-8781-a9273ab59157.jpg)

### French version:

- [x] Please implement this correctly in the French version of the app and ensure the new strings to translate are added to Transifex.

![Screenshot_20201112-160059_CFC-RTM - RDC](https://user-images.githubusercontent.com/3488986/98996649-1d47d380-252b-11eb-8179-14453f8358a7.jpg)

**Comment by cafootitt** [comment]
English version looks good, but I'm unable to find the French strings in Transifex. Has this been merged to master yet?

**Comment by qaziabubakar-vd** [comment]
> English version looks good, but I'm unable to find the French strings in Transifex. Has this been merged to master yet?

This has been merged to master but for the strings to be added in Transifex, we need to merge the Keycloak branch with master. Once it's merged the strings will automatically be added to Transifex.

**Comment by cafootitt** [comment]
@qaziabubakar After speaking with Ronald, we came to the conclusion that the French translation needs to be added to the app, not in Transifex. Here is the translation:

L'enfant a-t-il reçu, dans les 24 heures précédentes, l'un des 4 produits suivants: produits animaux (œufs, foie, lait), fruits, légumes, ou céréales?

0 - Aucun des 4 produits
1 - Un seul type d'aliment
2 - Deux types d'aliments différents
3 - Trois types d'aliment différents
4 - Quatre types d'aliment différents

**Comment by cafootitt** [comment]
DRC V1.0.1 - lgtm
