### ISSUE TITLE
Create French versions of the child and mother danger sign images

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1554]
Baby danger sign images: https://drive.google.com/drive/u/1/folders/1ZSsEvcJLicAL8Q9RohYD3hMAIqHphh3Z
Mother danger sign images: https://drive.google.com/file/d/1YKFVEIxpIXd2FcjloMg6gXxTBrwMleFm/view?usp=sharing

### Mother danger sign translations

English | French
-- | --
Fever | Fièvre
Bleeding vaginally | Saignement vaginale
Severe headache | Mal de tête grave
Convulsions | Convulsions
Difficulty breathing | Difficulté de respiration
Severe abdominal pain | Douleur abdominale sévère
Swollen face and legs | Visage et jambes enflés

### Child danger sign translations

English | French
-- | --
Fast breathing | Respiration rapide
Chest indrawing | Tirage respiratoire
Low or high temperature | Basse ou haute température
Refuses to suckle | Refuse de téter
No movement | Pas de mouvement
Convulsions | Convulsions
Jaundice | Jaunisse

**Comment by rowo** [comment]
@cafootitt 

Mother, does not have difficulty breathing:
![diagramArtboard 1](https://user-images.githubusercontent.com/1584163/99347398-0a077180-2865-11eb-80d5-93a7325d159c.png)

Child:
![child-danger-signs-fr](https://user-images.githubusercontent.com/1584163/99347512-4fc43a00-2865-11eb-8090-3e8d5bbc8342.png)

**Comment by cafootitt** [comment]
Thanks Roger. That's odd, we must have never gotten difficulty breathing image from them.
