### ISSUE TITLE
[Design issue] [All wcaro countries] Incorporate ECD pdf counseling materials into the Job Aids section of the app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1556]
PDF materials (both English and French) can be found in this folder: https://drive.google.com/drive/u/1/folders/12yKPiJ3KcGYWS9XEil4Y0DqE2hbjHnOu.
- There are 8 pdfs in English
- There are 6 pdfs in French

The client wants to add the pdf materials for ECD to the Job Aids section of the app.

The Job Aids section of the app currently looks like this (there are only tutorial videos there currently):

![Screenshot_20210105-113059_CFC-RTM - Tchad](https://user-images.githubusercontent.com/3488986/103675580-05635d80-4f78-11eb-8d62-e586dee5d7d6.jpg)

Keep in mind:
- Since the job aids section cannot be accessed while a home visit is in progress (and a home visit cannot be saved), these materials will only be able to be consulted either before or after a child home visit, not during.
- Generally-speaking, we can break down job aids into the tutorials (how to use the app - these are all videos right now), and counseling materials to be used with client visits.
- We cannot rule out additional counseling materials from being added later on, but the client says in the short term, they don't expect anything else. They also don't produce these themselves; instead they rely on country offices to provide pre-approved program content and materials, so it's basically as they get them from country partners.
- Similarly, they cannot rule out having counseling videos in the future, but they acknowledge they are harder to come by, as they're more expensive to produce and harder to disseminate or share between programs.
- The client is happy to leave the implementation to us and for us to advise them on best user experience in terms of how to format and structure the job aids section.

For implementation:
- In my mind, I'm seeing a sub-categorization by job aid type - tutorial vs. counseling - and then a sorting by alphabetical order (all media types sorted together and not sub-categorized).

**Comment by cafootitt** [comment]
Waiting for more input from the client before we proceed on this.

**Comment by rowo** [comment]
@cafootitt I don't have any further questions. Just to confirm, the proposal you described "In my mind, I'm seeing a sub-categorization by job aid type - tutorial vs. counseling - and then a sorting by alphabetical order (all media types sorted together and not sub-categorized)." is the same as what the client said in the email?

**Comment by cafootitt** [comment]
Yes, I believe that is what they are saying when they say "So, in terms of your first question, maybe a mix of both? Meaning all counselling materials are clustered together, then arranged alphabetically / by age with materials about newborns on top." but they would be open to other suggestions of ours.

**Comment by rowo** [comment]
The screens for this: https://marvelapp.com/project/5413883

First a menu, then tapping into either **Counseling** (age order) or **Tutorials** (alphabetical order).
