### ISSUE TITLE
New design request to make the "SUBMIT / VALIDER" button contrast easier to see

### ISSUE THREAD

**Issue by cafootitt** [opensrp/opensrp-client-chw#1578]
From the client:

> Under home visits, is it possible to add a contrast/box around the word SAVE/SUBMIT to make it obvious when saving is not yet allowed? This signals to the CHW that they are missing a few required information. From the training, they sometimes get confused why the save is not working, and it appears that they don't see clearly that the SAVE/SUBMIT word is greyed out. 

![Screenshot_20201123-160855_CFC-RTM_-_RDC](https://user-images.githubusercontent.com/3488986/100015826-738d0000-2dd0-11eb-8f96-66a3fd502488.jpg)

**Comment by cafootitt** [comment]
Hi Roger - your thoughts on this would be appreciated. Should we consider changing the button? Or should we maybe add a dialog that explains why the visit can't be saved yet?

**Comment by rowo** [comment]
- For the required fields, we should add that red asterisk as part of the labels so the user knows ahead of time things are required. For this use case, maybe it's not clear enough doing the inverse (i.e. showing what is optional).
- Coincidentally, we just talked about this in Unicef Tunisia and it might be good to consider doing the same thing here, which is show a snackbar / toaster when the user taps a disabled button.
- I don't know if the button outline would do much on its own. A more significant button background could work, but we don't really do that anywhere else. Transitioning from the top button to a [fixed button at the bottom](https://marvelapp.com/prototype/1296hh24/screen/72966669) like we started proposing in mobile forms would definitely make that button more prominent if it's feasible.

**Comment by cafootitt** [comment]
Thanks @rowo I'll circle back after discussing with Ronald and the rest of the team.

**Comment by cafootitt** [comment]
Discussion on the placement of the save button moved to this issue: https://github.com/OpenSRP/opensrp-client-chw/issues/1656

This issue will be about the red required asterisk and the toaster message only, but I'm marking as blocked until the final implementation for the save button in issue 1656 is agreed on.

**Comment by rowo** [comment]
@cafootitt It would also be good to show a snackbar when the user tries to submit to say why it's not working. The button should also react to the press to show the user the tap is being read. I don't know if this is part of Android or part of the some kind of library we're using, but it's something I should talk to an engineer about if there's time in this project.
