### ISSUE TITLE
[bug - all wcaro flavors] Supervisor and CHW accounts show different family tasks after successful p2p sync

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1585]
Client is reporting that the p2p sync is successful, but there are small discrepancies in the list of tasks that are showing up for the family. There are two additional tasks that appear in the supervisor app that don't appear in the CHW app. She took a video that shows what's happening (please leave volume on):

https://drive.google.com/file/d/1f-82P_CWjmgsZlksC5KxVRcVHdV2kq6J/view

The CHW account she was using was `relais1` and the supervisor account was `pcac1`

I've taken a snapshot of the video screen to show the two additional tasks that are appearing in the supervisor app that are not shown in the CHW app:

![Screen_Shot_2020-11-25_at_1_54_09_PM](https://user-images.githubusercontent.com/3488986/100273463-bbd52b00-2f54-11eb-8d3d-ba94b6d8da76.jpg)

**Comment by rkodev** [comment]
@cafootitt was the sync done 24hr after the home visit? All visits, PNC, ANC, Child Home Visit have a 24hr wait before gettting synced. 
While on other users' phones this task will appear, on the chw's phone, which recorded the visit, the task will not appear.

**Comment by cafootitt** [comment]
The reason for this is the 24 hour event processing issue - whereby events aren't synced until 24 hours later. Will explain this to the client and open a new issue if they think another error is occurring
