### ISSUE TITLE
Discussion on syncing events immediately instead of waiting for 24 hours edit period to be over

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1593]
Right now certain events in the wcaro apps do not sync (to the server or via p2p sync) until 24 hours after the event was submitted. I think the original reason for this is in the 24 hours, these events can be edited, so the sync is held off until the edit period is over. Let's discuss the implications of this and see if there's a way to sync immediately and then submit an edit event if the event is then edited within the following 24 hours.

**Comment by cafootitt** [comment]
Ronald to write up additional implementation details of how to implement this, taking into account how LMH dealt with this.
Ronald and Zain/Qazi to have a call in the next 2 hours on this.

**Comment by rkodev** [comment]
1. Turn on `allowOnSave` in the application flavor file
2. Add ability to void events by updating the properties
@qaziabubakar you can void an event by adding these 4 properties 
```
                .withSyncStatus(SyncStatus.PENDING.value())
                .withDateCreated(new Date())
                .withVoided(true)
                .withVoider("current user")
                .withVoidReason("Edited Event")
                .withDateVoided(new Date());

```
3. Ensure that the Immunization Library deletes/voids records in the vaccines table and service table. Add migrations to the 2 tables
4. Update all the reports and the methods to filter voided values

**Comment by cafootitt** [comment]
PRs for immunization and ANC libraries. Test cases and coverage being worked on now. Once finished, we can do core and chw release.

**Comment by cafootitt** [comment]
Core library PR needs to be updated with minor changes and tests, and then after merged, we can do chw library release and wrap up this issue.

**Comment by cafootitt** [comment]
Closing this issue, as QA will take place in https://github.com/OpenSRP/opensrp-client-chw/issues/1710 and https://github.com/OpenSRP/opensrp-client-chw/issues/1629
