### ISSUE TITLE
Add form configuration to the WCARO flavors - staging server - for testing

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1631]
We want to add form configuration to a wcaro app to start testing. I discussed the high level implementation plan with @dubdabasoduba on Jan 11, as follows:

1. Choose 2-3 forms to use as a demo
2. Upload those forms, check on code on the client to make sure we're calling the right activities.
3. Don't necessarily need OpenSRP web, as we can post via postman, we would just need OpenSRP web if we want to show it to the client.
4. Happy for other suggestions from @rkodev, but I'm thinking we can test on the DRC flavor, as that is the flavor that has the most form changes from the other wcaro apps and DRC is already deployed on Keycloak.

@dubdabasoduba to add link to the other issue where we need to update the batch upload script to work with KeyCloak, since that's related here.

I've also scheduled a call on Thursday this week to discuss more specifics on the implementation plan for Zain and Qazi to pick up.

**Comment by dubdabasoduba** [comment]
- [ ] https://github.com/OpenSRP/opensrp-server-web/issues/478
- [ ] https://github.com/OpenSRP/opensrp-server-web/issues/680

@cafootitt both of these issuea are key for use to have form configuration working seamlessly.

**Comment by dubdabasoduba** [comment]
> We want to add form configuration to a wcaro app to start testing. I discussed the high level implementation plan with @dubdabasoduba on Jan 11, as follows:
> 
> 1. Choose 2-3 forms to use as a demo
> 2. Upload those forms, check on code on the client to make sure we're calling the right activities.
> 3. Don't necessarily need OpenSRP web, as we can post via postman, we would just need OpenSRP web if we want to show it to the client.
> 4. Happy for other suggestions from @rkodev, but I'm thinking we can test on the DRC flavor, as that is the flavor that has the most form changes from the other wcaro apps and DRC is already deployed on Keycloak.
> 
> @dubdabasoduba to add link to the other issue where we need to update the batch upload script to work with KeyCloak, since that's related here.
> 
> I've also scheduled a call on Thursday this week to discuss more specifics on the implementation plan for Zain and Qazi to pick up.

1. We can pick the registration form, a patient visit close form (for ANC we used ANC Close form) and one other form in the app
2. Make sure the client code extends the correct activities. i.e 'FormConfigurationJsonFormActivity'

**Comment by dubdabasoduba** [comment]
Documentation on enabling form configuration can be found [here](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1507000340/OpenSRP+Document+Configurability).

**Comment by cafootitt** [comment]
Will test family registration form first.

**Comment by cafootitt** [comment]
No longer a priority, closing.
