### ISSUE TITLE
[all wcaro countries] Implement changes to the Job Aids section of the app to incorporate ECD counseling materials

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1653]
We are making changes to the UI in the Job Aids - Guidebooks section of the app to accommodate the addition of counseling materials. These changes should be implemented for all wcaro flavors.

### Current Job Aids - Guidebooks page

![image](https://user-images.githubusercontent.com/3488986/104227361-40054400-5417-11eb-8e6f-d49f99181cc1.png)

#### Two sub-menu items for Tutorials and Counseling:
https://marvelapp.com/prototype/fha17je/screen/75863145

- [x] "Tutorials" sub-menu item opens the Tutorials page (see below)
- [x] "Counseling" sub-menu item opens the Counseling page (see below)
- [x] Icons are in the Marvel hand-off section

#### New Tutorials page:
https://marvelapp.com/prototype/fha17je/screen/75863144

- [x] The current tutorial videos should be moved to this new page
- [x] Back button in top left or device back button takes the user back to Guidebooks overview page (see above)
- [x] Tutorial videos should be re-arranged in alphabetical order (A to Z) in both English and French versions

#### New Counseling page:
https://marvelapp.com/prototype/fha17je/screen/75863143

- [x] Back button in top left or device back button takes the user back to Guidebooks overview page (see above)
- [x] ECD counseling materials are arranged in alphabetical order (A to Z) in both English and French versions
- [x] Icons are in the Marvel hand-off section
- [x] PDF materials (both English and French) can be found in these folders: https://drive.google.com/drive/u/1/folders/1p8EVabHynW3QVHG6NReYALO_xuWFURw2 and https://drive.google.com/drive/u/1/folders/1rrMOu-QlJaPgHpTEaI_9R6ScR2SD8uNq
- There are 8 pdfs in English
- There are 6 pdfs in French
- [x] Tapping on one of the pdfs opens the pdf in read-only mode on the device screen (not pictured). User can tap the back or exit button or the device back button to return to this screen.

**Comment by cafootitt** [comment]
Library shared by Sam is good to use. 
Incorporating the library and updating the views should take about a day or so, so hopefully close the issue EOD tomorrow, 10 Feb.

**Comment by cafootitt** [comment]
Shift the pdfs to the DRC server for testing purposes. Plan to submit a PR today, Feb 11.

**Comment by qaziabubakar-vd** [comment]
New strings added with keys `"tutorials"` and `"counseling"`

**Comment by cafootitt** [comment]
DRC stage release 1.0.3 (19 Feb 2021) - lgtm. I'll close the issue and send you the translations on Slack after I hear back from the client. Good work!
