### ISSUE TITLE
Re-export DRC locations from DRC production server

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1669]
In the DRC location export that I was provided, the export seems incomplete compared to what we have in DHIS2, see below:

The numbers refer to the number of locations tagged as that location unit group in DHIS2 vs. the export

  | DHIS2 | Export
-- | -- | --
Pays | 1 | 0
Province(DPS) | 26 | 3
Zone de sante | 519 | 39
Aire de sante | 9027 | 698
CAC | 30 | 7
Village/Communaute | 263 | 55

Can we look into what went wrong here and see if we just need to do the export again or whether we didn't successfully import the locations from DHIS2?

**Comment by githengi** [comment]
Looks like the export was only done for 1000 locations. There are 9923 on the server. Looks like only the 1000 usually returned by the API was used
