### ISSUE TITLE
BA - Upcoming services and medical history don't appear to be working on the registers

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1686]
**Upcoming services** is not working on **most** of the registers:
- ANC
The row button to access the upcoming services appears, but when you click it, the page opens an empty/blank white page.

![Screenshot_20210209-111057](https://user-images.githubusercontent.com/20777928/107336075-c5891c00-6ac9-11eb-85ce-a83c5131c63b.png)
![Screenshot_20210209-111048](https://user-images.githubusercontent.com/20777928/107336090-c8840c80-6ac9-11eb-84c6-a63ec8cb3ddd.png)

- PNC
The row button to access the upcoming services appears, but when you click it, the page opens an empty/blank white page.

![Screenshot_20210209-111417](https://user-images.githubusercontent.com/20777928/107336030-b6a26980-6ac9-11eb-8a34-731ea3b880dd.png)
![Screenshot_20210209-111421](https://user-images.githubusercontent.com/20777928/107336036-b99d5a00-6ac9-11eb-883f-9fed66bab9f0.png)

- Child
The upcoming services appears to be working on this register
- Family Planning
The row button to access the upcoming services appears, but when you click it, the page opens an empty/blank white page.
-Malaria
The upcoming services does not appear - it should only show the follow up visit

**Comment by allan-allay** [comment]
@Mstjamush Are you refering to the member profile of a Malaria register client?

**Comment by Mstjamush** [comment]
Yes

**Comment by allan-allay** [comment]
**LOE:** ~ 2 days

**Comment by Mstjamush** [comment]
Fixed
