### ISSUE TITLE
BA - Key home visit tasks like immunisations for the child are missing from the profiles on the PNC register 

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1687]
Key home visit tasks are missing from the PNC home visit:
- Exclusive breastfeeding
- Nutrition Status of the baby (ies)
- Observation and Illness of the baby(ies)
- Immunizations for baby(ies) that did not receive BCG or OPV0 during birth

<img width="310" alt="Picture1" src="https://user-images.githubusercontent.com/20777928/107338610-c7a0aa00-6acc-11eb-8c8a-7c04169d69a7.png">

**Comment by allan-allay** [comment]
**LOE:** ~ 2 days

**Comment by Mstjamush** [comment]
Fixed
