### ISSUE TITLE
Investigate why family members aren't appearing after new app install

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#169]
I noticed this on the last couple of releases, when I install a new apk, i.e the Feb 28 build from yesterday, most of the family records in there don't have any family members listed. This shouldn't be possible, because one shouldn't be able to remove the last member and leave no family members in the household. I think for some reason they are not syncing.

Examples (using chathree login):
- Gulas Family (although I created a new record for a child just now, but the family head isn't appearing)
- Www Family
- New Family

Etc.

**Comment by rkodev** [comment]
@cagulas we solved the issue that affected the Gulas Family has been resolved. For the other 2 records reproducing the error has not been possible. The data never got to the server either. I think we can close this issue and check if it re-occurs.
