### ISSUE TITLE
Clicking the child's medical history results in the application crashing

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1694]
On the child register in a child profile, the app crashed when selecting the medical history.

To replicate:
The child must have had one home visit done. Once you fill in the home visit, the button will appear on the child's home page. However, when you click it - it crashes

![Screenshot_20210209-112250](https://user-images.githubusercontent.com/20777928/107335953-9bcff500-6ac9-11eb-8fdc-edd75847fc8e.png)

**Comment by allan-allay** [comment]
LOE: **~2 days**

**Comment by Mstjamush** [comment]
Fixed
