### ISSUE TITLE
Missing the Malaria Confirmation form on Malaria Profile

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1695]
- The row button opening the filled malaria confirmation is missing from the malaria profile
<img width="296" alt="Picture1" src="https://user-images.githubusercontent.com/20777928/107338907-22d29c80-6acd-11eb-84af-68c48a9fdf08.png">

**Comment by allan-allay** [comment]
Hi @msschroeder Are you referring to the **_follow-up visit done/edit_** row?

**Comment by msschroeder** [comment]
@allan-allay No, I am talking about the row above the Family services due row button. Where is says you tested positive on date _______ and takes you to their original malaria registration form

**Comment by allan-allay** [comment]
LOE: ~ **1 day**

**Comment by Mstjamush** [comment]
Fixed
