### ISSUE TITLE
HF - The filter on ANC, PNC, Child, FP, Malaria has overlapping text which is unreadable

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1705]
The filter on ANC, PNC, Child, FP, Malaria has overlapping text which is unreadable
![Screenshot_20210215-135453_Kituoni](https://user-images.githubusercontent.com/29072646/107964048-f7165180-6fb9-11eb-9e48-c335b8cd7f4f.jpg)

**Comment by msschroeder** [comment]
@Mstjamush This did not occur on my device. Pixel 2. What device were you using?

**Comment by Mstjamush** [comment]
@msschroeder Samsung Galaxy Edge 7

**Comment by Mstjamush** [comment]
Fixed
