### ISSUE TITLE
BA - Overlapping test on Child profile

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1708]
Overlapping test on Child profile

![Screenshot_20210215-100700_WAJA](https://user-images.githubusercontent.com/29072646/107964703-9dfaed80-6fba-11eb-8add-04ce5e84acba.jpg)

**Comment by msschroeder** [comment]
@Mstjamush I do not get this on my device

**Comment by Mstjamush** [comment]
Fixed
