### ISSUE TITLE
QA results for the DRC production release candidate (v1.0.6 - 22 Feb)

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1714]
DRC production release candidate V1.0.6 (built 22 Feb)

(All of the below was done while app set to French)

- [x] App crashes the first time you open Family Registration form, but not afterwards `worked on @qaziabubakar `
- [x] App crashes when you exit the ANC home visit page (only if you open ANC home visit from the ANC register list) `worked on @rkodev`
- [x] PNC woman does not appear immediately in the PNC register list after filling out Pregnancy Outcome form `worked on @qaziabubakar`
- [x] Birth certification not filled in when you re-open the PNC home visit `worked on @qaziabubakar`
- [x] Observed the ANC registration form getting partially filled in issue again `worked on @rkodev `
- [x] Obs & Illness is appearing before Td and Sp doses in the ANC home visit - it should sort to last in the list `worked on @rkodev `

**Comment by rkodev** [comment]
@cafootitt Was able to replicate the ANC issue, to replicate
1. Fill in a PNC outcome
2. The next ANC registration will be populated

**Comment by cafootitt** [comment]
QA Feb 24 release candidate - lgtm, awesome work!!
