### ISSUE TITLE
Vaccine data isn't cleared in home visit when you exit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#172]
I'm noticing a lot that when you exit a home visit for a child, the vaccine data you entered isn't getting cleared, because when I go back and open a home visit later on, I'm noticing a lot of time the vaccine data is still shown as recorded in the home visit.

**Comment by mahmud6390** [comment]
please check this issue after merge issue 154

**Comment by mahmud6390** [comment]
adding fix in pending PR #233

**Comment by cagulas** [comment]
lgtm
