### ISSUE TITLE
Remove sick child form from WCARO Apps

### ISSUE THREAD

**Issue by muchuri** [OpenSRP/opensrp-client-chw#1722]
app version: Togo release App Version 1.1.4 (built on 05 Mar 2021)
username: asc1
1. After login, access the All Families and select Test Family
2. Select Doe Frenetic Greenhouse record from the listing
3. Click the menu option feature at the top right corner. Sick child form, Registration info and Remove this person options are displayed
4. The Sick child form should be removed from the list of options. Registration info and Remove this person options should be left as is

**Comment by cafootitt** [comment]
V1.1.4 Togo - 10 march 2021 build date - lgtm
