### ISSUE TITLE
P2P sync performance improvements - incorrect authorization details provided

### ISSUE THREAD

**Issue by muchuri** [OpenSRP/opensrp-client-chw#1742]
The client has reported an issue with P2P sync performance improvements on different CHSS-CHA accounts unsuccessfully. The application responds with an error message is "incorrect authorization details provided"

**Comment by cafootitt** [comment]
Blocked, as we're unable to reproduce on testing accounts; waiting for the client to share the affected accounts.

**Comment by cafootitt** [comment]
Client is no longer reporting this, closing and moving to done column.
