### ISSUE TITLE
Exclusive breastfeeding options displaying opposite values on selection

### ISSUE THREAD

**Issue by muchuri** [OpenSRP/opensrp-client-chw#1747]
1. access all families listing and select a family, choose a child
2. click on record visit --> exclusive breastfeeding 0 months
3. select option No and click on Save button
4. on returning to the home visit listing, exclusive breastfeeding 0 months, it's checked green and marked as **Yes**

![Screenshot_20210329-100816_CFC Monitor](https://user-images.githubusercontent.com/10526420/112801819-04733100-907a-11eb-95fb-7b6466ea5466.jpg)

![Screenshot_20210329-100728_CFC Monitor](https://user-images.githubusercontent.com/10526420/112801839-0b9a3f00-907a-11eb-8285-dcb5e9260d81.jpg)

**Comment by cafootitt** [comment]
@muchuri This is actually correct. The way the question is worded means that "No" = exclusively breastfeeding.

**Comment by muchuri** [comment]
Ok sure this makes sense. Thanks
