### ISSUE TITLE
Child Clients  - empty listing on selecting due only

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1752]
### Pre-Condition
test was conducted on the Guinea flavor

### Steps to reproduce
1. select child clients from the drawer menu
2. switch on the due only control at the top right corner of the screen. There is a pager control that is returned with empty listing as illustrated below

![Screenshot_20210330-162554_CFC-RTM - Guine](https://user-images.githubusercontent.com/10526420/112998228-847ec100-9176-11eb-919f-2060905c078a.jpg)

**Comment by ageryck** [comment]
Guinea not use currently
