### ISSUE TITLE
Upgrade WCARO server deployments

### ISSUE THREAD

**Issue by rkodev** [opensrp/opensrp-client-chw#1759]
Upgrading all existing WCARO deployments to OpenSRP > `v2.2`. This version of OpenSRP has much-needed improvements for security, data loss fixes, data duplication and is a requirement to support the latest version of the OpenSRP chw-client.

| Deployment  	| OpenSRP Version 	|  Status 	| Current URL 					|  Updated URL 			|  K8s  |
| ------------	| -------------	| ------------	| ------------- 				| ------------- 			| ------------- |
| Chad		| v2.5.10-SNAPSHOT 	| Upgraded	| https://wcaro-td.smartregister.org 		| https://wcaro-td.smartregister.org	| No |
| DRC		| v2.5.10-SNAPSHOT 	| Upgraded	| https://wcaro-cd.smartregister.org 		| https://wcaro-cd.smartregister.org	| No |
| Guinea	| v1.* 		| Pending	| https://wcaro-guinea.smartregister.org 	| https://wcaro-gn.smartregister.org 	| No |
| Togo		| v2.5.10-SNAPSHOT 	| Upgraded	| https://wcaro-tg.smartregister.org 		| https://wcaro-tg.smartregister.org	| No |
| Liberia	| v1.*			| Pending	| https://wcaro-liberia.smartregister.org 	| https://wcaro-lr.smartregister.org	| No |

Next Steps for Guinea and Liberia

- [x] Confirm deployment timelines with the WCARO office
- [x]  Confirm the complete list of users and locations to be imported to the new servers
- [x]  Upgrade Guinea and Liberia production servers. Deploying a parallel server with the new urls can be done immediately. We can also set up a temporary separate server to complete the data migration for the 2 countries
- [x]  Users and location import to keycloak realm and opensrp
- [x]  Verify Post-deployment checklist

- [x]  Testing chw android client

Post Deployment checklist
1. Ensure the server has ID generation set up
2. Migrate Images to S3
3. Android client authentication works
4. P2P works after data migration
5. End to end testing

**Comment by rkodev** [comment]
Related issue https://github.com/onaio/infrastructure/issues/3552

**Comment by rkodev** [comment]
Server Upgrade Process from OpenMRS:

1. Backup of the current OpenSRP + OpenMRS server databases 
2. Upgrading OpenSRP server to the latest version. 
- Confirm database is running in RDS instances
- Migrate all the images to S3 if still using local storage. (Update the references in the database to S3)
3. Deploying opensrp-web
4. Shutting down the old instance of OpenMRS
5. Location import to OpenSRP
6. User import to Keycloack + OpenSRP
7. Run post-deployment checklist  

**Post Deployment checklist**

> Ensure the server has ID generation set up
> Migrate Images to S3
> Android client authentication works
> P2P works after data migration
> End to end testing

**Comment by ageryck** [comment]
This has been achieved for Liberia [preview](https://github.com/opensrp/opensrp-client-chw/issues/1870) and scheduled for [Production](https://github.com/opensrp/opensrp-client-chw/issues/1872) too. Guinea is on hold till client comes back to us on the same
