### ISSUE TITLE
UNICEF Nigeria DCIS - Addition to Google Services

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1782]
There is a need to add UNICEF Nigeria DCIS project to Google Services. This is to facilitate setting up of an autonomous environment for the DCIS project.

**Comment by rkodev** [comment]
@ndegwamartin This we can add this project to Crashlytics 

Name : **CFC Nigeria**
Package : **org.smartregister.chw.nigeria**
