### ISSUE TITLE
DRC  - deletion of dummy data from 2 accounts

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1783]
DRC  - deletion of dummy data from 2 accounts: mukoko11 and diatabau4

**Comment by muchuri** [comment]
There is a need to conduct a filter to check on old data from 2020. Client had reported there exists old data from back then. We might need to carefully evaluate if the two affected accounts have any new recent data

**Comment by hilpitome** [comment]
@muchuri what flavor of the app does this belong i.e production, staging, preview etc?

**Comment by muchuri** [comment]
@hilpitome as discussed, since there is no trace of data from the 2 user accounts from back in 2020 (latest data from the two accounts is from March 2021), closing the ticket
