### ISSUE TITLE
Togo - Account does not sync to server upon log in

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1787]
Client reported an issue with some accounts not syncing with the server upon login. The accounts are:
1. tnakoldja15
2. stinbendja90
3. nsoule90
4. kyoumanli90
5. dmaldja48
6. kboundandja81
7. sminame97

**Comment by ageryck** [comment]
@rkodev and @zzainulabidin any updates on this please

**Comment by ageryck** [comment]
No more sync issues reported for Togo
