### ISSUE TITLE
Account login failure for user account

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1791]
WCARO Chad is experiencing challenges with user account tchere99 (credentials to be shared on request). The issue was reported by field teams

**Comment by qiarie** [comment]
@muchuri Any more details you can share on the nature of the issue they are encountering?

**Comment by muchuri** [comment]
@qiarie they are not able to login to the WCARO app using this account in the field. However, they did report that from their office they were able to login. The plan is to debug the production release version and verify if the issue is present or not. Could be a device-specific issue

**Comment by qiarie** [comment]
@muchuri Please confirm that the user exists in WCARO Chad Keycloak realm

**Comment by ageryck** [comment]
@muchuri as advised by @hilpitome I have tested the user and it is currently logging in successfully
