### ISSUE TITLE
Registered Household Discrepancies After App Updates

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1793]
Client has reported an issue about registered household discrepancies after app upgrade. For instance the account 'hsambiani10' had 88 household before the app was updated but after the upgrade it has 0 households. In other cases there are accounts with increased households count after the upgrade. Attached is a list of additional accounts with similar issues. Columns K and L represent the difference in numbers of enumerated households vs after the app upgrade

[TGO CFC - kpendjal - Translated.xlsx](https://github.com/opensrp/opensrp-client-chw/files/6608893/TGO.CFC.-.kpendjal.-.Translated.xlsx)
[TGO CFC - kpendjal.xlsx](https://github.com/opensrp/opensrp-client-chw/files/6608894/TGO.CFC.-.kpendjal.xlsx)

**Comment by allan-on** [comment]
Hi @muchuri. This appears to be data synced from other locations.
- I've tested the prior released TOGO app v1.2.2 (released around March 23rd) vs the updated version v1.2.4 and the number of households are the same on both apps. 
- I've also looked at the code changes for the recent release (v1.2.4) and there are no changes that impact Sync, Events and Clients processing
- As an example for `ylamboni96`, there's additional data from ` "KPEKAKANDJI 2"` village that's part of their district location

**Comment by muchuri** [comment]
Hi @allan-on please find feedback from the client below:

_we have had this bug earlier in Dec 2020 and it was fixed. if you look at the different users, we have cases where we lost all household data. we also have cases where we have less households, and we also have cases where we have more households. let's say additional data have been synced earlier, however, this does not explain the cases where we have lost all households and cases where is have less households._

Is it possible to first investigate cases where all the households are lost? Also, is it possible to run the app's Dec 2020 version just to verify if the fix applied then was at code level and might have been overwritten by subsequent updates since them?

**Comment by muchuri** [comment]
More feedback/update from the client in verbatim below:

_if it helps, I just checked Canopy and data from significant number CHWs is not reflected. we should have at least 3 times the number of CHWs. we thought data refresh was automatic but it is not the case_

**Comment by allan-on** [comment]
Here are the findings after looking at the data on the production server and the OpenMRS instance that previously had locations and team assignments that were later imported into the new production server: 


1. For `nbomboma61` with 0 households, it appears there's no data they've ever synced to the server. Checking for any events synced by that provider Id returns 0 rows. 

```sql opensrp_wcaro_togo=> select * from core.event where json->>'providerId' like '%nbomboma61%' limit 5;
 id | json | date_deleted | server_version 
----+------+--------------+----------------
(0 rows)
```

2. For a second provider with 0 households `hsambiani10`, it appears they've been reassigned teams. 
Currently they sync by a new location Id i.e. "16abc9c4-7a2c-4b6f-ae50-a3a61d5da720" -> TIGOU 2
Yet they previously used to be in BARWAGA 1. 
On checking the DB with their old BARWAGA 1 location Id, they have synced data i.e. 68 records Last synced 2020-12-17 18:23:47

```sql opensrp_wcaro_togo=> select count(*) from core.event where json->>'eventType' like '%Family Registration%' and json->>'providerId' like '%hsambiani10%';
 count 
-------
    68
```


3. On checking the a user who has increased housholds i.e. `ylamboni96`, it appears they're syncing with multiple jurisdiction Ids 
```json
{
    "organizationIds": [
        263
    ],
    "jurisdictions": [
        "8f616485-8326-474d-8134-1cc3a5904b9e",
        "6f14860f-2aee-4f9a-80ca-8e1e619046c8"
    ],
    "plans": []
}
```
THis implies that their organisation (263) is assigned multiple locations. The household numbers being synced on the device are from a location shared with another organisation (team)
```sql 
opensrp_wcaro_togo=> select * from team.organization_location where organization_id = 263; 
 id  | organization_id | location_id | plan_id | from_date  | to_date |   duration    
-----+-----------------+-------------+---------+------------+---------+---------------
 263 |             263 |        1570 |         | 2021-03-16 |         | [2021-03-16,)
 769 |             263 |        1560 |         | 2021-05-11 |         | [2021-05-11,)
(2 rows)


opensrp_wcaro_togo=> select * from team.organization_location where location_id = '1560';
 id  | organization_id | location_id | plan_id | from_date  | to_date |   duration    
-----+-----------------+-------------+---------+------------+---------+---------------
 255 |             255 |        1560 |         | 2021-03-16 |         | [2021-03-16,)
 769 |             263 |        1560 |         | 2021-05-11 |         | [2021-05-11,)
 ```

**Comment by vincent-karuri** [comment]
Result of 

`select count(distinct json->>'providerId') from core.event;` is `409`.

Meaning that from the events table, `409` unique providers have submitted at least one event in the lifetime of the server.

**Comment by vincent-karuri** [comment]
Run query on users:

`select count(*) from core.event_metadata where event_type='Family Registration' and provider_id='<username>';`

to determine if they've ever registered a household. Results to follow...

**Comment by vincent-karuri** [comment]
[Google sheet](https://docs.google.com/spreadsheets/d/19Q8iW45rxybHqumK3AIPkt4-8TrL82vSrlfUvji8dY8/edit#gid=850863990) with the numbers

**Comment by vincent-karuri** [comment]
`select id from team.practitioner where username=<username>` to get auto-incremented user id
`select organization_id from practitioner_role where practitioner_id=<practitioner_id>` to get organizations user is assigned to.
`select location_id from organization_location where organization_id=<org_id>` to get locations associated with an organization.
`select geojson_id from location_metadata where location_id=<location_id>` to get the location uuid from auto-incremented location id

**Comment by vincent-karuri** [comment]
Looks like location sync is based off of a csv of locations https://github.com/opensrp/opensrp-client-chw/blob/aeba7970b31f89fb328868f792bb1f8e182907a5/opensrp-chw/src/main/java/org/smartregister/chw/application/ChwSyncConfiguration.java#L39. The location a user is assigned to, and locations below it.

**Comment by vincent-karuri** [comment]
`select count(*) from core.event_metadata where event_type='Family Registration' and location_id='<location_id>'` get all events tagged with a particular location uuid

**Comment by vincent-karuri** [comment]
From the findings here https://github.com/opensrp/opensrp-client-chw/issues/1793#issuecomment-861410733 we can conclude the following:


1. There exists users who have never synced data to the server before e.g. column N of rows 3, 9 and 10 
2. Users ARE receiving the correct number of household events considering the Android client's sync queries (column T)  and comparing the results to actual data in the DB (column R)
3.  The Android client's sync queries are based on a [concatenation of  locations](https://github.com/opensrp/opensrp-client-chw/issues/1793#issuecomment-862336670 ) to which the user is assigned (column Q)

With the facts above, sources of data inconsistency could arise from:

1. Incorrect location assignments where a user may see more or fewer households if they're included to or excluded from certain locations respectively 
2. Unsynced household data - users who have never synced their data will only see data from other users who share the same location(s) if any
3. Flawed location concatenation logic on the Android device  - a few of the sync queries in column T included a parent location ID (not sure that should be happening)

There's room for further verification/investigation along points 1 and 3 above.

CC @ageryck @muchuri

**Comment by vincent-karuri** [comment]
`select name,geojson_id, parent_id from location_metadata where name='<location_name>';` get location ids by location name.

**Comment by vincent-karuri** [comment]
Running the query above on 3 random users from https://github.com/opensrp/opensrp-client-chw/issues/1793#issuecomment-861410733 showed that they had at least one correct location mapping. However, their team is associated with more that one location mapping which may be a source of issues.

**Comment by ageryck** [comment]
Awesome, thanks @vincent-karuri for this detailed analysis. This is helpful and validates most of our assumptions as earlier discussed. Much appreciated, I am putting this into a presentation format to be communicated back to the client in a few. 
Finally, this confirms our position on deploying OpenSRP web for Togo too to help with locations and team management right ? cc @muchuri

**Comment by vincent-karuri** [comment]
Action points: 

https://github.com/opensrp/support/issues/12
https://github.com/opensrp/support/issues/13
