### ISSUE TITLE
Discussion on user roles implementation for CRVS

### ISSUE THREAD

**Issue by qaziabubakar-vd** [opensrp/opensrp-client-chw#1794]
In CRVS app, we have two type of user roles, one is a "CHW user" and another is "CRVS Agent". Based on the types of roles, we need to show different data for the two type of users. Currently we have two approaches under discussion from the engineering perspective:

1. Single APK Approach:
We will have a single APK for both types of users and based on what user you log in with, you'll see data visible to only that specific role. From engineering point of view, this will need to be handled in multiple switch statements or on application level. Once the user is logging into the app is syncing, we will sync the specific data for that user role, so both the roles will be handled in a single APK. There might be some implementation required on the server side. 

2. Multiple App Flavors:
In this approach, we can have two different flavors for two different role types. This means that we will have two separate APKs, one would specifically be for "chw user" and other for "crvs agent". In this approach, the client side codebase for two user roles will be well separated. Server side work maybe required for this approach as well.

Discussion is needed on which approach will we follow, going forward.

**Comment by ageryck** [comment]
Thanks @qaziabubakar for this, as discussed earlier for purposes of maintainability and ease of use from client side one would pick a single APK approach, however could implementing such switch statements within a single app have any technical downside of app functionality ? 
I invite @ukanga for and engineering perspective on this and @rowo for design perspective, as it stands now we haven't shared this with the client though its to their knowledge that we are coming up with a single app.
cc @muchuri @vincent-karuri

**Comment by dubdabasoduba** [comment]
For Point 1: 
- How do regulate the data for the different roles on the API. We ACL but we need to do some more R&D to see if it support this role-based access as we envision it here. 
- We also need to look at the possible performance implications on the app for trying to traverse and sort the data in-app. 

For Point 2:
- How much different are the two user work flows? If they aren't very different I don't think this option is viable. 

Opinion
- If we have now maojr performance implications on the app I would say we go with Option 1.

**Comment by vincent-karuri** [comment]
Cool, my 2C, I think the multi-APK approach is suitable if we expect the two apps to share a good amount of common functionality but also expect them to diverge in a non-trivial way. 

As discussed before, if we only have a few UI changes, this may not warrant maintaining two APKs (may be overkill). We can simply use the roles synced for each user (or a server-side setting? @dubdabasoduba  can confirm) and switch statements to apply the different UIs.

The down-side I see to switch statements is the risk of overdoing them. It may be best to isolate the switch logic e.g. to a util class. The idea there is to make it easier to pull out the switch logic into flavors if the use case arises later on. Single APKs can also become "massive" as they diverge more.

For data access control, I think this may be dependent on the RBAC work, yet to be merged https://github.com/opensrp/opensrp-server-core/pull/218 and https://github.com/opensrp/opensrp-server-web/pull/359.

And finally, there's the user preference on whether they'd want to maintain multiple APKs - having understood the pros and cons of course.

**Comment by ukanga** [comment]
@ageryck @qaziabubakar Do we already have designs for the different user workflows that I could review? Could you share those with me, please?

**Comment by ageryck** [comment]
> @ageryck @qaziabubakar Do we already have designs for the different user workflows that I could review? Could you share those with me, please?

@ukanga some of the design screens are available that were done by @rowo and @muchuri can share link to them. It is however notable that the designs for "CRVS Agent" forms have not been conclusively agreed upon partly subject to the discussion at hand. See workflows in the first tab [here](https://docs.google.com/spreadsheets/d/1AgO-uT8_gn7oIhZ67V7EHkCLDIi2mHvbzgPyoyo3q8Q/edit#gid=156834735)

**Comment by muchuri** [comment]
Further to the discussion in regards to the design screens, there is [this document](https://docs.google.com/presentation/d/13sQaEBDVZujOG-XQtCND5TOmNhkCX7I0Ec6hTKcT-Gk/edit#slide=id.gc50a200b02_0_6) detailing some of the proposed design approaches done by @rowo 

- We have the CRVS Agent and CHW user menu options on slide 8
- Out of area birth/death menu options for CRVS Agent on slide 11
