### ISSUE TITLE
WCARO DRC - Missing Household Data After App Update

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1806]
Client reported having lost 40 households after updating APK during field runs. Before Sync, there were 50 households assigned to the affected user. After updating the app, the number of household decreased to 10. The 40 households are presumed to be lost

**Comment by ageryck** [comment]
For user hgr1: Database shows 34 on filter by hgr1 while a sync on the device shows 75 (adding locations under it, query resulted 85 positive deviation possible with removal events)
For user hgr6: Database shows 13 while a sync on the device shows 12 (possible removal for the variance)
For user hgr12: Database shows 10 while a sync on the device shows 10
Additionally I have tested for hgr8: Database has 28 while sync on device shows 28

**Comment by ageryck** [comment]
After a review several users for WCARO DRC testing for sync with old app, and a sync after updating new app the results are ad documented [here](https://docs.google.com/document/d/1b7Py5JcQaOy_0iJBVmksAnjvrTrbeZGFaKjthTs7kEo/edit). It was notable that in some cases we had sync more than 3 times to have all the records transferred to the server as indicated in the various `create_date `timestamps. In all cases for each sync on the app was notifying the user with a toast message of _sync complete_ (This was erroneous on some cases as not all the records has hit the server)

In a bit to tame this and resolve the current stalemate for DRC, we need a confirmation whether;
1.  Will an update from playstore not delete any pending records on the device ? this could easily resolve the current fear of loosing any data that will not have been synced successfully to the server
2.  Are there any improvements that have been done (case of Reveal) on the sync functionality that surely validated records before toasting _sync complete_?

cc @muchuri @rkodev @ndegwamartin

**Comment by ndegwamartin** [comment]
@ageryck an update from **Playstore** does not delete any data from the device since we only upgrade the logic. Data can only be lost if the app is installed before fully syncing it to the server, otherwise it can still be re-synced. 

Basically the user should never have to uninstall the app from the device to do an upgrade

**Comment by ndegwamartin** [comment]
I think Reveal did make some improvements towards validation that @Rkareko can comment/advise on that.

We might also need to ship a WCaro APK with this feature to enable manual visualisation of synced records cc @qiarie @hilpitome 

![123798934-5c773900-d8f0-11eb-9183-3aad14722413](https://user-images.githubusercontent.com/10017086/124098944-b1888b80-da65-11eb-998c-6b1d333d190a.png)

**Comment by dubdabasoduba** [comment]
> After a review several users for WCARO DRC testing for sync with old app, and a sync after updating new app the results are as documented [here](https://docs.google.com/document/d/1b7Py5JcQaOy_0iJBVmksAnjvrTrbeZGFaKjthTs7kEo/edit). It was notable that in some cases we had to sync more than 3 times to have all the records transferred to the server as indicated in the various `create_date `timestamps. In all cases for each sync on the app was notifying the user with a toast message of _sync complete_ (This was erroneous on some cases as not all the records has hit the server)
> 
> In a bit to tame this and resolve the current stalemate for DRC, we need a confirmation whether;
> 
> 1. Will an update from playstore not delete any pending records on the device ? this could easily resolve the current fear of loosing any data that will not have been synced successfully to the server
> 2. Are there any improvements that have been done (case of Reveal) on the sync functionality that surely validated records before toasting _sync complete_?
> 
> cc @muchuri @rkodev @ndegwamartin

For point 1. An update will only result in loss of data if the initial app is deleted before the new one is downloaded and installed. 

For Point 2: @ndegwamartin @ageryck @rkodev can this future be added in core and maybe made configurable. With disabled by default but enabled when need be?

**Comment by dubdabasoduba** [comment]
> @ageryck an update from **Playstore** does not delete any data from the device since we only upgrade the logic. Data can only be lost if the app is installed before fully syncing it to the server, otherwise it can still be re-synced.
> 
> Basically the user should never have to uninstall the app from the device to do an upgrade

Unless clearly communicated. E.g in cases where we are upgrading from OpenMRS based to Keycloak based app auth.

**Comment by ageryck** [comment]
> @ageryck an update from **Playstore** does not delete any data from the device since we only upgrade the logic. Data can only be lost if the app is installed before fully syncing it to the server, otherwise it can still be re-synced.
> 
> Basically the user should never have to uninstall the app from the device to do an upgrade

Thanks @ndegwamartin with this assurance we can push the release app we have for DRC to playstore and have the client update on the device to avoid data loss that has been reported. cc @muchuri 
The reveal feature will be nice to have too

**Comment by ageryck** [comment]
> > @ageryck an update from **Playstore** does not delete any data from the device since we only upgrade the logic. Data can only be lost if the app is installed before fully syncing it to the server, otherwise it can still be re-synced.
> > Basically the user should never have to uninstall the app from the device to do an upgrade
> 
> Unless clearly communicated. E.g in cases where we are upgrading from OpenMRS based to Keycloak based app auth.

@dubdabasoduba are you saying for such migrations then we communicate to them to uninstall/delete before installing new ?

**Comment by dubdabasoduba** [comment]
> > > @ageryck an update from **Playstore** does not delete any data from the device since we only upgrade the logic. Data can only be lost if the app is installed before fully syncing it to the server, otherwise it can still be re-synced.
> > > Basically the user should never have to uninstall the app from the device to do an upgrade
> > 
> > 
> > Unless clearly communicated. E.g in cases where we are upgrading from OpenMRS based to Keycloak based app auth.
> 
> @dubdabasoduba are you saying for such migrations then we communicate to them to uninstall/delete before installing new?

- The engineers would know when this is required. Other than such migrations we can have other scenarios that require this. So if they advise it, then we need to communicate it and advise on syncing before uninstall. 
-

**Comment by ageryck** [comment]
This will be actioned as stated above to mitigate data loss for the current mission as we implement [this ](https://github.com/opensrp/opensrp-client-chw/issues/1820)to mitigate future data loss
