### ISSUE TITLE
WCARO Liberia - Pre-mission Issues

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1807]
- [x] Under ANC home visit, it’s not persisting the data and allowing for edit after saving (Chad version allows for editing after saving/persisting data) - _default behavior not change applied_ - Assignee: @qaziabubakar-vd 

- [x] Counselling under Job Aids not loading @zzainulabidin 

- [x] https://github.com/opensrp/opensrp-client-chw/issues/1799 Assignee: @qaziabubakar-vd 

- [x] On checking DOB is estimated it’s not hiding the field and displaying the text field to enter the estimated DOB (under add family member - child under 5 years) - _default behavior not change applied_ @zzainulabidin 

- [x] It’s possible to set previous pregnancies to 0 and surviving children to 1 under ANC Registration enter the necessary details Assignee: @qaziabubakar-vd 

- [x] Under woman profile ANC screen, the GA label is not getting updated after changing or editing ANC registration information (Faith Sewa) does not refresh immediately Assignee: @qaziabubakar-vd 

- [ ] Baby at 1 year missing week 10 immunization (could be a country setting? to be confirmed with the client)

**Comment by Mstjamush** [comment]
Issues(Liberia)

1. On checking DOB is estimated it’s not hiding the field and displaying the text field to enter the estimated DOB (under add family member - child under 5 years)
2. Once a user inputs the LMP, the weeks are in French despite the App operating in English
3. Under woman profile ANC screen, the GA label is not getting updated after changing or editing ANC registration information. It doesn't refresh immediately

**Comment by muchuri** [comment]
Feedback from client [here](https://docs.google.com/spreadsheets/d/1SoG-w4M-Ut5gdG9mi6ZvhkOi2qTFACx_WQETtZ2exYg/edit#gid=169297897) 
But under pregnancy outcome, the French issue is already fixed in the current version

**Comment by ageryck** [comment]
@muchuri review this and close accordingly
