### ISSUE TITLE
DCIS - Child Disability - Severity Choices Should be Apply for every Difficulty Type

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1818]
Under Child Clients menu option --> Select child --> Record visit --> Select Disability. Select _Does your child have any of the following challenges that impacts the ability to learn or lead a normal life_

For every difficulty type, impact of the difficulty (or difficulties)? should appear for every difficulty type

![Screenshot_20210702-121902_Nigeria DCIS](https://user-images.githubusercontent.com/10526420/124254786-16a9b300-db32-11eb-84ea-f2574ab9533b.jpg)

**Comment by ageryck** [comment]
The severity question should be a select one(was wrongly captured as checkbox in DD), @zzainulabidin  could a spinner be a better control to capture that and it be presented after every disability question?

**Comment by zzainulabidin** [comment]
Done, type change changed to spinner so that the user can select only one option.
