### ISSUE TITLE
Upcoming page is broken for some children

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#182]
For example, child Faith Ann Gulas (ID: 1838010) has a blank upcoming services page even though she has upcoming services.

![screenshot_20190304-140750](https://user-images.githubusercontent.com/3488986/53729807-4f182400-3e87-11e9-9041-7fe75d7752b7.png)

**Comment by cagulas** [comment]
@mahmud6390 Pls remember to assign issues to yourself when you pick them up.

**Comment by cagulas** [comment]
21 March release QA:

Child Susie Lea Flash (ID# 2293538) - chathree login:

- I registered her at 1 year 8 months of age, so old enough to receive every single vaccine
- In the home visit, I back-recorded all vaccines: OPV 0, BCG, OPV1-3, Penta1-3, PCV1-3, Rota1-2, IPV, MCV1-2, and YF.
- For some reason, her upcoming shows she's due for MCV 1. She already received MCV 1, so instead it should show she's due for another service

![Screenshot_20190322-152755](https://user-images.githubusercontent.com/3488986/54826887-d657fb00-4cc1-11e9-9b1e-be1b3c0d3c04.png)

**Comment by mahmud6390** [comment]
@Ephraim or Ronald can you please check the VaccineAsynctask class "nv"
nextvaccine.why it's return MCV as it's already received.sorry i have
limited access to debug.

**Comment by mahmud6390** [comment]
pending PR #283

**Comment by ephraim** [comment]
Please do not use @Ephraim as that is me. Please do use @keymane.

**Comment by mahmud6390** [comment]
> Please do not use @ephraim as that is me. Please do use @keymane.

Ahh,i am sorry,it was quick comment from my mobile.That's way it's tag with wrong suggestion.
I delete the comment. sorry for that.

**Comment by cagulas** [comment]
lgtm
