### ISSUE TITLE
Add Sync Records Complete Statistics and Progress Feature

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1820]
From the data inconsistency and data loss issues reported for both WCARO [DRC ](https://github.com/opensrp/opensrp-client-chw/issues/1806)and [Togo](https://github.com/opensrp/opensrp-client-chw/issues/1793). We have decided to upgrade the sync feature in the client app to be able to show number of records actually synced to the server with their current status/progress of the sync process. The current sync feature indicates a message `sync complete` where as there are records yet to be synced to the server.

**Requirement**
Add detail on percentage of items synced to and from the server (e.g. 26% complete) and give more statistical details on the various entities that are synced to the server. This should only allow the sync complete message to be displayed only if all records have been successfully synced to the server.

**Development**
The implementation and design can re-use existing [implementation ](https://github.com/opensrp/opensrp-client-reveal/issues/759)in Reveal.
Implementation to include [this](https://github.com/opensrp/opensrp-client-unicef-angola/issues/58)
This should be implemented to all WCARO flavors as scoped [here](https://docs.google.com/document/d/1uCEQiOCjlNskzPwdSPh0omjKboWUR6PEQPmkOCmN2vM/edit).

**Comment by rowo** [comment]
@ageryck some initial drafts of what we talked about putting reveal sync functionality into EIR. Awaiting some content from you on the stats screen and your research into if we can show some more user-valuable in the progress and stats than what exists.


![Frame 1](https://user-images.githubusercontent.com/1584163/124834014-06883e00-df4d-11eb-97c4-70c81154633a.png)

![Frame 3](https://user-images.githubusercontent.com/1584163/124834010-06883e00-df4d-11eb-84ae-d83209d97ec0.png)
![Frame 4](https://user-images.githubusercontent.com/1584163/124834012-06883e00-df4d-11eb-92a2-b770df30d805.png)
![Frame 2](https://user-images.githubusercontent.com/1584163/124834013-06883e00-df4d-11eb-865b-edfe662ee1e4.png)

**Comment by ageryck** [comment]
Done and scaled to all WCARO flavors
