### ISSUE TITLE
BA CHW - Performance of forms 

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-chw#1828]
Reference: [QA Report](https://docs.google.com/document/d/1Ti1yNqr0Upmo-XbHDTKk5uclcdgOnTIbmjwmFiEhLvw/edit?usp=sharing)

Issue: App very slow when a user is typing inputs to the fields (forms)

Reproduce:
1. Open a user profile
2. Add to a service with a form - ANC, PNC, FP, Malaria
2. Fill in the form

@Mstjamush 
1. What device did you use to test this?
2. What username did you use to test this? So as to get similar results - possible due to the number of families?

**Comment by allan-on** [comment]
There was an initial attempt at addressing this issue.
See previous research and fixes mentioned in https://github.com/opensrp/opensrp-client-chw/issues/1797#issuecomment-867495987
