### ISSUE TITLE
BA CHW  - FP form crashes when submitting

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-chw#1829]
Reference: [QA Report](https://docs.google.com/document/d/1Ti1yNqr0Upmo-XbHDTKk5uclcdgOnTIbmjwmFiEhLvw/edit?usp=sharing)

Issue: App hangs and crashes when doing a FP registration. There was a lengthy time taken while saving, before the crash.

Reproduce:
1. Open a user's profile page
2. Open the FP registration form from three dot drop down
3. Fill the form and submit

@Mstjamush 
1. What device did you use to test this?
2. What username did you use to test this? So as to get similar results - possible due to the number of families?

**Comment by hilpitome** [comment]
From the test I did with the user with username chwone I did not experience this crash on an android 11 emulator

**Comment by ekigamba** [comment]
@msschroeder 
Is this project still under support? Is this issues still present or was it resolved?

**Comment by msschroeder** [comment]
@ekigamba This was a past issue. I don't remember if it is still an issue

**Comment by ekigamba** [comment]
@msschroeder Thanks. I am going to be closing this issue. We can reopen or create another one if the issue reoccurs.
