### ISSUE TITLE
BA CHW - Navigation to All families after ANC home visit recorded

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-chw#1830]
Reference: [QA Report](https://docs.google.com/document/d/1Ti1yNqr0Upmo-XbHDTKk5uclcdgOnTIbmjwmFiEhLvw/edit?usp=sharing)

Issue: A user is being re-routed to the All Families page when he/she navigates back from recording an ANC Visit

Reproduce:
1. Open an ANC profile with a service reminder
2. Fill the form
3. Submit

@Mstjamush 
1. What device did you use to test this?
2. What username did you use to test this? So as to get similar results - possible due to the number of families?

**Comment by hilpitome** [comment]
@Mstjamush do you know where the page should reroute to after this?

**Comment by msschroeder** [comment]
@hilpitome The page should be rerouted back to the last page or if not possible, the client's profile where the ANC home visit was recorded

**Comment by hilpitome** [comment]
@msschroeder the above commit reroutes app to the ANC clients page. The family member being on top of the list

**Comment by ekigamba** [comment]
This was fixed in this PR https://github.com/opensrp/opensrp-client-chw/pull/1805 which was in reviews

Is this under project still under support and was this issue fixed? @msschroeder

**Comment by joyce-x-chen** [comment]
I think we can close this. cc: @msschroeder @samkanga @ageryck
