### ISSUE TITLE
WCARO Liberia - OpenMRS Preview and Production Server Sanity Check

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1832]
In reference to the upcoming Liberia mission (26th July), we would like to have a sanity check in preparation of the mission. Requesting checking of both preview and production environments of OpenMRS if they are functional. A spot-check of the preview environment it seems not operational. Encountered an error on attempting to login

![image](https://user-images.githubusercontent.com/10526420/125748134-f018633f-b986-4a37-8a17-d5d6dd69459c.png)

**Comment by dubdabasoduba** [comment]
**Questions to Ronald**
- Was these openmrs instances running before? If yes, why are they offline? 
- What is the LOE to bring them back up and config them again?
- What do you need for the reconfiguration?

**Questions to Lewis**
- What's the realistic deadline for this work? My guess is the 22nd? 

cc: @rkodev @muchuri @ageryck

**Comment by muchuri** [comment]
@dubdabasoduba I hoped this would have been done by 19th July to allow enough time to test stuff before the mission the following week. The issue has been raised [here](https://github.com/onaio/infrastructure/issues/4431) and is currently being looked at by @hilpitome
