### ISSUE TITLE
WCARO DRC - Missing PNC records

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1836]
After synching data from the server, the PNC indicator on the device is 0. 
Steps to reproduce:
1. Install the production version of the WCARO DRC APK (request Lewis for APK)
2. Login using production credentials (request Lewis for the credentials)
3. On successfully logging in, initiate sync, wait for sync to complete
4. check PNC indicator is 0 as illustrated below:

![image](https://user-images.githubusercontent.com/10526420/126747630-aa702fe8-88a6-4f37-a2dc-5bcc328de98d.png)

There is a need to investigate why the indicator is 0 and whether there is any PNC data associated with the location the CHWs collected the data

**Comment by hilpitome** [comment]
Currently the app marks any PNC record that is greater than 60 days old as closed. This is a possible explanation for this

**Comment by muchuri** [comment]
Thanks @hilpitome for taking time to investigate on this. I have informed the client on our findings and they seem to be happy with the explanation. Closing the ticket
