### ISSUE TITLE
WCARO DRC - Missing WASH Data

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1837]
Client reported an issue on WASH Data missing from their dashboard. Below is a comparison between what is in Togo and DRC respectively:

Togo Dashboard - WASH
![image](https://user-images.githubusercontent.com/10526420/126748784-372b15dd-7b1e-422a-9773-fe4bfa0b2a73.png)

DRC Dashboard - WASH
![image](https://user-images.githubusercontent.com/10526420/126748850-4dd505df-a0b0-48f3-8b6f-09cdc4a17ad8.png)

There is a need to investigate why the DRC WASH dashboard is blank

**Comment by hilpitome** [comment]
I looked into the wcaro DRC db and it does not have a `WASH CHECK` event. Wcaro Togo on the other hand has them.

**Comment by ageryck** [comment]
@hilpitome kindly give details description of the investigations you did on this please
