### ISSUE TITLE
WCARO DRC - At Birth Immunization Missing Data

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1838]
Client has reported missing immunization data at birth. Below is a comparison between Togo and DRC dashboard respectively

Togo Dashboard - At Birth
![image](https://user-images.githubusercontent.com/10526420/126750807-e662ccb0-909a-4917-901d-66b9ac372c19.png)

DRC Dashboard - At Birth
![image](https://user-images.githubusercontent.com/10526420/126750837-81796966-e376-4ee9-838b-8c16df5520d4.png)

There is a need to investigate the root cause of the missing immunization data

**Comment by hilpitome** [comment]
@muchuri is this still an issue?

**Comment by muchuri** [comment]
Closing ticket for now. Will re-open if issue is reported again by the client
