### ISSUE TITLE
Unicef HQ - CRVS

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1840]
Conduct sanity checks on staging servers for CRVS below;
Add sample locations (we can used test locations) and team assignments base on shared file 
- https://crvs.labs.smartregister.org/opensrp
-  https://keycloak-stage.smartregister.org/auth/
- https://web.crvs.labs.smartregister.org/fe/login 

Login access on bitwarden

**Comment by ageryck** [comment]
@muchuri attached list of requested users here please

**Comment by muchuri** [comment]
user listing for requested demo CRVS users [here](https://docs.google.com/spreadsheets/d/1V86djoojHM9hZpJ6luOGp11pkoSnzauBQyayIPUCLkU/edit#gid=0)
