### ISSUE TITLE
Add OpenMRS concept mappings for all data entry forms in wcaro

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#185]
All concept mappings are in the CFC data dictionary [here](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1085543306).

Check out the OpenMRS entity parent, OpenMRS entity, and OpenMRS entity ID columns in each individual tab.

**Comment by cagulas** [comment]
Unable to QA this, because I cannot retrieve any records in OpenMRS: https://openmrs.unicefwcaro-stage.smartregister.org/openmrs/admin/patients/index.htm. All clients registered in the app I cannot find in OpenMRS.

**Comment by cagulas** [comment]
Notes from 22 March discussion:

- Create events in OMRS only when vaccines and other services (including Vita A, Deworming, MNP) are given
- Create an event in OMRS for each exclusive bf event, regardless of whether answer is yes/no
- Create an event in OMRS for each obs & illness episode recorded in the app
- Create an event in OMRS only when birth certification equals yes

**Comment by rkodev** [comment]
@cagulas. Update on this -  we have discovered an error in OpenMRS / OpenSRP sync in the wcaro staging server. Tagged it to @manutarus to help with the config. https://github.com/onaio/playbooks/issues/1281.

**Comment by cafootitt** [comment]
I'm closing this for now. QA for OpenMRS is a lower priority for now, plus we need to make the above fix, will create a separate issue for this.
