### ISSUE TITLE
Unicef Nigeria: DCIS - update location hierarchy default plan

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1851]
Need to make update to the location hierarchy by adding a new `level 0` location to the database.

Location hierarchy file is [here](https://docs.google.com/spreadsheets/d/16Kp87Z4P3izfBPm9mUFbXU-u5G4nkHb7K2TFzg7Bjp4/edit#gid=1598386385)

**Comment by hilpitome** [comment]
@ageryck I have worked on this. It should be sorted.
