### ISSUE TITLE
Due empty state graphic

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#187]
For when the due tab is empty and they have no due home visits.

![screenshot_20190305-112312](https://user-images.githubusercontent.com/3488986/53790929-2badb180-3f39-11e9-9a49-3b9f9897d063.png)

**Comment by rowo** [comment]
No services are due
When a service becomes due for a family member, it will show up here.

![wacro-due-empty](https://user-images.githubusercontent.com/1584163/53908554-9a643b00-401d-11e9-88dc-1c34a06a924b.png)

**Comment by cagulas** [comment]
Looks great, thanks.

**Comment by cagulas** [comment]
Hi @ladleo What's the status on this one?

**Comment by ladleo** [comment]
Still working on it.

**Comment by cagulas** [comment]
QA 29 April release:

<img width="520" alt="Screen Shot 2019-04-29 at 11 53 59 AM" src="https://user-images.githubusercontent.com/3488986/56885607-8402ba80-6a75-11e9-9d6a-af5f93e4ddbb.png">
Mockup on left, screenshot of app on right

- [ ] Let's reduce the size of the icon here. Notice how the entire width of the icon roughly matches the width of the yellow line under Due tab in the mockup?
- [ ] Don't capitalize "Services"
- [ ] The text isn't matching, change it to what's in the mockup, so instead of "it shows up here" change it to "it will show up here".

Please post a screenshot of these fixes here when finished, so I can check it before the next release.

**Comment by rkodev** [comment]
@cagulas 
![Uploading Screenshot_1557237882.png…]() This is the updated design

**Comment by cagulas** [comment]
Lgtm
