### ISSUE TITLE
Upgrade WCARO Liberia from OpenMRS to Keycloak - Preview

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1870]
This is a follow up issue to this [issue](https://github.com/opensrp/opensrp-client-chw/issues/1759). We have recently made changes to the client app with new features about sync fix and progress bar badge. 
In order to scale these and other updates to the Liberia flavor there's need to upgrade the current server (v1.5) to latest OpenSRP Server and update client app to authenticate through Keycloak.

This will involve the [tasks](https://docs.google.com/spreadsheets/d/1GKZv0LdLpWv1wxunI8z-m-iRETQExx1bwflFs1oWRx0/edit#gid=0) below in order of execution;

- [x] Spin up new OpenSRP Servers for Preview 
- [x] Setting unique ID generation - preview server
- [x] Setting up default plan - preview server
- [x] Create new realms on Stage keycloak 
- [x] Deploy OpenSRP Web Preview Instances
- [x] Location and Users Import to Keycloak and OpenSRP - Preview
- [x] Data Migration to Preview
- [x] Generate a production release pointing to preview for QA
- [x] System testing and data verification - Preview

**Comment by ndegwamartin** [comment]
**Resources**
- [How+to+Configure+Unique+IDs+sources+on+OpenSRP](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/2899345409/How+to+Configure+Unique+IDs+sources+on+OpenSRP)
- [OpenSRP data migration and import tool](https://github.com/opensrp/opensrp-data-import)

**Comment by ageryck** [comment]
Preview Env is considered successful after apk passed QA
