### ISSUE TITLE
Upgrade WCARO Liberia from OpenMRS to Keycloak - Production

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1872]
This is a follow up issue to this [issue](https://github.com/opensrp/opensrp-client-chw/issues/1759). We have recently made changes to the client app with new features about sync fix and progress bar badge. 
In order to scale these and other updates to the Liberia flavor there's need to upgrade the current server (v1.5) to latest OpenSRP Server and update client app to authenticate through Keycloak.

This will involve the [tasks](https://docs.google.com/spreadsheets/d/1GKZv0LdLpWv1wxunI8z-m-iRETQExx1bwflFs1oWRx0/edit#gid=0) below in order of execution;

-  Spin up new OpenSRP Servers for Production
-  Setting unique ID generation -  Prod servers
-  Setting up default plan - Prod servers
-  Create new realms on Production Keycloak
-  Deploy OpenSRP Web Prod Instances
-  Create DB backups for the current OpenSRP Server and OpenMRS
-  Location and Users Import to Keycloak and OpenSRP - Prod
-  Data Migration to Prod Server
-  Location and Users Import to Keycloak and OpenSRP - Prod
-  Create production release and deploy to playstore for QA 
-  System testing and data verification - Prod
-  Request for client downtime for switch

**Comment by allan-on** [comment]
**Migration of users to keycloak & locations/teams to OpenSRP:** 
- [ ] Ensure all devices have synced
- [ ] Shutdown the "old" production
- [ ] Take a backup of the database
- [ ] Deploy new server version with a temp domain + run migrations on the current database instance
- [ ] Import locations, teams, users etc 
- [ ] Release( APK and switch to the permanent domain)

For QA: 

- [ ] Install the current Playstore version and test app update with the new APK

**Comment by ageryck** [comment]
Client mentioned devices were all synced saved for very few approximated devices.
Importation of [users](https://docs.google.com/spreadsheets/d/1mpkcYS_yh_on4DjwzKFyjnc3KRyipAyc/edit#gid=1759019684) will be conducted from a cvs file, this follows new requirement by the client to generate generic usernames ans password for all existing users in addition to few additional users. 
There will not be any resulting effect of new usernames and password both on the client app side and the dashbaord and the location and team assignment will be maintained. The only foreseeable effect will be upon troubleshooting, the filter by `provider_id` should reference both old and new `usernames` (to be documented).

**Comment by allan-on** [comment]
The users and team assignments are as defined in this Spreadsheet https://docs.google.com/spreadsheets/d/1-IOSKHB4ZwA4fNyiSF0UgqhU7eZg4QmA/edit#gid=870990558

**Comment by ageryck** [comment]
thanks @allan-on and @muchuri I am closing this, we can consider migration successful. Any upcoming issues to handled as newly arising issues
