### ISSUE TITLE
WCARO Togo - Not able to login for version v1.0.13

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1882]
On entering correct production user credentials, the application returns the error message below:

![Screenshot_20210907-185932_CFC-RTM - Togo](https://user-images.githubusercontent.com/10526420/132376000-ba64e0b0-c0d4-4293-ab34-e024ae6a6519.jpg)

APK used to reproduce this issue to be shared separately including the user credentials. 

Initial suspicions was the OS version, but tests where conducted using even Android 7 which behaved the same way and only affected opensrp-chw-togo-v1.0.13-jan version

**Comment by allan-on** [comment]
@muchuri Which Server end-point is that version pointing to? Please check from that 3 dot (kebab) menu on the login screen

**Comment by muchuri** [comment]
@allan-on please find below the server settings below:

![Screenshot_20210907-192059_CFC-RTM - Togo](https://user-images.githubusercontent.com/10526420/132378711-acb6f042-1751-4dc8-a008-d5407f8937ba.jpg)

**Comment by allan-on** [comment]
@muchuri The server instance is an old instance that no longer exists. 
This instance https://wcaro-togo.smartregister.org/opensrp/ is unreachable

**Comment by allan-on** [comment]
The new end-point is https://wcaro-tg.smartregister.org/opensrp/ but this end-point points to the server version that uses Keycloak for authentication.
This means even if we update the endpoint from the settings, the Android app being tested doesn't support authentication via Keycloak.
