### ISSUE TITLE
Out of area birth - App review issues

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1889]
- [x] Access the out of area birth option on app. Select any record and navigate to the form in edit mode. The Reason dropdown should be removed since the form represents registration of death
- [x] Still in the same form, if gender selected is Female, under the newly added questions (If yes, has the pregnancy contributed to the death) still shows if the event gender is changed to Male

**Comment by muchuri** [comment]
In relation to 
_Still in the same form, if gender selected is Female, under the newly added questions (If yes, has the pregnancy contributed to the death) still shows if the event gender is changed to Male_
a similar issue has been encountered under add family head form for members between the age of 5 - 18 years where different education options are presented. Steps to reproduce are as follows:

1. from the family listing, select family head from the list of family members
2. click on the 3 dots at the top right corner
3. select registration info option
4. set the date of birth to below 18 years
5. **_Has the child ever attended school or any other early childhood education programme?_** dropdown appears. Select Yes
6. **_What level or year of school is s/he attending right now?_** dropdown appears. Select any option
7. change date of birth to be above 18 years old. Both dropdowns in 5 & 6 above disappear
8. set the date of birth to below 18 again, only drop in 5 appears with option set to Yes

**Comment by ageryck** [comment]
@qaziabubakar follow up on this

**Comment by charlene-570** [comment]
@muchuri this is tested and in the clear
