### ISSUE TITLE
DCIS: Test APK (Prod release pointing to stage)

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1899]
Create a production release pointing to [stage](https://dcis-ng.labs.smartregister.org/opensrp/) after addressing the following [issue](https://github.com/opensrp/opensrp-client-chw/issues/1883)

**Comment by allan-on** [comment]
The [2nd Field Testing - Volunteers feedback Issues](https://github.com/opensrp/opensrp-client-chw/issues/1883) was addressed in this [commit](https://github.com/opensrp/opensrp-client-chw/pull/1774/commits/23195dbdea3fa7ba6bca405596d61d0d4af27583). 

This work is already part of the features/fixes in the APK built on Thursday 16th Sept for the QA release with the server URL pointing to the WCARO _Stage_ server.

**Comment by ageryck** [comment]
@muchuri kindly take note am therefore closing this

**Comment by ageryck** [comment]
@allan-on the apk that was released is pointing to wcaro-shared-stage, we need a new test apk that is pointing to the correct stage env for DCIS, link above.
cc @muchuri

**Comment by allan-on** [comment]
@ageryck This is done ✅
