### ISSUE TITLE
DCIS - Final QA Feedback

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1904]
DCIS App, the following issues have been noted from QA
- [x] Wash check data not saving on DB
- [x] Some data elements save labels instead of spinner options e.g. `fam_source_income` and `income_bracket` and some wash event responses
- [x]  After p2p Supervisor device cannot conduct internet sync, gives an error -sync failed
Upon resolving this, the app needs a quick QA and a production release be created pointing to [prod](https://dcis-ng.smartregister.org/opensrp/) instance

**Comment by ageryck** [comment]
![chss_sync](https://user-images.githubusercontent.com/23252704/134238710-d398d2c1-e62c-4732-9ead-6092ea99cec4.png)

**Comment by muchuri** [comment]
1) Confirmed WASH Check data was hitting the DB
2) Synced failed issue resolved as well after setting the APK to point to DCIS staging server

**Comment by zzainulabidin** [comment]
fam_source_income and income_bracket question in family registration save their hint if the user didn't select any option. There is a bug in native form lib. For now, I applied check on chw app if fam_source_income and income_bracket have values equals to the hint then the values will be removed.
