### ISSUE TITLE
Create Total U5 children indicator

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#193]
Refer to [Reporting](https://docs.google.com/spreadsheets/d/1q9YiWqjLiToTd0--Q8CbwhBwwcNDspbDxVrUfDm8VGU/edit#gid=1627225414) dictionary for reference.

Label: Total U5 children

Calculation: Count of all U5 children who are registered in the child register (i.e. all children aged 0 to < 60 months). Note, this should match the number of children shown in the app side menu.

<img width="382" alt="screen shot 2019-03-06 at 12 31 12 pm" src="https://user-images.githubusercontent.com/3488986/53935396-34c48d00-40b7-11e9-898b-fb663c618426.png">

Note: In the event the mockup does not match the content in this issue and in the reporting dictionary, ignore the content in the mockup and use what's in this issue and the reporting dictionary only.

@rowo Can you please provide the font size, color codes, spacing instructions, etc. for this indicator? Please un-assign yourself from the issue afterwards.

**Comment by rowo** [comment]
![screen shot 2019-03-07 at 2 45 26 pm](https://user-images.githubusercontent.com/1584163/53984650-bb915e00-40e7-11e9-9643-422826b6f52f.png)

A
font-family: Roboto-Regular;
font-size: 17px;
color: #212121;
letter-spacing: 0;

B
font-family: Roboto-Bold;
font-size: 32px;
color: #212121;
letter-spacing: 0;
text-align: right;

C
font-family: Roboto-Light;
font-size: 15px;
color: #757575;
letter-spacing: 0;

**Comment by cafootitt** [comment]
lgtm

**Comment by rowo** [comment]
Feedback: UI/UX Request: in the in-app dashboard, some ASC (especially those with poor eyesight) get confused which pie graphs refer to which indicators. Can we make the borders/contrast clearer/darker?

Can you provide a screenshot from the current build they are responding to @cafootitt ?

**Comment by cafootitt** [comment]
Ok, here you go. I looked and it is identical to what's in the issue comment above, so I figured I'd just send you the issue link, but here you go:

![Screenshot_20191014-171226_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/66766410-09d7be00-ee7c-11e9-9e22-ff749e7a2ba4.jpg)

**Comment by rowo** [comment]
@cafootitt thanks Carolyn. I think changing the border lines from 1px line to a 4px line and changing color to #DEDEDE should improve contrast enough.

![Group 8 Copy](https://user-images.githubusercontent.com/1584163/67336435-5e6ddf80-f4f3-11e9-950f-50e8bf42326b.png)

**Comment by cafootitt** [comment]
Thanks!

**Comment by cafootitt** [comment]
Moved to new implementation issue: https://github.com/OpenSRP/opensrp-client-chw/issues/932
