### ISSUE TITLE
Completed task on Volunteer's device not appearing on Supervisor's device

### ISSUE THREAD

**Issue by muchuri-zz** [opensrp/opensrp-client-chw#1949]
### Reported Issue

A supervisor in Bauchi reported inability to view completed tasks that have already been submitted by a volunteer on their device. Below are sample screenshots from a volunteers device with a task completed:

![image](https://user-images.githubusercontent.com/10526420/140513704-cd3fd224-1dc8-4bd5-a3e3-4f6673fd864a.png)

Below is the supervisor's screenshot indicating the task not completed for the specific family with 3 pending tasks:

![image](https://user-images.githubusercontent.com/10526420/140513926-e979294a-0e73-44a0-8423-6469536e91e6.png)
 
### What is needed?
Check from the backend OpenSRP DB if there is any pending services associated with the volunteer which could be flagging from the supervisor device as incomplete task

**Comment by allan-on** [comment]
@muchuri We don't store any  Visits or Services data on the server. 
We only store the related events and compute whether a task is done or due in the app based on the events

**Comment by muchuri** [comment]
I have requested the client to share DB extract from the devices for further analysis from our end. Hope this will help @allan-on

**Comment by muchuri** [comment]
@allan-on please find the DB extracts [here](https://drive.google.com/drive/folders/1uzphOyAleBK1ZrrAO_Dt1P6GieLL1S5X?usp=sharing)

**Comment by allan-on** [comment]
@muchuri After checking data synced on the device for the supervisors and volunteers that were shared as well as checking the DB extracts, the findings are:
- For families synced, the correct status is displayed on the register.
- On the supervisor devices, there are multiple families having similar names hence the likelihood to mistake a family for another displayed on the volunteer device - This is most likely what is happening. 
To avoid this they can check that the family members in each family match.
Here are a couple of screenshots illustrating the above-mentioned observations.
 
**Sani Familiy**
<img src="https://user-images.githubusercontent.com/16164649/143007550-6dfbd026-271c-48e9-bb6e-853d30928a56.png" width=60% height=60% />

**Aliyu Family**
<img src="https://user-images.githubusercontent.com/16164649/143007527-b2e85e0f-a4cd-43df-b9ad-4c693cd1dff4.png" width=60% height=60% />
