### ISSUE TITLE
QA feedback issues

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1954]
After QA run tests on the latest APK version of the CRVS app, the following issues were encountered.

- [x] Under the Job Aids menu, Guidebooks tab, the following resources cannot be downloaded:
1. ANC Registration
2. ANC Visit

- [x] The counseling download page is empty

**Comment by zzainulabidin** [comment]
Issue resolved.
Update the guidebook URL from [CHAD](https://opensrp.s3.amazonaws.com/media/chad/ ) flavor to [TOGO](https://opensrp.s3.amazonaws.com/media/togo/) and tutorials are working fine now. Keep that a note [CRVS](https://opensrp.s3.amazonaws.com/media/crvs/) guidebook URL is not working and didn't respond any tutorials.

**Comment by ageryck** [comment]
All tutorials and guide books downloading successfully
