### ISSUE TITLE
CRVS UNICEF HQ Pregnancy outcome event table has multiple lbw variables

### ISSUE THREAD

**Issue by muneneg** [opensrp/opensrp-client-chw#1956]
We have 3 different lbw... objects under the "pregnancy_outcome_table", in other deployments, we just have 1. Also, why do you have a key code added to the variable. -- see image below

![image](https://user-images.githubusercontent.com/41571129/143030130-75d6c06e-edda-4a48-bee2-d5b158d0767d.png)

**Comment by muchuri** [comment]
@allan-on kindly can you assist in investigating this issue

**Comment by allan-on** [comment]
@muneneg This is the event JSON?

**Comment by allan-on** [comment]
### Due and Overdue count bug:
- On log in for the first time, the count is different from when navigating to the Register afterwards. 
- The count is updated onResume and onSyncComplete. 

This implies on first log in the incorrect count shows when sync is marked as complete yet the due and overdue computations aren't complete.

**Comment by ageryck** [comment]
worked on additional implementation worked under issue
