### ISSUE TITLE
Feedback issues after review with client

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-chw#1962]
- [x] Click birth certification menu --> Update status --> Change Select birth registration type label to `Select Informant` and change relevance as indicated in DD
![InkedScreenshot_20211125-110328_CRVS_LI](https://user-images.githubusercontent.com/10526420/143404137-0a8d83fe-4fe2-489a-a85e-0a75b6cda74f.jpg)

- [x] Add the term `(Stillbirth)` under the death certification listing for death resulting from pregnancy outcome=stillbirth, All death listing to include;
- Name, Age, Place of Death and Sex - For Adult

- CG:Name, Name, Age, Place of Death and Sex - For Child

- CG: Name, [Stillbirth], Place of Delivery/Death - For Stillbirth

![InkedScreenshot_20211125-134319_CRVS_LI](https://user-images.githubusercontent.com/10526420/143427961-b5067fde-6de5-40bb-abf1-4051eeb30f0c.jpg)

- [x] Hide the notification label under birth registration form  even if relevance is met  _**Ask to see the birth notification and instruct the caregiver to register the birth at County Health**_, do not delete as we may bring it back after UAT tests
![InkedScreenshot_20211125-135147_CRVS_LI](https://user-images.githubusercontent.com/10526420/143428477-a7560ea6-181d-4d01-9e6e-fb3148d8ad16.jpg)

- [x] Misspelling of the Birth registered by under birth registration form
![InkedScreenshot_20211125-135147_CRVS_LI2](https://user-images.githubusercontent.com/10526420/143429190-a95c771c-dac8-4fe0-805a-da5d1142da61.jpg)

**Comment by ageryck** [comment]
-[ ] Remove Hospital as a choice in out of area birth registration for question birthplace

**Comment by ageryck** [comment]
Issues resolved
