### ISSUE TITLE
Placeholder Issues - WCARO Togo

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1963]
Below are some issues reported for WCARO Togo under going tests to help reproduce;

- [x] Remove child with reason death, child still exists in the register
- [ ] Dashboard figures differs from app figures - Village of Bawalessi in USP Bitchabe (`nbassar87`) - screenshots [here](https://drive.google.com/drive/u/1/folders/1S5OrIeeVbOBzTx6lgTQNol4av06yg-fr), tasks completed on app reflecting as pending on dashboard

**Comment by ageryck** [comment]
Preliminary tests indicate remove child work okay as child is successfully removed and indicated with status `deceased`

**Comment by ageryck** [comment]
During a meeting with client the in-app charts showed different figures across two devices after a successful sync with server, there need to determine the mode of calculations to ascertain the app is correctly calculating the figures being shown.  

@allan-on would it be possible to generate the queries used for the in-app indicators so that we can take device db extracts and run to make comparisons ?

**Comment by allan-on** [comment]
@ageryck Yes, it is possible to get the queries. The indicator queries are defined in a YAML file i.e. 
[child-reporting-indicator-definitions.yml](https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/src/main/assets/config/child-reporting-indicator-definitions.yml) file

**Comment by ageryck** [comment]
@zzainulabidin kindly document test you have conducted regarding second issue here

**Comment by ageryck** [comment]
Investigations in to the second issue resulted into findings that each device has different timelines depending on the device processing capacity to execute an after sync processing of events data from server side back to tasks in order for the inapp reporting page to correctly indicate the number at device level. It was however  noted that in fullness of time after different devices syncing the same account should finally to able to show matching data.
We have recommended additional test with various devices/accounts to ascertain this.
