### ISSUE TITLE
In-App Supervision Indicators - Discussion

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1965]
As a contractual requirement we have a deliverable to create in-app supervisor indicators to help in monitoring CHW's and their work. This work is been scoped [here](https://docs.google.com/document/d/1l_TgsqO8kZpNzZxhqjJ8TvWUJDv-Mmha2x_toA7_Khg/edit#)
The desired indicators are defined in this [doc](https://docs.google.com/document/d/1rKjXwQIpc7vYJZoVii6HbUPq2rDBo16i/edit) and are intended to be displayed in-app.
Since the CHW/Supervisor app is just the same app no different flavors, we are looking at creating just a single design, same indicator definition and display but intending to rely on user level/team assignments/location hierarchy to display the same. If a CHW log into the app they can see only their performance/calculations are based on the data within their assigned location/team, however if a supervisor logs into the app they are able to see aggregated data from all the CHW under their assigned team/location.

Questions is 
1. How possible is this, can confidently rely on the location hierarchy/ team assignments to achieve this task ?
2. The aggregated data at supervisor level may sometimes need to displayed in a table like dis-aggregated by CHW is this a design that can be accommodated ?
3. Can we only show this report to supervisors i.e. determine who a user is and if they are supervisors then render this view ?

**Comment by ageryck** [comment]
@allan-on when you get a moments let me know thoughts on the above questions/considerations.

**Comment by allan-on** [comment]
1. Can we rely on the location hierarchy/ team assignments to achieve this task ?
>  Team assignments and location hierarchies will allow supervisors to sync all data synced by their respective CHWs since sync is by location. 
The hierarchies and assignments are mainly for data sync and so we'll need the implementation to tie CHWs to a Supervisor for some of the queries. 

2. The aggregated data at the supervisor level may sometimes need to display in a table like dis-aggregated by CHW is this a design that can be accommodated ?
> Yes, for data that's associated with a `providerId` or `anmId` e.g. `Events`. The data will be filtered by the providerId

3. Can we only show this report to supervisors i.e. determine who a user is and if they are supervisors then render this view ?
> Yes, we can have a different dashboard view for supervisors. On login, we can get the practitioner role. This role is what will be used to determine which reporting dashboard view to render.

**Comment by ageryck** [comment]
@rowo we may need some advise on the placement on of the new indicators and possibly some design screens especially for indicators with table like results

**Comment by ageryck** [comment]
@rowo [here ](https://drive.google.com/drive/u/1/folders/1jsV0xL9FpXv6EbvUNpGCQPXkrPmQhtwL)are the current screenshots

**Comment by ageryck** [comment]
@rowo did you manage to put some mock screens for this, kindly share

**Comment by rowo** [comment]
@ageryck please see https://www.figma.com/file/Gan8PFBKHYjRd6zSPvfhnQ/WCARO---Design-edit?node-id=614%3A855

- I'm not sure about the label wording. Should review, I think it's related to my second point..
- In dashboards I always think its confusing to do the opposite of what's expected, especially if a pattern is established to start with. The example is the first indicators look at a completion rate (more is better) and then it flips when it looks at the CHWs to say "task incompletion rate" (more is worse). Why not just keep the same completion rate but reverse the order of the sort? 

<img width="360" alt="Job Aids - Dashboard" src="https://user-images.githubusercontent.com/1584163/152095989-612219bb-b48d-4679-a17f-b254c3d82a7c.png">

**Comment by ageryck** [comment]
@rowo thanks for this, we will use it. I agree with your point on first indicator, however still thinking even with the count of CHW,s who have completed tasks isn't more still better ?

**Comment by ageryck** [comment]
@allan-on and @zzainulabidin see above design mock up for our use.
