### ISSUE TITLE
CRVS: DRC UAT - Users, Teams and Location Set up

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1968]
This issues help set up users, teams and locations for the planned UAT in DRC on the production servers below;
- List of [users](https://drive.google.com/drive/u/1/folders/1XldzYtC7fUISQKM1hZFSqq9qWDfupnYI) shared by client
- We have the option of importing all locations and teams from the current [WCARO DRC](https://web.wcaro-cd.smartregister.org/) Instance and only creating users selected for the UAT.
- Selected [Users](#) for UAT
- Trainer Accounts 
OpenSRP Server Details:
CRVS OpenSRP Production Server https://crvs-cd.smartregister.org/opensrp/
OpenSRP Web https://web.crvs-cd.smartregister.org
Access on Bitwarden Collection `UNICEF HQ Crvs DRC Production`

Tasks:
- [x] Creation of [users](https://docs.google.com/spreadsheets/d/1ed4y492E26a3Cr8F0RPFtDQBCiZ1yzR2/edit#gid=630870597)
- [x] Creation of Locations
- [x] Creation of Teams
- [x] Posting of default plan
- [x] Verifying Unique ID generation

**Comment by allan-on** [comment]
- Locations added ✅ 
- Organizations/Teams added ✅ 
- Users added on Keycloak✅ 
- Practitioners added ✅ 
- **Practitioner roles added** ❌  -> Encountered an error with the Data import tool. To be resolved separately
- Default plan posted ❌ 
- Unique ID generation verified ❌

**Comment by ageryck** [comment]
This issue is pending correcting team assignment for demo account and testing it out, everything else is closed
