### ISSUE TITLE
WCARO: Inapp Reporting 

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1970]
using the guidance provided on this [issue](https://github.com/opensrp/opensrp-client-chw/issues/1965) and as scoped on this [doc](https://docs.google.com/document/d/1l_TgsqO8kZpNzZxhqjJ8TvWUJDv-Mmha2x_toA7_Khg/edit), this is to track the work around engineering the new inapp reporting requirement. Some of the major deliverable under this is;
- [x] write calculation queries for all the indicators as defined [here](https://docs.google.com/document/d/1rKjXwQIpc7vYJZoVii6HbUPq2rDBo16i/edit)
- [x] create dashboard forms in app
- [x] implement relevant job processing logic
- [ ] write tests
- [ ] Merge and publish
- [ ] scale to all WCARO flavors 

Assigned engineer to edit issue as appropriate

**Comment by ageryck** [comment]
This was advised that there will be no need to scale to all flavors

**Comment by zzainulabidin** [comment]
I have pushed the updates made for indicator into [this](https://github.com/opensrp/opensrp-client-chw/pull/2015) branch.
These changes include adding the 3rd tab into the indicator screen with all the 5 required queries written into this [yml ](https://github.com/opensrp/opensrp-client-chw/blob/0883685c5b265b283aa062ebb9cd14c5b5c2769a/opensrp-chw/src/main/assets/config/supervisor-reporting-indicator-definitions.yml) file.
Currently, one indicator 2nd in issue is working. We need further progress to show the remaining indicator using the multipart feature in the indicator library.

**Comment by ageryck** [comment]
@allan-on kindly give guidance on the most updated code for this to guide @qaziabubakar to start looking into this

**Comment by ageryck** [comment]
@allan-on we have determined with @qaziabubakar that the `schedule_service` table contains only the current month's tasks meaning we can't query for previous months' tasks completion. Kindly help shade light on how the data on the table is handled at the end of the month. Does the table refresh recurring tasks?

**Comment by allan-on** [comment]
The Schedule job runs on initial login and subsequently every 12 hours (default duration).

When the job runs:
- All schedules created prior to the current date are deleted (i.e. schedules not created today) then 
- The schedules are recomputed based on the latest visit data for clients whose entity Ids aren't in the `schedule_service` table after old schedules were cleared. 

The workflow described is the reason there's no historical data
