### ISSUE TITLE
CRVS: ANC Registration redirects to login screen on save

### ISSUE THREAD

**Issue by allan-on** [opensrp/opensrp-client-chw#1979]
On clicking save after filling in the ANC Registration form, the app navigates to the login screen

**Steps to reproduce:** 
- Go to a family (WRA) member and do the ANC Registration, then save

**Comment by charlene-570** [comment]
@allan-on Test results on this
    • User is not redirected to Login sreen but Family members listing screen

See screen recording attached

https://user-images.githubusercontent.com/85434942/149947221-3a9aa501-6567-4894-88ec-a88b0b3c02f0.mp4

**Comment by ageryck** [comment]
@charlene-570 the recording is for new child registration not Women in Reproductive Age (WRA), you may need to select or add woman to a family aged between 15-49 to be able to register them for ANC.
@allan-on is that correct ?

**Comment by ageryck** [comment]
> @charlene-570 the recording is for new child registration not Women in Reproductive Age (WRA), you may need to select or add woman to a family aged between 15-49 to be able to register them for ANC. @allan-on is that correct ?

Issue reproduced on issue #1980
