### ISSUE TITLE
CRVS: Implement correct relevance for the remove family member options

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1985]
We will keep the remove reason question, this is to align the app to other CFC flavors and since client is potentially thinking of updating the CRVS modules into existing WCARO flavors.

For remove family member [child under 5 and adults];
- [x] keep remove reason question
- [x] if reason is death present all relevant questions based on the relevance defined [here](https://docs.google.com/spreadsheets/d/138JD_Zn3xTSsACn5cq8ZlGyeC8BEzmiU0XDKm1_Moeg/edit#gid=1085543306)
- [x] currently remove child under 5 is different from the adult one, the forms should look exactly the same with correct relevance implemented

**Comment by joyce-x-chen** [comment]
The death questions are still appearing in the `Remove family member` form even if the reason for removal is "moved away" or "other." @zzainulabidin

**Comment by ageryck** [comment]
Issue resolved
