### ISSUE TITLE
Create Children (0-59 months) with a birth certificate indicator

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#199]
Refer to [Reporting](https://docs.google.com/spreadsheets/d/1q9YiWqjLiToTd0--Q8CbwhBwwcNDspbDxVrUfDm8VGU/edit#gid=1627225414) dictionary for reference.

Label: Children (0-59 months) with a birth certificate

Calculations:

Green - Count of children aged 0 and < 60 months who have a birth certificate (birth_cert = yes).

Red - Count of children aged 0 and < 60 months who do not have a birth certificate (birth_cert = no).

<img width="373" alt="screen shot 2019-03-06 at 12 31 34 pm" src="https://user-images.githubusercontent.com/3488986/53935985-62123a80-40b9-11e9-8b51-b3fdd3418630.png">

Note: In the event the mockup does not match the content in this issue and in the reporting dictionary, ignore the content in the mockup and use what's in this issue and the reporting dictionary only.

@rowo Can you please provide the font size, color codes, spacing instructions, etc. for this indicator? Please un-assign yourself from the issue afterwards.

**Comment by rowo** [comment]
Specs here: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/193#issuecomment-470667482

**Comment by cafootitt** [comment]
lgtm
