### ISSUE TITLE
CRVS: App auto logs out

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1993]
The app auto logs out, at times on idle other times on active use of the app.
The screen below contain the error message toasted during the log out.
![image](https://user-images.githubusercontent.com/23252704/152942820-5ae75d4e-c5a9-4066-a0bc-b382160d6156.png)

**Comment by ageryck** [comment]
see additional suggestion/feedback [here](https://github.com/opensrp/opensrp-client-chw/issues/1983#issuecomment-1032366547)

**Comment by allan-on** [comment]
With perioding syncing, there's an authorization verification prior to syncing to the server. 
If the session has timed out and the access token is invalidated the user is logged out. 
The session timeout has been increased on Keycloak to mitigate this.

**Comment by ageryck** [comment]
> With perioding syncing, there's an authorization verification prior to syncing to the server. If the session has timed out and the access token is invalidated the user is logged out. The session timeout duration has been increased on Keycloak to mitigate this.

@allan-on can we reword the alert then to be more just informative without redirecting them to admin and avoid disabled
