### ISSUE TITLE
CRVS: Death/Birth Summary Order

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1996]
- [x] order both birth and death summaries by latest record first, order by DESC (latest record)
- [x] Out of Area death form, Age at death not auto calculated

**Comment by zzainulabidin** [comment]
Out of Area death form, Age at death will auto calculate when you enter DOB and Date of death.

**Comment by ageryck** [comment]
@zzainulabidin kindly relook into this
