### ISSUE TITLE
CRVS: Pregnancy outcome form - baby details are asked in French

### ISSUE THREAD

**Issue by joyce-x-chen** [opensrp/opensrp-client-chw#1999]
When completing the `Pregnancy Outcome` form in the CRVS app (stage release from 4 Feb), the baby details are asked in French. 

Steps to replicate:

1. Log in to app and set language to English, if needed
2. Find a pregnant woman within a household
3. Start `Pregnancy outcome` form
4. Select live birth, enter recent date, health facility, 1 child born
5. Press checkmark after entering number of children born to generate "baby details" form

"Baby details" form populates in French.

I checked if the reverse happens when the language is set to French. It does not. However, "Number of children born" is not translated. This should say "Nombre d'enfants nés." Also, the select-one options for "Type of pregnancy" are not translated. They should be:

- Singleton > Unique
- Twin > Jumeaux
- Triplet > Triplé
- Other > Autre
- Unknown > Inconnu

**Comment by charlene-570** [comment]
@joyce-x-chen @zzainulabidin  Kindly view screenshot 
![Screenshot_20220214-120110](https://user-images.githubusercontent.com/85434942/153832755-076a2f44-6590-4166-97f6-a64fe5e70a01.png)

**Comment by ageryck** [comment]
resolved
