### ISSUE TITLE
CRVS: Infants <28 days old not added to birth certification list

### ISSUE THREAD

**Issue by joyce-x-chen** [opensrp/opensrp-client-chw#2000]
When a birth is recorded via the `Pregnancy outcome` form, the infant is not added as a family member immediately and their birth certification status cannot be updated. Steps to replicate:

1. I recorded the pregnancy outcome of a live birth. Date of delivery is yesterday / i.e. infant is 1 day old. The infant was not added to the list of family members nor to the `Child Clients` list. 
2. The mother's status did change from ANC to "PNC Day 1" and she was moved to the list of `PNC Clients` successfully. 
3. If I click on the woman, I'm able to see that she has a one-day old infant and I can edit the baby's details from the mother's record. 
4. If I edit the baby's details to make her more than 28 days old, then the baby appears in the list of family members. 
5. If I edit the baby's details to make her less than 28 days old, the baby disappears from the list of family members and from the mother's profile. 

Step 4 and 5 are not expected events, but I was just checking the app logic. 

Expected behavior: after a "live birth" pregnancy outcome is recorded, the following should happen:

- The infant should appear as a family member within the household 
- The count of the number of household members should increase by one and a boy/girl icon showing an additional child under 5 should appear 
- The infant should appears on the `Child Clients` list
- The infant should appear on the `Birth certification` list

**Comment by joyce-x-chen** [comment]
@rowo helpfully pointed out that it is possible to register Birth certification of infants <28 days through the `PNC Visit` > `Birth certification` form. Is it possible to:

- Check that this version of the `Birth certification` form is consistent with the full list of questions required for CRVS
- Add the infant to appear in the list of `Birth certification` list as a priority (it's ok if they are missing from the `Child clients` list and from the household register for now) 

cc: @ageryck

**Comment by joyce-x-chen** [comment]
Note that there is a bug in that form (`Birth Certification` form within `PNC form`) where you cannot enter a birth certificate number greater than one digit. The error message displayed says: "Birth certificate number must be unique and cannot exceed 15 digits" but appears the moment you enter more than 2 numbers/letters. It appears that the constraints are implemented incorrectly and currently configured to allow:
- Up to 15 numeric digits
- A single letter

**Comment by ageryck** [comment]
@allan-on lets override the limit query about the `<28 days` and immediately list all infants from pregnancy outcome live birth so that they are able to be filled for birth certification details on the birth summary register

**Comment by ageryck** [comment]
@allan-on I can see updated in the current apk kindly confirmed you worked on it ?

**Comment by allan-on** [comment]
Hi @ageryck This is fixed in the most recent APK shared for the TOT
