### ISSUE TITLE
Create Children (12-59 months) who died in the last year indicator

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#201]
Refer to [Reporting](https://docs.google.com/spreadsheets/d/1q9YiWqjLiToTd0--Q8CbwhBwwcNDspbDxVrUfDm8VGU/edit#gid=1627225414) dictionary for reference.

Label: Children (12-59 months) who died in the last year

Calculation: Count of all children >= 12 months and < 60 months who were marked as deceased in the most recent 12 months (i.e. in Remove Child Under 5 form, date_died occurred in the most recent 12 months).

<img width="373" alt="screen shot 2019-03-06 at 12 31 34 pm" src="https://user-images.githubusercontent.com/3488986/53936026-8a019e00-40b9-11e9-9770-f3f5c9583871.png">

Note: In the mockup, only one death indicator is shown, but we are actually doing two death indicators.

@rowo Can you please provide the font size, color codes, spacing instructions, etc. for this indicator? Please un-assign yourself from the issue afterwards.

**Comment by rowo** [comment]
Specs here: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/193#issuecomment-470667482

**Comment by cafootitt** [comment]
lgtm
