### ISSUE TITLE
Place all reporting indicators in the Job Aids -> Dashboard tab

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#202]
<img width="341" alt="screen shot 2019-03-07 at 9 21 28 am" src="https://user-images.githubusercontent.com/3488986/53936388-a8b46480-40ba-11e9-8bb6-57205f6e906d.png">

Job Aids in the bottom navigation menu should be highlighted when you select it.

@rowo ~~In the reporting mockups, the top header only shows dashboards. Do you want the top header section here to collapse on scroll and only show dashboard? Should we add the top left menu button here, like you have in the reporting mockups? Please un-assign yourself when you've provided input.~~
RW edit: top header section collapses and just shows tabbed subsection on scroll (either "Dashboard" or "Guidebooks"). No other items appear in header other than "Job Aids"

**Comment by rowo** [comment]
@cagulas It's been so long, that screen is such blast from the past! Requirements for this section were not defined well when it was created, so I think we can reevaluate how to launch the Dashboard and/or Job Aids sections. Are we still doing the Guidebook content as markdown format?

**Comment by cagulas** [comment]
Guidebooks would be pdfs I think we discussed, so similar to the ANC library page. This would also potentially be the place for the tutorial videos.

**Comment by rowo** [comment]
@cagulas I updated the first comment and unassigned myself.

**Comment by cagulas** [comment]
Great, thanks.

**Comment by allan-allay** [comment]
- [ ] Display Total children U5

- [ ] Display Children (12-59 months) who died in the last year

- [ ] Display Children (0-11 months) who died in the last year

**Comment by cagulas** [comment]
lgtm
