### ISSUE TITLE
DCIS: Birth Registration Schedule

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#2025]
Client reported that children under 5 have the service for Birth Certification re-occurring as a due service even after successfully filling out the detailed and capturing birth certificate details.

Expected functionality is that the service can only re-occur when it has never been filled or no certification details captured.

We are conducting independent QA to confirm the same, however this issue is to request engineering confirmation on how this functionality has been implemented on the DCIS flavor of the CFC app

**Comment by allan-on** [comment]
Hello @ageryck. The implementation is similar to the workflow on all WCARO flavors in that: 
The birth certification task is filled only once and never shows up in subsequent visits once the visits have been processed (after 24 hours to allow for editing of visit details)

**Comment by ageryck** [comment]
Further QA tests were conducted on this to certain the correct processing workflows, we determined that the birth registration task only re-appeared for children that did not have birth certificates.
