### ISSUE TITLE
DCIS: Add eventDate to the system birth notification report

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#2027]
Client requested addition of a variable named `age in months` into this [dashboard](https://crvs-cd.discover.ona.io/superset/dashboard/5/) for the second table (With system birth notification).
The `age in months` variable should be a date difference based on the child's `dob` and `eventDate`

**Comment by muneneg** [comment]
@ageryck I have added the `age in months`  calculated as the difference in months between the `event_date` and `child birthdate`. I also added the `event_date`  for easier reference.

**Comment by ageryck** [comment]
completed
