### ISSUE TITLE
Need to modify name rows to prevent cut-offs

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#203]
![screenshot_20190307-084737](https://user-images.githubusercontent.com/3488986/53936597-60e20d00-40bb-11e9-8b2f-fb23f87e5237.png)

@rowo in a previous issue, you mentioned the below options:
- Reduce width of button column and button text size
- Only show an initial of first or last name of caregiver
- Shorten age to 3 characters when appended to name

Could we also discuss the option of moving age to the same row as gender?

**Comment by rowo** [comment]
@cagulas Seems like no matter if we do any of those we'll run into issues at some character length in this country or the next. The only thing that can handle every scenario is allowing multiple lines for names and letting users self regulate by entering names that work sufficiently for them (see row 5 below). 

![screen shot 2019-03-07 at 1 55 49 pm](https://user-images.githubusercontent.com/1584163/53981536-bda3ee80-40e0-11e9-971d-bead4235ffc6.png)

Originally, I had thought we could truncate name and use age separately (row 1 and 2). Using last name initial would make more sense than family name, but then you get this odd truncation on long names (row 3). Moving age to the next level only saves a few characters and I still like age on the same line for quicker identification (row 4).

Beyond that, the font sizing can get smaller and padding around the avatar tighter.

**Comment by cagulas** [comment]
@rowo Do you think we can pause this now that we are making middle name optional? I think that could potentially do away with most of the cut-offs. What do you think?

**Comment by rowo** [comment]
Sure if West African countries don't have super long names that always start out the same way, I don't think we need to deal with this now.  Just having the first ~25 characters of name/age seems enough for ID purposes within a family.

**Comment by cagulas** [comment]
Great, I'll move this to the icebox column
