### ISSUE TITLE
[Discussion] QR code to read birth certification details

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#204]
We got a request from the client after his field test this week at the project site. Apparently, the birth certificates that are issued in Liberia have QR codes on them, which contain the name of the child and birth certificate number (the issuance date is also embedded in this number, see example below). The client is requesting that we consider adding the QR code reader to the birth certification widget in the app as well as the add child under 5 form.

This does have benefits, namely that the CHA would not need to manually enter the birth certificate number or the child's name if scanning the code within the add child under 5 form.

Sample QR code data:
Registration ID:15-T.S.20190125-52449
Firstname:John
Lastname :Smith
Volume Number:58-I

Changes required:
- Add the QR code button to the add child under 5 form and the birth certificate widget in the home visit
- In the add child under 5 form, scanning the QR code would read and populate the child's first and last name in the form.
- We'd need to add the birth certificate questions - number and issuance date - to the add child under 5 form, but leave them optional. If they scan the QR code, we'd read in the Registration ID and populate the birth certificate number field. If possible, we can parse the ID number and obtain the date (ie 20190125 in sample above). If that's not feasible, we can just record the ID number and remove date, as they can view the date from this ID number.
- In the birth certificate widget in the home visit, we'd have to have the Registration ID populate the birth certificate number field and make the date optional perhaps, as the date is included in the ID number.

What would an approximate LOE for the above changes be? We don't need to include this in the training release if it's not feasible, but a LOE would help as a start.

**Comment by cagulas** [comment]
Sent an example over email.

**Comment by mlberg** [comment]
We had this before for ZEIR I'm pretty sure.

Do we have a bit more information on the birth certificate. I saw the email you sent.  Is that exactly how the QR works?

So this would be used for the birth certificate entry but not as the main ID right?

**Comment by cagulas** [comment]
@mberg That's correct. In ZEIR, it read the OpenSRP ID number and populated the field, so this could similarly read the QR code and populate the birth certificate number; however, the example sent has about 4 fields in total, so we'd need to parse which of these is the ID.  

Correct, this would just be the birth certificate, we would separately still issue a unique OpenSRP ID.

**Comment by cafootitt** [comment]
Closing this. Will re-open if it becomes a requirement.
