### ISSUE TITLE
Need assets to put finished app on Play Store

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#205]
We need to clear the server url for the version posted to the play store, so users outside this project don't have access to the project server data entry endpoint. Once the devices are configured and the server url added initially, they should not need to re-enter the server url with each app update. I remember this is how ZEIR worked, but please confirm we can still do this.

We'll need the following:

- [x] A short description of the app (up to 80 characters)
- [x] Full description of the app (up to 4000 characters)
- [x] Hi-res app icon (512x512 pixels) @rowo
- [x] Feature graphic for the app. More info on the feature graphic [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en) (1024x500 pixels) @rowo
- [x] 3 screenshots of the app @rowo

**Comment by cagulas** [comment]
It looks like the training will be scheduled for the week of April 15th, so the finished app will need to go onto the play store before then.

**Comment by cagulas** [comment]
Adding blocked label as we have a discussion on what graphics - unicef or liberia - we need to use here.

**Comment by cagulas** [comment]
@rowo This is no longer blocked. We'll be posting the app to the play store specific to Liberia, so app name will be CFC Liberia Monitor. Let me know when you will be able to share the graphics needed, as specified above.

**Comment by cagulas** [comment]
**A short description of the app (up to 80 characters)**

App for family enumeration, child health, and ANC and PNC community workflows.


**Full description of the app (up to 4000 characters)**

Liberia CFC Monitor was developed for Liberia’s Ministry of Health, as part of UNICEF’s Child-friendly Communities (CFC) program. The app is used by Community Health Assistants (CHAs) and their supervisors to enumerate all families in their catchment area and provide routine child health, antenatal care (ANC), and postnatal care (PNC) services in the community. 

Liberia CFC Monitor is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers.

**Comment by rowo** [comment]
@cagulas can you point me to the issue with the latest app icon and/or graphics discussion for Liberia CFC Monitor?

**Comment by rowo** [comment]
@cagulas also remind me — what is the relationship of these assets to other assets for the West Africa project? I think we talked about on the OpenSRP call about making a standardized login page, but will these assets also need to have a standard approach either due to client requirement or internal efficiency?

**Comment by cagulas** [comment]
On our weekly call, we discussed that we'd like to head in the direction of having standardized assets for all West Africa projects, but we won't have this soon enough, so we'll need to post the Liberia app to the Play Store as the Liberia-specific app, so we'll use the "Liberia CFC Monitor" as the app name and the app logo (Unicef/Liberia emblem -- or just the Liberia emblem if space is an issue) as the app icon I guess.

**Comment by cagulas** [comment]
I can't find the issue or Slack message where the combined logo was sent. Did you send it directly to Eph or Ronald maybe?

**Comment by rowo** [comment]
@cagulas Found the issue: https://github.com/OpenSRP/opensrp-client-chw/issues/79. Just to confirm, the logos should be side by side then on the feature graphic? 

And sure, I will just the emblem for the app icon since if it's both it'll be too small to see anything.

**Comment by cagulas** [comment]
Yes, I think if that looks alright for the feature graphic, they can be side by side, but if you suggest something else, like one on top of another, that could work as well (with country emblem being the one on top).

**Comment by rowo** [comment]
![liberia-cfc-app-icon](https://user-images.githubusercontent.com/1584163/57272255-f3be0a00-7060-11e9-9641-49b60f648269.png)
![liberia-cfc-playstore-feature-graphic](https://user-images.githubusercontent.com/1584163/57272256-f3be0a00-7060-11e9-8253-9b77e26b3995.png)

**Comment by cagulas** [comment]
@rkodev I'm not seeing the above banner asset in the play store posting. I see 3 screenshots from the app instead. Do you know why this is?

**Comment by rkodev** [comment]
@cagulas The banner asset was added to the play store. But the playstore layout looks to have been changed by Google

**Comment by cagulas** [comment]
@rkodev Ok, did Playstore require 3 screenshots from the app in addition to the banner?

If so, @rowo I might ask you to help refine the screenshots, as they were just taken from someone's device.

**Comment by rkodev** [comment]
@cagulas The 3 screenshots are mandatory for the play store release. They seem to be more prominent in the play store layout too.

**Comment by rowo** [comment]
@cagulas Sure, actually I did okay these images but reading over it closer I'm seeing the profile one is inappropriate (Gang Member name — perhaps a new screenshot can be taken). What else were you thinking should change? It's just dummy info.

**Comment by cagulas** [comment]
@rowo Ok, let me work on it. I was thinking they also didn't look high quality, but let me try taking on android studio emulator, which might be better.

**Comment by cagulas** [comment]
<img width="271" alt="Screen Shot 2019-05-30 at 9 23 23 AM" src="https://user-images.githubusercontent.com/3488986/58612928-ed682a00-82bc-11e9-868a-72b37ea4caa1.png">
<img width="270" alt="Screen Shot 2019-05-30 at 9 24 21 AM" src="https://user-images.githubusercontent.com/3488986/58612930-ee00c080-82bc-11e9-9596-a16ed4b35820.png">
<img width="270" alt="Screen Shot 2019-05-30 at 9 25 25 AM" src="https://user-images.githubusercontent.com/3488986/58612931-ee995700-82bc-11e9-9c42-460f76963033.png">

@rkodev Please use these three screenshots to update the listing on the play store.

**Comment by cagulas** [comment]
Done
