### ISSUE TITLE
Boresha Afya Sync Improvements

### ISSUE THREAD

**Issue by allan-on** [OpenSRP/opensrp-client-chw#2072]
The following are suggestions that can be implemented to improve app performance during sync and reduce lag during sync: 
- Prioritize sync over:
  - Reporting Library indicator computations - Should only run on-demand or with longer schedule durations
  - Child Alert updates
  - Schedule tasks generation (execution)
- Consider removing `synchronized` in the `processClient()` method to allow faster saving of Clients during EC processing (when sync is in progress)

**Comment by owais-vd** [comment]
@allan-on can we wrap [processEvents](https://github.com/opensrp/opensrp-client-chw/blob/master-v1/opensrp-chw/src/main/java/org/smartregister/chw/sync/ChwClientProcessor.java#L31), [resetSchedule](https://github.com/opensrp/opensrp-client-chw/blob/master-v1/opensrp-chw/src/main/java/org/smartregister/chw/task/ChildHomeVisitScheduler.java#L16) and [onVisitEvent](https://github.com/opensrp/opensrp-client-chw/blob/master-v1/opensrp-chw/src/main/java/org/smartregister/chw/application/ChwApplication.java#L357) method body in async operation.

**Comment by owais-vd** [comment]
We can use RxJava to make sequential async operations. cc: @allan-on

**Comment by allan-on** [comment]
Hi @owais-vd Here's a list of implementations for your reference: 

**CHW Application class**
1. https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/src/main/java/org/smartregister/chw/application/ChwApplication.java#L418

2. https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/src/main/java/org/smartregister/chw/sync/ChwClientProcessor.java#L46

**CHW Client processor**
1. https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/src/main/java/org/smartregister/chw/sync/ChwClientProcessor.java#L72

2. https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/src/main/java/org/smartregister/chw/sync/ChwClientProcessor.java#L79

**SchedulesIntentService**
This method is used as a check prior to the execution of the visit schedules in this Service class
- https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/src/main/java/org/smartregister/chw/service/SchedulesIntentService.java#L46
