### ISSUE TITLE
Boresha Afya Fixes: Saving a Family takes more than 5mins

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-chw#2077]
APK - Kituoni (Health Facility)
Android version 7

Steps to reproduce:
	a) Click add family
	b) Fill in the fields
	c) Click Submit

See attached video

https://user-images.githubusercontent.com/5908630/176893365-b777aa23-bf32-4836-b0c5-1623c0ed27ed.mp4

.

**Comment by owais-vd** [comment]
`processClient` method is `synchronized` in `CoreClientProcessor` class.

https://github.com/opensrp/opensrp-client-chw-core/blob/0ad08cde606d7759bb29f6b04852859f6ef28a58/opensrp-chw-core/src/main/java/org/smartregister/chw/core/sync/CoreClientProcessor.java#L125

and initially when we launch the app the `processClient` method is blocked by thread IntentService[SyncClientEventsPerTaskIntentService].

cc: @samkanga

**Comment by owais-vd** [comment]
a suggestion here, can we remove `synchronized` keyword from the `processClient` method so other threads cannot block it.
cc: @ekigamba

**Comment by ekigamba** [comment]
I agree with @hilpitome.

I'd prefer we leave it as-is, unless there's a better alternative and good reason to remove it given that it relates to synchronizing multiple-threads.

@owais-vd Are there other performance improvements that you can suggest or identified causes for slowness?

Follow [this documentation](https://github.com/opensrp/support/issues/192) that will help you investigate further and implement previous fixes:

Here is a checklist

- [ ] Updates to the latest core libraries to fix issues
- [ ] Make sure the event-client tables and other details tables have the base-entity-id index. Some migrations that required recreating this tables did not recreate the indexes.
- [ ] Investigate illegal operations on the app by running the app with StrictMode enabled
- [ ] Check for memory leaks using Leak Canary
- [ ] Check for long-running queries, disable or optimize them
- [ ] Check for long-running operations on the main thread
- [ ] Disable report generation running and make it ad-hoc

Other performance-related discussions for reference and perusal:
- https://github.com/opensrp/support/issues/122
- https://github.com/opensrp/opensrp-client-giz-malawi/issues/254

cc @samkanga

**Comment by faith-mutua** [comment]
@samkanga @owais-vd the issue has been resolved. Saving a family now takes less than a minute
