### ISSUE TITLE
Boresha Afya Fixes: Saving an additional family member take more than 5mins

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-chw#2078]
APK - Kituoni (HF)
Android Version 7

Steps to follow:
	a) Click on a family
	b) Click Add family member
	c) Fill in the details
	d) Click Submit

See video here

https://user-images.githubusercontent.com/5908630/176893808-ca977ec6-4c4a-41ae-9c54-39746cec36da.mp4

**Comment by faith-mutua** [comment]
@samkanga @owais-vd saving an additional family member now takes 3 minutes. I'm not sure whether this is the targeted timeline.
