### ISSUE TITLE
Boresha Afya Fixes: Crash Following FP Initiation

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-chw#2087]
Android version 7

BA CHW APP

When a female is initiated to family planning, the process goes through successfully but end with an App crash.

Steps to Follow:
- Initiate a woman to family planning
- Fill in all the details and hit the save button
- Attempt to select the completed record or navigate the App
- The App crashes

**Comment by madrinekariuki** [comment]
@samkanga 
This has been tested on this shared apk `opensrp-chw-ba-debug-2087.apk`

Tested on:

- physical android 11 device
- emulated android 8 device


steps:
Followed the steps highlighted [here](https://github.com/opensrp/opensrp-client-chw/issues/2087#issue-1303358653)

observations:

- The app is not crashing after initiating a woman to FP
- one is able to navigate through the app after initiating a woman to FP without any crashes.
