### ISSUE TITLE
Update both notes on the Birth Certification widget in home visit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#209]
See rows 88 and 89 on the Child Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1775888911)

Ask to see the birth notification and instruct the caregiver to register the birth at County Health.

Instruct the caregiver to have the birth registered at County Health.

**Comment by cagulas** [comment]
This is probably related and might be quick to fix at the same time: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/145

**Comment by mahmud6390** [comment]
pending PR #230

**Comment by cagulas** [comment]
lgtm
