### ISSUE TITLE
Add 3rd answer choice to obs & illness episode

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#210]
The users want a third option added to the action taken question in Obs & Illness episodes widget: No action taken.

Pls see row 96 in the Child Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1775888911)

**Comment by mahmud6390** [comment]
pending PR #230

**Comment by cagulas** [comment]
lgtm
