### ISSUE TITLE
Set up the reporting infrastructure for generating indicators

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-chw#216]
Refer to  [In-app Reporting Discussion]( https://docs.google.com/document/d/1Ik2fb7NceaYxVLtLl6tQFUiWcQb6V8QIR_MIZT4MLqg/edit#heading=h.bus3azg6nbat) 

- [x] Create a background service to generate indicators
- [x] Standardized data model to store indicators
- [x] Helper classes to retrieve and display indicators in a dashboard

**Comment by cagulas** [comment]
This is done.
