### ISSUE TITLE
Simplification of floating action button

### ISSUE THREAD

**Issue by mlberg** [OpenSRP/opensrp-client-chw#219]
![Screenshot_20190311-152138](https://user-images.githubusercontent.com/42673455/54151796-070e7980-4412-11e9-9d59-9e15fd838a87.png)

I'd like to propose simplifying the number of elements on the top level by doing the following.

For the household level view remove:
* Remove existing family member
* Change Family Head
* Change primary care giver

On the family head page add Change Family Head option
On the Primary care giver page add Change Primary Care giver button

The remove family member option is already on every page

**Comment by rowo** [comment]
I'm fine with removing those items from the household view and moving them to the individual level.

**Comment by mlberg** [comment]
Sorry for this change.  I'm worried about showing options that happen rarely plus this will free up room if we use this for other things in the future.

**Comment by rowo** [comment]
After a closer look:
- If we remove the "remove existing family member" option from the family profile, logically that would remove the first step in "Remove member" where you select the individual you are removing. However, that would also remove the "Removing entire family" option. So options I see are: (1) we keep that entire select individual or family step even when accessing "remove" from the individual profile (with the individual default selected as a radio button), or (2) Add a new "remove/delete family" into the family choice list (negating the goal of your change @mlberg )
- Change family head doesn't have any edits, though the blank form that appears when there are no existing other options is confusing. 
- Change primary caregiver doesn't have any edits, though there's a bug (or just incomplete functionality) where if you add a new person and say they are the primary caregiver, the designation is not saved (however that person's phone number and education are thankfully saved).

**Comment by cagulas** [comment]
> (1) we keep that entire select individual or family step even when accessing "remove" from the individual profile (with the individual default selected as a radio button)

I see the above as slightly confusing. If the user is already on the individual page, why are we making them select again? We already show the person's name and age in the close form to help make sure they selected the right person, and for good measure, we show a final confirmation after the form to confirm you want to close the person's record. This seems a bit unnecessary to me. My opinion is to keep it as is on the family profile page. 

I also find it slightly confusing to have to go to the existing family head / caregiver profile to change their status away from that person. Wouldn't it be less confusing to add a "Make family head" or "Make primary caregiver" button on other profile pages that are eligible?

**Comment by rowo** [comment]
@cagulas Speaking for @mlberg I believe this is about reducing the overall complexity by moving actions that will happen very rarely or never. I agree the individual interactions you mentioned would be slightly confusing, but for the weekly interactions the user would see fewer options. So that I think was Matt's goal.

Some other approaches to respond to the "too many items in the floating action button (FAB)" problem that Matt is addressing is to: (A) Nest the not often used buttons in a "Other..." type of button in the FAB that opens up another list, and (B) Add a top-right three-dots pull down to put the rare actions and keeping the FAB for common ones, and (C) Move all FAB items to the top-right three-dots pull down and remove the FAB. Originally, I thought the FAB would make it easier to learn by CHWs, but it is probably exacerbating the perception by making very rare actions seem  accessible.

**Comment by cagulas** [comment]
I think I prefer the action of moving more rare actions into an other option in the FAB. I could be wrong, but that also seems like the least amount of work for us to change as well.

I think we're also assuming what the rare actions would be. Changing the family details is probably also rare, as that's just changing the family name or address. Adding a new family member probably wouldn't be too common either actually.

**Comment by cagulas** [comment]
@rowo @mberg I'd like to finalize this discussion and create an implementation issue today, as our team has pretty much wrapped up everything else apart from reporting.

How about the proposal that we move all choices apart from Call and Add family member to an Other button, so we have 3 options total in the initial FAB selection and if they open Other, they see 4 other options?

Roger, new mockups showing the Other (with icon) and how tapping on Other opens new options would be helpful here.

**Comment by rowo** [comment]
@cagulas in the Material guidelines, they say do not use an overflow menu in the FAB speed dial. (They also say don't use it for destructive or secondary actions too so we're breaking some rules already attempting to simplify for CHWs.). Consequently, the FAB speed dial overflow button is probably not part of the library though @keymane can shed light on this. 

The least work is just moving forms to individual profiles. The one confusing part is the "remove family" option there, which is probably too confusing, so it would have to be added to the FAB menu on the family profile.

@mberg It might feel bad like wasted work, but how would you feel about it if all of the floating action button items were moved into a top right dropdown instead? That would make those actions much less prominent and the buttons would seem more approachable as a list.

**Comment by rowo** [comment]
@mlberg 
<img src="https://user-images.githubusercontent.com/1584163/54633246-27fc4d80-4a56-11e9-9f18-026363b7be6c.png" width="350">

<img src="https://user-images.githubusercontent.com/1584163/54633250-29c61100-4a56-11e9-8606-d5794230e927.png" width="350">

**Comment by mlberg** [comment]
Sorry for the late reply on this.  I'd like to try and avoid nesting the FAB if possible.  

My vote would be to go with the combo approach you originally recommended.  

So in the FAB menu I would have:

- Call
-  Add new family member

I could see adding other action items here later like "message" or "refer"

I would put in the hamburger menu
- Family details
- Remove family member
- Change family head
- Change primary care giver

For the person pages I think we can remove the FAB and replace it with a hamburger menu.  The only exception would be potentially the care give or head of household who we would want to call.  Having the call on the child page doesn't make a lot of sense.

This would allow us to keep the selection workfows we currently have with minimum destruction (and I think they are quite nice)

I think keeping the FAB for key actions is important as we don't have visible buttons in the interface.  

Of note: we had one of the Mauritanian nurse midwives way she knew what a hamburger menu was cause she has it on her phone.  So it sort of reinforced to me keeping to android design principals where possible is important.

**Comment by mlberg** [comment]
On the FAB can we also make the buttons and text a little bit bigger?

With the hamburger menu on the right this aligns with how we are doing subtaks with the clinical app (ZEIR) so I think this keeps things consistent.

**Comment by rowo** [comment]
@mberg A few responses: 
The official name it seems is "dropdown menu", not hamburger menu. Hamburger menu is usually on the top left and slides full screen height.

I am okay with this, though I do think it makes what's complicated even more complicated at the CHW level. I'm not convinced it's worth it, but I am okay with it. 

I wouldn't count only the things that are button shaped as "visible buttons". On what is tappable, you would have the dropdown menu, three tabs, each family member, and each due task. That's a lot of stuff to tap. Going to family members and due tasks I would say are the key actions, not calling and adding (which will happen rarely after enumeration).

The call for any member of the family goes to a dialog: https://marvelapp.com/9j1277a/screen/49183728. So it does make sense on the child profile. The user won't always get to the child profile via the family register.

**Comment by cagulas** [comment]
Ok, so just to summarize (and I'll create a new issue for implementation and close this one once we finalize): We are keeping the FAB for family and family members, but also creating a top right dropdown menu:

Family FAB:
- Call
- Add new family member

Family dropdown:
- Family details
- Remove existing family member
- Change family head
- Change primary caregiver

Family member FAB:
- Call

Family member dropdown:
- Registration info
- Remove this person

**Comment by rowo** [comment]
If [no phone number is provided](https://github.com/OpenSRP/opensrp-client-chw/issues/207#issuecomment-470659047), then the FAB in the family member should probably be hidden, but on the family profile, we can still make it disabled on the speed dial menu.

**Comment by rowo** [comment]
@mberg @cagulas here are updated screens for FAB simplification

Family fab, phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799456-b843b980-4c33-11e9-9db2-6b47c006b8f7.png" width="330">

Family fab, no phone
<img src="https://user-images.githubusercontent.com/1584163/54799468-c72a6c00-4c33-11e9-985f-dbb33f19748a.png" width="330">

Family dropdown
<img src="https://user-images.githubusercontent.com/1584163/54799479-d1e50100-4c33-11e9-97db-04fb8ba54e6c.png" width="330">

Individual member fab, phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799486-dc06ff80-4c33-11e9-9c3c-f86ba6fbad04.png" width="330">

Individual member fab, no phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799491-e6c19480-4c33-11e9-8478-e7bd5ce14a51.png" width="330">

Individual member dropdown
<img src="https://user-images.githubusercontent.com/1584163/54799505-f80aa100-4c33-11e9-9bb2-c33b7c7c4b89.png" width="330">

**Comment by cagulas** [comment]
Closing this and created implementation issue here: https://github.com/OpenSRP/opensrp-client-chw/issues/248
