### ISSUE TITLE
Fix spelling mistake in "provided" and grey out the icon as well

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#236]
- [x] Spelling mistake
- [ ] If possible to do quickly, grey out the phone icon as well (if you need a new icon from Roger, please ignore then)
- [x] If possible, let's also make sure the same grey out action happens on individual member profile pages as well (see second screenshot below) for all family members, including children.

![Screenshot_20190321-085224](https://user-images.githubusercontent.com/3488986/54737163-b93b0380-4bbf-11e9-941a-9f672f142421.png)
![Screenshot_20190321-094227](https://user-images.githubusercontent.com/3488986/54737162-b809d680-4bbf-11e9-81df-aef985fc86f9.png)

**Comment by rkodev** [comment]
@cagulas I'll skip the second issue for now since it might require a new icon.

**Comment by cagulas** [comment]
Ok no worries, let's skip it

**Comment by cagulas** [comment]
lgtm
