### ISSUE TITLE
Simplify floating action button (FAB) and create top right dropdown menu

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#248]
**Family FAB:**
Call *(if no number provided, show disabled state that's already implemented)*
Add new family member

**Family dropdown:**
Family details
Remove existing family member
Change family head
Change primary caregiver

**Family member FAB:**
Call *(if no number provided, hide the FAB completely)*
**Note how the icon changes to just the call button for the family member FAB**

**Family member dropdown:**
Registration info
Remove this person

Screenshots of all the options:

Family fab, phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799456-b843b980-4c33-11e9-9db2-6b47c006b8f7.png" width="330">

Family fab, no phone
<img src="https://user-images.githubusercontent.com/1584163/54799468-c72a6c00-4c33-11e9-985f-dbb33f19748a.png" width="330">

Family dropdown
<img src="https://user-images.githubusercontent.com/1584163/54799479-d1e50100-4c33-11e9-97db-04fb8ba54e6c.png" width="330">

Individual member fab, phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799486-dc06ff80-4c33-11e9-9c3c-f86ba6fbad04.png" width="330">

Individual member fab, no phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799491-e6c19480-4c33-11e9-8478-e7bd5ce14a51.png" width="330">

Individual member dropdown
<img src="https://user-images.githubusercontent.com/1584163/54799505-f80aa100-4c33-11e9-9bb2-c33b7c7c4b89.png" width="330">

@rowo Can you pls provide the icons for call FAB button and also the greyed out call icon? Also, if there are any special formatting or font specifications for the new top right dropdown, please add them here. Pls un-assign yourself after.

**Comment by mlberg** [comment]
This looks good to me.  Thanks everyone

**Comment by rowo** [comment]
@cagulas icons I believe are already there. I'm okay with the ones in the discussion issue Matt created.

**Comment by cagulas** [comment]
@rowo I'm referring to both of the below icons. Can you kindly point me to where these are uploaded, as I can't find them in the previous issue.

<img width="82" alt="Screen Shot 2019-03-25 at 8 43 43 AM" src="https://user-images.githubusercontent.com/3488986/54897613-39bc7580-4eda-11e9-9d6e-b14db21802f9.png">
<img width="63" alt="Screen Shot 2019-03-25 at 8 43 50 AM" src="https://user-images.githubusercontent.com/3488986/54897615-3a550c00-4eda-11e9-81ce-e0c2062bbb6b.png">

**Comment by rowo** [comment]
@cagulas https://github.com/OpenSRP/opensrp-client-chw/issues/219#issue-419645634 the phone icon in this post is okay with me.

**Comment by cagulas** [comment]
Cool, but I don't see a black background one. Is that ok? Also, I don't see the greyed out one.

**Comment by rowo** [comment]
Should be

**Comment by cagulas** [comment]
Perfectly implemented, awesome!
