### ISSUE TITLE
Fix exclusive breastfeeding in Medical history page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#249]
Not sure if this was specified in the original issue, but I'm seeing that we need to update how exclusive breastfeeding is displayed in the medical history page, see below screenshot.

In the add child under 5 form, the variable {early_bf_1hr} maps to "Early initiation of breastfeeding: Yes/No" in the medical history page (seen below). What's happening right now is that the exclusive breastfeeding 0 months question is being mapped to this instead.

**What it should be:**
Early initiation of breastfeeding (1 hr)? Yes/No --> Early initiation of breastfeeding: Yes/No
Exclusive breastfeeding 0 months --> Exclusive breastfeeding 0 months: Yes/No
And so on.

Let's also please capitalize the "Yes" and "No"s on the medical history page

![Screenshot_20190322-100928](https://user-images.githubusercontent.com/3488986/54806378-e0123c00-4c8a-11e9-983c-a66ab1fb9889.png)

**Comment by mahmud6390** [comment]
Right now it's showing from breast feeding home visit data.Need to use "Early initiation of breastfeeding" from child form.

**Comment by mahmud6390** [comment]
![medical](https://user-images.githubusercontent.com/2793306/55461249-d20ed480-5615-11e9-9381-88a8e02ee5e0.png)

**Comment by cagulas** [comment]
Looks great!

**Comment by cagulas** [comment]
This is fixed.
