### ISSUE TITLE
Customize the side panel with the list of registers for the CHW app for BA

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#257]
Please reference below or issue: [BA issue #2](https://github.com/OpenSRP/opensrp-jhpiego-ba/issues/2)

<img width="318" alt="screen shot 2019-01-14 at 11 55 04" src="https://user-images.githubusercontent.com/20777928/51103317-485c2180-17f3-11e9-855b-831d7133e366.png"><img width="324" alt="screen shot 2019-01-14 at 11 55 13" src="https://user-images.githubusercontent.com/20777928/51103321-4d20d580-17f3-11e9-9aed-a4deafd25e9b.png">

- [x] Update the top logo with "USAID Boresha Afya" instead of "Boresha Afya"
- [ ] Update the registers to include the following registers in the following order: All Families, ANC,  PNC, Child Clients, Family Planning, Malaria
- [x] Update the icons associated with each register. You should have access to this file. Please mention me and let me know if yo do not have access

**Comment by msschroeder** [comment]
@ladleo @JafariUCC I have added you both to the issue and you can decide who will work on which issue. Please unassign one of you once you decide. Thanks!

**Comment by ladleo** [comment]
@msschroeder the icon for **FP** is missing.

**Comment by msschroeder** [comment]
@ladleo Let me check with the designer. I also do not see it.

**Comment by msschroeder** [comment]
@ladleo @JafariUCC I believe you should now have access. Please confirm if you still do not have access

**Comment by msschroeder** [comment]
@rkodev @manutarus This has all the values, but the Malaria is in all capitals. Ideally, this would be "Malaria" not "MALARIA". It doesn't really fit with the rest using capital letter as the first value and lower case for all other values

**Comment by rkodev** [comment]
@ladleo Please check this

**Comment by paulinembabu** [comment]
![Screenshot_1562662646](https://user-images.githubusercontent.com/23362825/60874505-d19f5e80-a240-11e9-86a0-63d026772382.png)

This has been Resolved.

**Comment by msschroeder** [comment]
@paulinembabu This should be Family Planning not FP as is noted in the issue

**Comment by msschroeder** [comment]
lgtm
