### ISSUE TITLE
Customize the Add Family - Family head details for BA

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#259]
Please see below or reference [BA issue #4](https://github.com/OpenSRP/opensrp-jhpiego-ba/issues/4)

After a CHW has selected "Add Family", they will enter "Family details"  and "Family head" information.

<img width="360" alt="screen shot 2019-01-20 at 13 32 50" src="https://user-images.githubusercontent.com/20777928/51438043-f49c7d00-1cb7-11e9-9b72-05eb961cf2fc.png">

- [x] Follow the content in the [data dictionary](https://docs.google.com/spreadsheets/d/1WioGjOYVcJ87NfddArsTrimhWGDO7S1s2nj_qD0s8Ho/edit?usp=sharing), "Census register - Household Registration" tab. The name of this form is "Add Family" as shown in the screenshot above.
- [x] Please make sure to also update the page when a user views/ updates the head of household's information

**Comment by rkodev** [comment]
@msschroeder while displaying the nearest location, which method should we use list the locations?
    1. The display 5 or 10 clinics that are nearest to the location of the device?
or 2. Display only clinics accessible by the user

**Comment by msschroeder** [comment]
@rkodev I would recommend for now that we auto assign the health facility associated with the CHW as the nearest health facility. I will update the data dictionary

**Comment by msschroeder** [comment]
Closing the issue
