### ISSUE TITLE
Enable translation to Swahili

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#263]
- [x] Enable support for Swahili in BA

**Comment by rkodev** [comment]
@msschroeder translation for the strings will need to set up a transifex for Swahili as @craigappl did for French.

**Comment by msschroeder** [comment]
@rkodev Like you need me to provide the translations or set up how the translations can be done on Transifex?

**Comment by cagulas** [comment]
@craigappl added for Swahili already. Megan, when you're back later this week, I can hopefully remember enough to show you how to do this

**Comment by cafootitt** [comment]
this is done
