### ISSUE TITLE
Add a Refer to Facility button to list of pop-up buttons to BA

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#269]
<img width="354" alt="screen shot 2019-01-21 at 09 59 22" src="https://user-images.githubusercontent.com/20777928/51457673-4e0db600-1d63-11e9-8a48-fac80b1ca052.png">

- [x] From a family member's profile page, there should be a pop-up. Add a fourth button, which will allow the user to refer the current client (from the profile page) to a facility. This should be called "Refer to facility" as shown in the screenshot

**Comment by msschroeder** [comment]
This issue is blocked until we determine if this is where the Refer to a facility will go.

**Comment by rkodev** [comment]
@msschroeder @mberg @keymane  The design for this fab menu was simplified. Please look at this issue https://github.com/OpenSRP/opensrp-client-chw/issues/248

**Comment by msschroeder** [comment]
@rkodev The FAB was simplified, but because of how we are implementing the FAB, referring a person would be a service that would be done frequently more so than updating a record. So I would think we would want in the FAB. Also, it was blocked. So I assumed we would have to discuss as well.

**Comment by cagulas** [comment]
I think it should go in the FAB.

@rowo @mberg Any strong objections. This would only make 2 FAB options total in the individual client  profile page.

**Comment by rowo** [comment]
No objections.

**Comment by rkodev** [comment]
@msschroeder @cagulas @rowo I'm I free to start working on this issue?

**Comment by msschroeder** [comment]
@rkodev Yes, there is consensus on where this should go. Please feel free to start this issue.

**Comment by rowo** [comment]
Those icons need updating btw

**Comment by rkodev** [comment]
@rowo cool, you can update me when the referral icons are ready

**Comment by rowo** [comment]
@rkodev The icons share in the icons folder: https://drive.google.com/drive/u/0/folders/1XMVd5PJEZEanMs57tBgEWbhVJbRBNYG3

Files start with... "floating-....png" 

![floating-call-icononly_xxhdpi](https://user-images.githubusercontent.com/1584163/56028681-569dd900-5d21-11e9-8877-43ce8f768eef.png)

![floating-registrationInfo-icononly_xxhdpi](https://user-images.githubusercontent.com/1584163/56028726-6ae1d600-5d21-11e9-950d-1765ee9fe04e.png)

![floating-removeMember-icononly_xxhdpi](https://user-images.githubusercontent.com/1584163/56028747-76cd9800-5d21-11e9-940d-7beb44c48df4.png)


![floating-refer-icononly](https://user-images.githubusercontent.com/1584163/56028735-71704d80-5d21-11e9-8928-ec8ee679f1bc.png)

**Comment by msschroeder** [comment]
Closing issue.
