### ISSUE TITLE
Change child profile to adult profile (leaving medical history) when child turns 5yo

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#297]
When a child turns 5 yo, they are automatically removed from the child register, but they also remain a family member listed in the family members page. We need to update the 5 yo's profile page, however, to an adult profile. We will leave the medical history, as determined in https://github.com/OpenSRP/opensrp-client-chw/issues/250 issue.

![image](https://user-images.githubusercontent.com/3488986/56014695-00b83980-5cff-11e9-9b15-047d632a2144.png)

**Comment by cagulas** [comment]
@mahmud6390 When you're back from Geneva, you can work on this issue.

**Comment by mahmud6390** [comment]
![Screenshot_20190522-123434](https://user-images.githubusercontent.com/2793306/58157710-bf6e5e80-7c9a-11e9-89f3-8eb879d6ddb6.jpg)
![Screenshot_20200522-125521](https://user-images.githubusercontent.com/2793306/58157745-c9905d00-7c9a-11e9-91c4-291a53a6bfe1.jpg)

**Comment by mahmud6390** [comment]
> QA results
> 
>     * [x]  Changing child avatar to person avatar was missed
> 
> 
> All else looks good

pending PR https://github.com/OpenSRP/opensrp-client-chw/pull/390

**Comment by cafootitt** [comment]
lgtm
