### ISSUE TITLE
APK Release Issues v0.1.2 (April 26th 2019) - All Families Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#313]
**Register**
- [x] On the All Families Register, does the Due only button work? Because there is a family with out any services due in the list (i.e. Komba Family) - A child has been registered, It does not appear to have a head of household attached to the family. Could that be why?
![Screenshot_20190429-102521](https://user-images.githubusercontent.com/20777928/56881493-3f712200-6a69-11e9-9e1e-bd6996ae40af.png)

**Comment by cagulas** [comment]
@msschroeder 

>> On the All Families Register, does the Due only button work? Because there is a family with out any services due in the list (i.e. Komba Family)

Is this because no child has been registered yet?

>> Can you clarify how the search button works? Do you search by just name or ID or location? And which ID does it search by? As of right now it appears to search by location, family name or ID?

Check out https://github.com/OpenSRP/opensrp-client-chw/issues/12 and https://github.com/OpenSRP/opensrp-client-chw/issues/11 for how it should work. 

>> Add a Family - Family Details - Choice options when closing the page are Oui and Non (French). These should definitely not be there, and needs to be changed before our official release.

Can you provide a screenshot of this? Is this on the close form dialog? 

>>  Add a Family - Family head - Is there a reason we have a save at the top and a back and submit when you finish here?

This sounds like native android form library that we use, so I don't think we want to change this.

>> Add a child U5 - Edit Registration - Health Insurance, Health insurance number, and physical disabilities, birth registration and number, growth booklet and nutrition values disappear.

Do you mean they originally appear and then disappear or just fail to be pre-loaded into the form entirely?

**Comment by msschroeder** [comment]
@cagulas All have been created as new issues separately and questions answered in those issues

**Comment by cagulas** [comment]
Ah, ok I thought you meant there was no due button appearing, but you mean the due only *filter*.
Sounds like that might be an issue, as the due only filter should only show due/overdue families.

**Comment by msschroeder** [comment]
@cagulas I did check. I was also wondering if it might be because this family might have been created a while ago? It wasn't clear, but I wanted to flag just in case

**Comment by cagulas** [comment]
Cool, yea maybe. I definitely encourage the team to clear the data occasionally for this reason. You can ask them to clear the data in the new release if you want.

**Comment by rkodev** [comment]
@msschroeder this issue should be resolved in the current build

**Comment by msschroeder** [comment]
@rkodev @manutarus I would be happy to close the issue, but I would prefer to QA the issue before closing completely with a APK as we had discussed. Would it be possible to generate an APK or can we include these fixes in the APK with ANC that will be available this week?

**Comment by rkodev** [comment]
@msschroeder this should have been included in the last release

**Comment by msschroeder** [comment]
lgtm
