### ISSUE TITLE
QA bug - 24th April

### ISSUE THREAD

**Issue by rkodev** [OpenSRP/opensrp-client-chw#317]
- [x] If you add a child under 5 years old to a family. That child won't appear in the family page but can be found in the "enfants clients" list.

Find below translations gaps. These are not critical.

- [x] [Add a family] "DOB unknown": unknown is English

- [x] [Add a family] "Back" is English

- [ ] [Add a family/member]Age: "5y" should be "5 ans" in French

- [x] [Add a child member] Difficulties physiques: yes/no should be "oui/non"

- [ ] [Family information] The "a" in "Male" is not correctly displayed.

- [x] [Family information] Title "…. Family" should be "… Famille" in French

- [ ] [Record visit] "Deworming 1st dose", "Exclusive breast feeeding", "Action taken"are English

- [x] Family Register - “Gulas Family” needs to be reordered and translated to “Famille Gulas”

**Comment by cagulas** [comment]
Closing this, since the bug was fixed. We'll do another round of French translation improvements when we have the first French deployment country.
