### ISSUE TITLE
APK Release Issues v0.1.2 (April 26th 2019) - All Families member added

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#320]
**Family Member**
- [x] Add other family member - Create member - If a female, the question about "Has the woman delivered in the last 1 year?" should be required.
- [ ] Add other family member - Edit Registration - When you open the client's information to update/edit the questions: woman delivered in last 1 year, type of disability, primary caregiver, occupation and leadership roles don't preload. Please also check the associated questions - if there is an other for them (i.e. leadership roles, type of disability, other type of insurance)

**Comment by msschroeder** [comment]
QA June 6 Build
- [ ] **Still is not working:** Add other family member - Create member - If a female, the question about "Has the woman delivered in the last 1 year?" should be required.

**Comment by paulinembabu** [comment]
![Screenshot_1562665480](https://user-images.githubusercontent.com/23362825/60878265-17135a00-a248-11e9-9df1-4e20017f6c89.png)
![Screenshot_1562665605](https://user-images.githubusercontent.com/23362825/60878277-1aa6e100-a248-11e9-8a99-b49d52f38339.png)
![Screenshot_1562665614](https://user-images.githubusercontent.com/23362825/60878287-1d093b00-a248-11e9-989c-194cb3a0b94f.png)


All the above issues have been resolved.

**Comment by paulinembabu** [comment]
![Screenshot_1562674907](https://user-images.githubusercontent.com/23362825/60887584-6e6ff500-a25d-11e9-86ea-8df58de108ec.png)

Resolved.

**Comment by msschroeder** [comment]
lgtm
