### ISSUE TITLE
APK Release Issues v0.1.2 (April 26th 2019) - Child Visit Immunization order

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#325]
**Child Visit**
The service schedule does not appear to be completely working for the BA context

- [ ] If I add a child at 4 years and I am collecting data on their immunizations. The Immunization (18m) appears like it has to be done. But, it requires me to fill all previous immunizations first. Once I fill in, the 10w disappears and the 14w appears along with 9m and 15m instead of 9m and 18m

![Screenshot_20190429-130147](https://user-images.githubusercontent.com/20777928/56889991-d4334a00-6a80-11e9-8dad-4eed7fccf126.png)
![Screenshot_20190429-130157](https://user-images.githubusercontent.com/20777928/56889997-dac1c180-6a80-11e9-8c91-e0af49d32345.png)

**Comment by cagulas** [comment]
Megan - this explains the workflow for recording immunization history:
https://github.com/OpenSRP/opensrp-client-chw/issues/142

Carolyn Gulas

Health Solutions Lead


<http://bit.ly/2aeOueY>

<http://bit.ly/2ckhfuf> <http://bit.ly/2csSdWW> <http://bit.ly/2bYdtWl>

**Comment by msschroeder** [comment]
This is already addressed
