### ISSUE TITLE
APK Release Issues v0.1.2 (April 26th 2019) - Child Immunizations 10w not included

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#326]
- [x] You cannot record immunizations for (10w) are included - OPV 2, Penta 2, PCV 2, Rota 2. This may be related to issue #324

**Comment by msschroeder** [comment]
@rkodev @manutarus I need an updated APK for BA to test this feature before I can sign off

**Comment by paulinembabu** [comment]
![Screenshot_1562656904](https://user-images.githubusercontent.com/23362825/60867393-626f3d80-a233-11e9-8064-d3dee99ec321.png)


10W vaccines Displayed.

**Comment by msschroeder** [comment]
@paulinembabu I would want to test in the final app before giving sign off for this as there was a specific scenario where this occurred. I can QA in our next release. You can move this to the QA.

**Comment by msschroeder** [comment]
@paulinembabu I cannot access the 10w from a newborn (registered at 0d or from one register much older 3y)

**Comment by msschroeder** [comment]
lgtm
