### ISSUE TITLE
APK Release Issues v0.1.2 (April 26th 2019) - Child Immunization 14w

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#327]
- [x] No all the immunizations for (14w) are included. It should also include OPV 3, Penta 3, and PCV 3 too.

**Comment by msschroeder** [comment]
@rkodev @manutarus This is not addressed on my current release. Possible a new APK has this update?

**Comment by paulinembabu** [comment]
![Screenshot_1562657153](https://user-images.githubusercontent.com/23362825/60867749-3acca500-a234-11e9-98fb-297a474da960.png)


Resolved

**Comment by msschroeder** [comment]
lgtm
