### ISSUE TITLE
APK Release Issues v0.1.2 (April 26th 2019) - Add Child Immunization 18m

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#330]
- [ ] Immunizations (18m) is not included child visit currently. The form needs to be updated to reflect the immunization MR 2 at 18m.

**Comment by msschroeder** [comment]
@rkodev @manutarus I need the updated APK for BA to test

**Comment by paulinembabu** [comment]
* The issue above has not been resolved. 
* In addition to this, there is an issue on the Immunizations (15m) and show the screenshot below. 

![Screenshot_1562661667](https://user-images.githubusercontent.com/23362825/60873368-f1ce1e00-a23e-11e9-8cea-b65d5e90751b.png)

**Comment by msschroeder** [comment]
Closing the issue and moving to issue #588
