### ISSUE TITLE
Vaccines grouped incorrectly

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#333]
![Screenshot_20190429-140007](https://user-images.githubusercontent.com/3488986/56942061-1f9d3500-6b21-11e9-9315-be841fdf0f74.png)

Rota 2 is a 10w vaccine, while OPV 3, Penta 3, and PCV 3 are 14w vaccines, so Rota 2 should not be shown together with the other three. I have not seen this before, so I'm not sure how this is happening or whether it's always been like this. 

Expected behavior:

For vaccines that are not given as part of a group, they should show up individually in the next home visit. For e.g. at 10w, you have OPV 2, Rota 2, Penta 2, and PCV 2 vaccines dues. Let's say during the visit, OPV 2 and Rota 2 were given, but Penta 2 and PCV 2 were not given. In the next home visit, it should show two separate rows for PCV 2 and Rota 2 vaccines.

**Comment by mahmud6390** [comment]
In previous implementation there has an option after 24 hours home visit done view "<Gray color>"record visit" button" it's showing like this if any previous group not given vaccine from showing in a row and present all due group in top row.
I think in new implementation(from refactor build) this issue will not present. Now we are displaying the vaccines as group wise if given or not given.

**Comment by cagulas** [comment]
@mahmud6390 Ok, I thought the version I tested this on was the version with the refactor in it. I will test again with the latest version you shared.

**Comment by cafootitt** [comment]
not seeing this anymore.
