### ISSUE TITLE
Exclusive breastfeeding service is missing

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#334]
In the latest release (V0.1.3) built on 29 Apr, the exclusive breastfeeding service seems to be missing from the home visit if you register an 8w old child.

To replicate, register a new U5 child (I put the child's DOB at Feb 28, 2019, so about 8w old). In the home visit, exclusive breastfeeding service - 1 months should appear, but it doesn't. Let's check the schedules are correct now after the refactor.

**Comment by mahmud6390** [comment]
![device-2019-05-06-170236](https://user-images.githubusercontent.com/2793306/57221384-dbc69600-7020-11e9-9c08-53333a3b9cfd.png)

**Comment by cagulas** [comment]
@mahmud6390 Still not appearing for me. Using user chathree, I registered a new child (Pam Berg, DOB: March 28, 2019), but in her first home visit, exclusive bf task is not appearing

**Comment by cafootitt** [comment]
lgtm
