### ISSUE TITLE
Status related bugs

### ISSUE THREAD

**Issue by mlberg** [OpenSRP/opensrp-client-chw#346]
I noticed the following testing the WCaro 0.13 release.

<img width="484" alt="Screen Shot 2019-05-01 at 10 28 19 AM" src="https://user-images.githubusercontent.com/42673455/57022075-00270a80-6bfc-11e9-9b60-170ae35f282f.png">

This page still shows BCG due after you do the vaccination.  It seemed to update itself though so it may be something that fixes upon sync.  The status change isn't immediate though it seems.

<img width="503" alt="Screen Shot 2019-05-01 at 10 17 25 AM" src="https://user-images.githubusercontent.com/42673455/57022325-ce627380-6bfc-11e9-922d-966fdd78b68f.png">

It shows now services are due despite seeing red dots on the client rows and on the home visit.

<img width="498" alt="Screen Shot 2019-05-01 at 10 17 58 AM" src="https://user-images.githubusercontent.com/42673455/57022346-dde1bc80-6bfc-11e9-971e-2fc2d6554b7b.png">
<img width="499" alt="Screen Shot 2019-05-01 at 10 18 13 AM" src="https://user-images.githubusercontent.com/42673455/57022362-e639f780-6bfc-11e9-99d5-08416c27c0c4.png">

**Comment by cagulas** [comment]
Seems to be fixed, but I'll keep an eye out for re-occurrence.
