### ISSUE TITLE
Add feature for child being removed from child register list at 5 years of age

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#36]
When the child reaches 5 years of age, they no longer need to be shown in the child U5 register list. This should be done automatically. We need to add a feature whereby when the child reaches 5 years old, their record is removed from the child register list. The child should still appear as a family member in the family's record in the family register list, though.

Also, the age of the child changes from displaying in this format (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/18) to only displaying the number, i.e "5" for 5 years of age instead of the previous format which was 4y 11m.

**Comment by cagulas** [comment]
@rowo It would be good to show something like a toaster message here, so the health worker is informed when this happens. What do you think?

**Comment by rowo** [comment]
We discussions this a bit on Slack. My perspective is there isn't much value in this information for the CHW. At that age, all schedules end and the 5+ client won't be relevant to the goals of the CFC project. In the current workflow, I didn't hear about any hoopla around this event — for example, the CHW doesn't go crossing the name off the U5 register or have "fully immunized"-like milestone.

**Comment by cagulas** [comment]
@raihan-mpower How can I QA this on the app? Should I register a child who's 4 years and 51 weeks and 6 days old and then see if they're removed from the reigster the next day?

**Comment by mahmud6390** [comment]
@cagulas  sorry to moved this issue from to do to "Ready for QA". It has some dependency need to work.

**Comment by cagulas** [comment]
@mahmud6390 no worries, thanks for letting me know.

**Comment by cagulas** [comment]
@mahmud6390 Can you list out the blockers for this issue?

**Comment by mahmud6390** [comment]
pending PR #229

**Comment by cagulas** [comment]
Lgtm
