### ISSUE TITLE
Create logos for Guinea, Togo, Chad, and DRC implementations

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#391]
Following the guidelines (https://github.com/OpenSRP/opensrp-client-chw/issues/349), we need to create the combined UNICEF/country emblem logo for the next WCARO countries: Guinea, Togo, Chad, and DRC.

Find the logos in this document*: https://docs.google.com/document/d/1ZlY6H1jF02HhbzNom6moYOl5Sb8kWCVBjdfo131JkUk/edit. I've added the wikipedia link, to be able to grab the image, underneath each image in the document.

Let me know if you need any additional info.

*Chad is missing. I've requested it from the client.

**Comment by cafootitt** [comment]
Can you provide this by the end of this week? I want to start a dev on the Togo adaptation starting next week.

**Comment by rowo** [comment]
@cafootitt Please review these

![logo-congo](https://user-images.githubusercontent.com/1584163/59437788-342b4900-8dc0-11e9-9d64-b03b7b4c46f5.png)
![logo-togo](https://user-images.githubusercontent.com/1584163/59437789-342b4900-8dc0-11e9-84d3-cfe8dfa8371e.png)
![logo-guinee](https://user-images.githubusercontent.com/1584163/59437791-34c3df80-8dc0-11e9-93ea-3a6a5abb0bb1.png)


Note: there is extra text on the google doc emblems vs. the wiki files.

**Comment by cafootitt** [comment]
@rowo I don't anticipate the extra text being an issue. Thanks for these.

**Comment by cafootitt** [comment]
I'll close this and create a new issue for Chad when we get it from the client.

**Comment by rowo** [comment]
![logo-chad](https://user-images.githubusercontent.com/1584163/59462571-02cb7100-8df2-11e9-8803-ace5a645cd38.png)

@cafootitt
