### ISSUE TITLE
Set up all the necessary servers for 4 new countries

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#393]
We're going to start work on the adaptation of the Liberia app for Togo, Guinea, Chad, and DRC next.

**Comment by cafootitt** [comment]
@manutarus Can you add here the plan of action for the servers that you mentioned yesterday on the call? Just so we document that decision, please.
Thanks.

**Comment by manutarus** [comment]
For this will have one staging environment that would be used primarily for development and QA, then setup preview servers per country that would be used for client releases so that each country would have a preview server.

**Comment by cafootitt** [comment]
Closing this. We will create new issues for the production server deployments when it's time.
