### ISSUE TITLE
Create MUAC icon and edit dietary diversity icon

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#394]
In Togo and Guinea, they have mid-upper arm circumference (MUAC) as a service for the child on a monthly basis from 6m to 5y of age. I looked in https://drive.google.com/drive/u/1/folders/1XMVd5PJEZEanMs57tBgEWbhVJbRBNYG3 and couldn't find an icon for MUAC. Do we need to create one?

The question that will appear on the screen is: "What is the color of the MUAC tape for the child?" The answer choices will be: Green, Yellow, Red.

Here's a picture of the tape: https://www.google.com/search?q=muac&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj0lJmLyd7iAhXxyIUKHb6LB-sQ_AUIECgB&biw=1432&bih=768#imgrc=0pspYxVxX1yw1M:. It's wrapped around the child's mid upper arm, so for an icon, do we want to show a child with this tape around the arm?

For dietary diversity icon, we discussed editing the picture to remove the grains and add an animal product (egg, liver, milk) and fruit product to the icon.

**Comment by rowo** [comment]
Dietary: https://drive.google.com/open?id=1-89gurBKmad1RqNtUZEj1_nReeoqHGu4

![form-dietaryDiversification2](https://user-images.githubusercontent.com/1584163/59577477-ea798180-9091-11e9-8a61-6d0f71f70864.png)

MUAC: https://drive.google.com/open?id=1-F-qmdcz_NFKFQvplTokxOQhWfN5gxB6

![form-muac](https://user-images.githubusercontent.com/1584163/59578117-b5226300-9094-11e9-8b1d-e4b7719c4036.png)

**Comment by cafootitt** [comment]
Great, thanks so much.
