### ISSUE TITLE
Fix navigation drawer Child Clients count

### ISSUE THREAD

**Issue by allan-allay** [OpenSRP/opensrp-client-chw#396]
In the navigation drawer, the Child Clients count is a count of children under the age of 5. 
The count is different from the count of total children under the age of 5 in the Job Aids dashboard. 
This is because of the query that gets the Child Clients count for display in the navigation drawer filters by doing a subtraction of the children's ages by year e.g. current date year 2019 - date of the birth year 2014 and counts only those whose difference is < 5. 
This is erroneous because the date of births includes a day and month and the count shouldn't by a calendar year. For instance, if a child's date of birth is is 2014 August 01, if the count is done in 2019, the child isn't counted since 2019-2014 is 5 years since it doesn't take into account that the child will turn 5 in the month of August
![total_u5_dashboard_count](https://user-images.githubusercontent.com/16164649/59251776-488e0b00-8c33-11e9-8507-c1aed591b47b.png)
![navigation_drawer](https://user-images.githubusercontent.com/16164649/59251781-4926a180-8c33-11e9-8b2f-0920ad2fdf0f.png)

**Comment by cafootitt** [comment]
Excellent, thanks for reporting this, @allan-allay

**Comment by cafootitt** [comment]
lgtm
