### ISSUE TITLE
Look into duplicate data entries recorded for a single home visit on device

### ISSUE THREAD

**Issue by allan-allay** [OpenSRP/opensrp-client-chw#397]
When recording a home visit it appears there are duplicate home visit entries persisted on the device for a single home visit. 
This affects the processing of home visit details when generating indicators. 
![home_visit](https://user-images.githubusercontent.com/16164649/59257607-f05d0600-8c3e-11e9-9874-b1d0c7f7ed66.png)

**Comment by mahmud6390** [comment]
pending PR #401

**Comment by cafootitt** [comment]
@allan-allay How can I QA this. Is this something you can check in the back-end?

**Comment by allan-allay** [comment]
Yeah I can extract the DB on the device and check

**Comment by allan-allay** [comment]
Reviewed fixes applied for this and confirmed a single entry for a single home visit as expected.
