### ISSUE TITLE
Add minimum dietary diversity and MUAC to Growth and Nutrition section in Medical History

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#415]
- [x] In the Growth and Nutrition section of the child's medical history page, add two new sub-sections for dietary diversity and MUAC tasks

- [x] MUAC sub-section label: "MUAC"
Then underneath: "{muac} - done [date of child home visit]"
Example: "Green - done 14-06-2019"

- [x] Minimum dietary diversity sub-section label: "Minimum dietary diversity"
Then underneath: "{diet_diversity} - done [date of child home visit]"
Example: "2 - one animal product AND one fruit - done 14-06-2019"

- [x] The lines should be added in chronological order.
- [x] Only the most recent 3 home visit inputs should be shown for each sub-section.
- [x] See mockup in last comment below.

**Comment by rowo** [comment]
Same answer as the other issue... since these are kind of new history field types, I don't know if we have to feel limited to what exists. I'm also not sure if they all have to be treated equal. It's more about what's important to show. We can figure out a way to show all history if that's necessary (with drill down to historical periods). If only the most recent matters, we can do that instead.

**Comment by rowo** [comment]
![WCARO - Child Profile - history](https://user-images.githubusercontent.com/1584163/59653696-2596b600-9161-11e9-8df7-369d147be89b.png)

**Comment by rowo** [comment]
![WCARO - Child Profile - history](https://user-images.githubusercontent.com/1584163/59653874-eb79e400-9161-11e9-96fd-b532b528d82f.png)

**Comment by mahmud6390** [comment]
![medical_screen](https://user-images.githubusercontent.com/2793306/60589785-231c9900-9dbc-11e9-81f3-18db2b450878.png)
@cafootitt can we use this for dietary and MUAC?

**Comment by cafootitt** [comment]
Looks good @mahmud6390

**Comment by cafootitt** [comment]
QA 1 August release:

Looks like duplication is happening here. This might be happening if you return to a visit to edit it:

![Screenshot_20190803-173609](https://user-images.githubusercontent.com/3488986/62302406-f4f5ac00-b482-11e9-8139-8b50be9f0b7a.png)

**Comment by cafootitt** [comment]
Unable to QA this, because app is not loading profile page for any child. See this issue: #581

**Comment by cafootitt** [comment]
Closing this and creating a single issue to address the additional entires here: https://github.com/OpenSRP/opensrp-client-chw/issues/617
