### ISSUE TITLE
Add ECD as a new section to the child's medical history page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#416]
- [x] After the Growth and Nutrition section of the child's medical history page, add a new section for ECD
- [x] Section label: "Early childhood development (ECD)"
- [x] Then underneath, on separate lines: 
"[date of child home visit] [(age of child at the time of the home visit)]"
"Developmental warning signs: {develop_warning_signs}"
"Caregiver stimulation skills: {stim_skills}"
"Early learning program: {early_learning}"
Example: 
14-06-2019 (1m)
Developmental warning signs: No
Caregiver stimulation skills: Yes
Early learning program: No

- [x] Use the child's age on the date of the home visit, not their current age.
- [x] The lines should be added in chronological order.
- [x] Only the most recent three home visit ECD tasks should be shown.
- [x] See mockup below in last comment

**Comment by rowo** [comment]
@cafootitt I'm not sure how to make the decision on what to show here. If it's important to show every single observation, I think we can figure a way to do it. If only the most recent matters, that's one approach. You could also show when developmental warning signs = yes.

**Comment by cafootitt** [comment]
@rowo I'm still not sure what the best approach is. My line of thought is that only showing the most recent observation wouldn't be an accurate picture of the child's true development state. Maybe the CHW caught the family on a bad day or bad week where they didn't have the money to buy meat, but the rest of the time, they do. It's more about the pattern over a longer period of time. Maybe the child consistently was getting meat products, but in the last 3 months, they haven't had any. That's probably a more important warning sign to look for. However, the argument could be whether the CHW would have the capacity to analyze long term trends from within the app; maybe that's only something program leads would be able to do from the back-end, and they would alert the CHWs to kids in their community at higher risk. 

So, looking at the bigger picture, it's definitely worth having the longitudinal data to observe trends over time, but I'm not sure giving that big picture to the CHW themself will be the most useful. Also, if a child has been sleeping under a bednet all their life, it's not important to show 59 entries of sleeping under a bednet in the app. It's more about identifying warning signs and bad trends and negative changes. It's probably out of scope to do something like showing trends in the app right now, which makes me lean towards only showing the last X number of observations in the app (maybe 3-6 entries? 6 months is sort of enough time to spot a trend) and leaving the trend analysis to the Canopy interface. 

What do you think to the above?

**Comment by rowo** [comment]
That is okay with me. 

I agree, I don't think anybody — CHW or not — could spot patterns of warning signs with how the data is going to be formatted and I agree the CHW history is mostly about the immediately actionable data i.e. recent events.

**Comment by rowo** [comment]
![WCARO - Child Profile - history](https://user-images.githubusercontent.com/1584163/59653684-19aaf400-9161-11e9-94b2-f705d86af662.png)

**Comment by rowo** [comment]
@cafootitt Please review
![WCARO - Child Profile - history](https://user-images.githubusercontent.com/1584163/59653923-06e4ef00-9162-11e9-83ad-0c6e9cb70497.png)

**Comment by cafootitt** [comment]
Thanks, looks good to me.

**Comment by mlberg** [comment]
Hi @cafootitt @rowo for the ECD I think it would be really helpful to see the age of the child.  Eg. 14-06-2019 - 1M Old

If that's complex technically we can do it in phase 2

**Comment by cafootitt** [comment]
Thanks for the suggestion. I think it's easy to add in there. I'll amend the top issue comment.

**Comment by rowo** [comment]
Here's a new screen. I assume we're using the standard age format here.

![WCARO - Child Profile - history](https://user-images.githubusercontent.com/1584163/59785747-a524a200-9293-11e9-8091-58ecd47d2d48.png)

**Comment by mahmud6390** [comment]
![issue-416](https://user-images.githubusercontent.com/2793306/60671196-634f4a80-9e94-11e9-84b7-5106452725c9.png)
@cafootitt at home visit we are using the order like LLITN then ECD can we use same in here? Like the screen shot?

**Comment by cafootitt** [comment]
Fine with me

**Comment by cafootitt** [comment]
QA 1 August release:

- [ ] Looks like some duplication is happening here.
- [ ] Can you add a space between the colon and the Yes/No?

![Screenshot_20190803-173911](https://user-images.githubusercontent.com/3488986/62302650-65043200-b483-11e9-93f4-6cd609a6e56c.png)

**Comment by cafootitt** [comment]
Unable to QA this, because app is not loading profile page for any child. See this issue: #581

**Comment by cafootitt** [comment]
Closing this and creating a single issue to address the additional entires here: https://github.com/OpenSRP/opensrp-client-chw/issues/617
