### ISSUE TITLE
Add LLITN as a new section to the child's medical history page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#417]
- [ ] After the Growth and Nutrition and new ECD sections of the child's medical history page, add a new section for the LLITN task.

- [ ] Section label: "Sleeping under a LLITN"
Then underneath: "{llitn} on [date of child home visit]"
Example: "Yes on 14-06-2019"

- [ ] The lines should be added in chronological order.
- [ ] Only show the most recent 3 inputs from the home visit.

**Comment by rowo** [comment]
So is the conclusion from the ECD issue to just use the last 3? Do you think monthly data captures will always be done this way or will something eventually be useful to show all history for?

**Comment by rowo** [comment]
@cafootitt what does this mean "{llitn}"?

**Comment by rowo** [comment]
![WCARO - Child Profile - history](https://user-images.githubusercontent.com/1584163/59653866-e3ba3f80-9161-11e9-883c-0af9900f6e18.png)

**Comment by cafootitt** [comment]
QA 1 August release:

- [ ] Duplicates seem to be happening:
![Screenshot_20190803-174317](https://user-images.githubusercontent.com/3488986/62302965-f4a9e080-b483-11e9-8b45-c7dba375848b.png)

**Comment by cafootitt** [comment]
Unable to QA this, because app is not loading profile page for any child. See this issue: https://github.com/OpenSRP/opensrp-client-chw/issues/581

**Comment by cafootitt** [comment]
Closing this and creating a single issue to address the additional entires here: https://github.com/OpenSRP/opensrp-client-chw/issues/617
