### ISSUE TITLE
Add sync animation and toaster message to dashboard refresh action

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#432]
Original issue: https://github.com/OpenSRP/opensrp-client-chw/issues/377

When the user presses the sync button, there is no spinner animation nor toaster message to confirm that the refresh was successful or failed. As a user, I might be confused and unsure whether the indicators updated or not.

- [ ] It would be nice to animate the sync button to show the sync is in progress. 
- [ ] When sync started, show toaster message "Updating"
- [ ] A toaster message at the end of the process would also be helpful:
"Dashboard update failed"
OR
"Dashboard updated"

**Comment by allan-allay** [comment]
*Implementation:*
- On click of the _refresh_ icon, it should change to an indeterminate progress indicator. 
- A Toast with the message "Updating..." should be displayed. 
- On completion of the fetching of the indicator tallies, the progress bar should change back to the refresh icon and another Toast with the message "Update complete" should be displayed. 
- In the event, the update fails, the Toast should be displayed with the message "Update failed"

**Comment by cafootitt** [comment]
lgtm
