### ISSUE TITLE
Add OPV 0 not included note to immunization indicator

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#433]
OPV 0 not included

**Comment by allan-allay** [comment]
*Fix:*
- For the Children (0-23 months) up to date on immunizations indicator #194, in the `JobAidsDashboardFragment`, set the Indicator Note i.e. `pieChartIndicatorVisualizationData.setIndicatorNote();` before getting the indicator view for display

**Comment by cafootitt** [comment]
Lgtm
