### ISSUE TITLE
Re-order the indicators

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#434]
order them in the order you find them in here: https://docs.google.com/spreadsheets/d/1q9YiWqjLiToTd0--Q8CbwhBwwcNDspbDxVrUfDm8VGU/edit#gid=1627225414

**Comment by allan-allay** [comment]
*Fix:* 
- Add the indicator visualization views in the order specified above in the `visualizationsViewGroup` by doing `visualizationsViewGroup.addView(view)` in the correct order of the views to be displayed.

**Comment by cafootitt** [comment]
lgtm
