### ISSUE TITLE
Design household survey interaction

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#454]
Hey Roger, as I mentioned over a call we had, can we start thinking about the interaction for the household survey questions for countries in West Africa?

Content for the 3-question household survey:

1. Does the household have handwashing facilities?

Info icon: Respond "Yes" if the household has a designated space to wash hands (or a mobile handwashing point), water, and soap. Otherwise, respond "No".

2. Does the household have access to clean drinking water?

3. Do household members use a hygienic latrine for the disposal of feces?

What do you think of adding this to the family FAB button, since it should be a frequently (i.e monthly, action?) We can also consider adding this to the child's monthly home visit form, but if there are multiple children in the home, this would get repetitive. My concern is that in the FAB button, though, it would be overlooked and never filled out. Another place for this is in the DUE tab for the family. The user would click on the task to open the form to fill in. We'd have to add a monthly schedule to this if we put it in the due tab.

@mberg Your input would be appreciated here as well.

**Comment by rowo** [comment]
@cafootitt The due tab is where it was designed to be originally. What is your thinking for wanting to change it? Does the due section already have a schedule indicator? 

I think we already discussed a while back that we wanted to pull these questions out of the individual's monthly form.

**Comment by cafootitt** [comment]
@rowo Ok thanks for jogging my memory.

>> Does the due section already have a schedule indicator?

What do you mean by this?

**Comment by rowo** [comment]
@cafootitt Some of the mockups have this blue dot/indicator that says whether the task is due or overdue. I was wondering if that is built out and if that is enough to indicate the monthly schedule aspect of it (so just questioning whether anything needs to be added).

I am remembering now the issue we had (before the house-not-person task was removed) was it wasn't clear how to get to the equivalent of a medical history. I believe the initial proposal (but not final agreement) was to access historical data via the individual forms in the house activity list.

**Comment by cafootitt** [comment]
Ah ok, I see what you mean. It is built in there, so we could put it on the monthly schedule (due each month, overdue the next month if not done), and we would probably want to include it in the number of tasks for the family, so that the task number on the register page still matches the Due number on the Due tab in the family profile, since that is one of the main reasons we said the task number would be tasks and not people needed to be visited.

So then mockups needed:
- Due tab in the family profile showing this task is due (let's call the task "WASH check", so the line shown would be: "Harris Family · WASH check" where Harris is the name of the family.
- Probably don't need a mockup of the 3-question survey, since it would be native form
- Then on the Activity tab: "Harris Family · WASH check", then on the next line: "Completed on [date]"
- Tapping on the row in the activity tab opens either a short dialog that summarizes the responses, e.g.: 
Clean drinking water: Yes
Hygienic latrine: No
Handwashing facilities: Yes

Or, probably simpler to achieve, re-launch the form but prevent edits.

**Comment by rowo** [comment]
The household due tab with updated labels: 
<img src="https://user-images.githubusercontent.com/1584163/60860010-b140b700-a1e2-11e9-8eac-05ed3383c28c.png" width="350">

The household activity tab with updated labels: 
<img src="https://user-images.githubusercontent.com/1584163/60860012-b1d94d80-a1e2-11e9-843d-bcb633e16f3a.png" width="350">

The household survey with disabled fields: 
<img src="https://user-images.githubusercontent.com/1584163/60860011-b140b700-a1e2-11e9-9000-e1cdcc9b58ca.png" width="350">

**Comment by cafootitt** [comment]
Thanks @rowo
