### ISSUE TITLE
Early learning program still in English in French version

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#468]
![Screenshot_20190710-111629](https://user-images.githubusercontent.com/3488986/60883971-348df700-a23b-11e9-90d5-6570443025f7.png)

Seems something is wrong with the string file. Is it not getting generated?

**Comment by mahmud6390** [comment]
In early_childhood_development_fr json file this string having as english. need to change this

**Comment by cafootitt** [comment]
Here is the French translation to insert into the json file:

L'enfant assiste-il ou elle régulièrement à une programme d'apprentissage pour la petite enfance?

**Comment by cafootitt** [comment]
lgtm
