### ISSUE TITLE
Implement profile page for all other family members

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#48]
This was mentioned in another issue, but all family members will get a profile page, not just children. For other family members who don't have home visits and services due (yet), the page will look like the below (ignore the child picture and imagine this is an adult shown):

<img width="335" alt="screen shot 2018-12-07 at 12 26 24 pm" src="https://user-images.githubusercontent.com/3488986/49639211-7e033300-fa1b-11e8-8a7f-6e8da6611051.png">

- [x] Note that they still have the floating action icon (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/39)
- [x] In this case, the back button would say "Return to Jack Smith Family" where jack smith is the `fam_name` of the family
- [x] Image or avatar is shown
- [x] `first name` `middle name` `last name`, `age`on first line
- [x] `sex` `village_town` `opensrp_id` on second line
- [x] Background is grey, we don't have to show the blue/pink backgrounds here
- [x] Notice that the family head, primary caregiver roles are shown, if applicable
- [x] Family has services due row is also shown (as per child's mockup: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/43)

**Comment by cagulas** [comment]
15 Feb build:

- [ ] Middle name and age are missing
- [ ] Not sure what this is, but there's a short yellow line that appears right in the middle bottom of the top demographic info section. Can we remove it?
- [ ] Instead of showing the row with the person's name repeated, let's change this to show whether the family has any services due, so same as the row we show on the child's profile view.

**Comment by cagulas** [comment]
@ladleo Hi Denis, what's the status on this issue? If you're finished, we want to start assigning you to other issues.

**Comment by ladleo** [comment]
Was meant to have a discussion with @rkodev and @keymane on this but I failed to make the call, but I should have this done as soon as I have that discussion with them.

**Comment by cagulas** [comment]
This is done, closing.
