### ISSUE TITLE
Calculations for fully immunized at 1 yr and 2 yrs

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#49]
In the child medical history page (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/46), a child can receive "badges" for reaching fully immunized status at 1 yr and again at 2 yrs. The calculations for these are below.

Fully immunized - 1 yr:
- bcg
~~- hepb~~
- opv1
- penta1
- pcv1
- rota1
- opv2
- penta2
- pcv2
- rota2
- opv3
- penta3
- pcv3
~~- rota3~~
- ipv
- mcv1
- yf

So basically, all of the vaccines due during the first year apart from OPV 0, which doesn't count towards this.

If the child receives all of the above vaccines before reaching 1 year of age, they get the fully immunized - 1 yr badge.

Fully immunized - 2 yrs:
- All of the vaccines listed above
- mcv2

If the child receives all of the above vaccines before reaching 2 years of age, they get the fully immunized - 2 yrs badge.

A child cannot ever get the 2 yrs badge if they didn't get the 1 yr badge.

**Comment by cagulas** [comment]
Icons attached now. @mahmud6390 

![icon-fully-immunized-1yr](https://user-images.githubusercontent.com/3488986/51116015-e4e5ea00-181a-11e9-9411-74b3ebc6ec50.png)
![icon-fully-immunized-2yr](https://user-images.githubusercontent.com/3488986/51116016-e4e5ea00-181a-11e9-90fe-dedb78ebb8ca.png)

**Comment by mahmud6390** [comment]
done

**Comment by mahmud6390** [comment]
Need to add mcv,yf in immunization library also vaccine list in home visit.
Right now without these fully immunization show.
pending PR
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/106

**Comment by cagulas** [comment]
I will QA this once all of the scheduling issues are fixed with the vaccines.

**Comment by cagulas** [comment]
QA on 21 March release:

Child Susie Lea Flash (ID# 2293538) - chathree login:
- I registered her at 1 year 8 months of age, so old enough to receive every single vaccine
- In the home visit, I back-recorded all vaccines: OPV 0, BCG, OPV1-3, Penta1-3, PCV1-3, Rota1-2, IPV, MCV1-2, and YF.
- Only healthy child 1 year badge is displayed in the medical history page, when both 1 year and 2 years should be displayed, since she received all vaccines.

**Comment by mahmud6390** [comment]
@Ephraim or Ronald at ChildUtils class there has two constant variable like
one_year and two_year vaccine list.can you please check the missing vaccine
name for 2yrs fully immunized?

**Comment by cagulas** [comment]
This works well now, thanks!
