### ISSUE TITLE
Implement Side Menu

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#502]
![Picture1](https://user-images.githubusercontent.com/20777928/61171194-e2234200-a57c-11e9-9f5a-6c8359774a7f.png)

- [x] The side menu can be opened by swiping from the left or tapping the side menu button on the main register page
- [x] Title should be "USAID Boresha Afya" not "Boresha Afya"
- [x] Order of the registers should be as pictured
- [x] Title of the registers should be: All Clients, All Families, ANC, PNC, Child Clients, Family Planning, Malaria, Referrals
- [x] Blue font for the register that's currently selected - Families should be default-select each time a user logs in.
- [x] Counts next to the registers should the number of client currently in the register
- [x] Below the registers should be the language choice option, device-to-device sync, and log out.
- [x] Logout button shows user's first name and logs user out of the app
- [x] Message Roger for the icons (referrals and family planning) when you are about to start work on this issue.
- [x] Sync button attempts to sync in between automatic attempts. 
- [x] At the bottom of the side panel should be the Sync and "Last: [time & date of last sync]". 

Similar to: [https://github.com/OpenSRP/opensrp-client-chw/issues/7](https://github.com/OpenSRP/opensrp-client-chw/issues/7)

**Comment by rowo** [comment]
@ellykits icons are in Drive, names start with "sidemenu..." https://drive.google.com/open?id=1-Zv67Yn8jZPsxcwZHQuDPhgtEwI5kiR8

**Comment by msschroeder** [comment]
lgtm
