### ISSUE TITLE
Implement floating action button (FAB) and create top right dropdown menu

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#507]
Same as the [CHW All Families Register](https://github.com/OpenSRP/opensrp-client-chw/issues/248). I have copied the issue here for simplicity.

**Family FAB:**
Call *(if no number provided, show disabled state that's already implemented)*
Add new family member

**Family dropdown:**
Family details
~Remove existing family member~
~Change family head~
~Change primary caregiver~

**Family member FAB:**
Call *(if no number provided, hide the FAB completely)*
**Note how the icon changes to just the call button for the family member FAB**

**Family member dropdown:**
Registration info
~Remove this person~

Screenshots of all the options:

Family fab, phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799456-b843b980-4c33-11e9-9db2-6b47c006b8f7.png" width="330">

Family fab, no phone
<img src="https://user-images.githubusercontent.com/1584163/54799468-c72a6c00-4c33-11e9-985f-dbb33f19748a.png" width="330">

Family dropdown - Please see the changes as noted above
<img src="https://user-images.githubusercontent.com/1584163/54799479-d1e50100-4c33-11e9-97db-04fb8ba54e6c.png" width="330">

Individual member fab, phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799486-dc06ff80-4c33-11e9-9c3c-f86ba6fbad04.png" width="330">

Individual member fab, no phone number provided
<img src="https://user-images.githubusercontent.com/1584163/54799491-e6c19480-4c33-11e9-8478-e7bd5ce14a51.png" width="330">

Individual member dropdown - Please see the changes as noted above
<img src="https://user-images.githubusercontent.com/1584163/54799505-f80aa100-4c33-11e9-9bb2-c33b7c7c4b89.png" width="330">

Icons: It's from the [material icon catalog](https://material.io/tools/icons/?search=phone&icon=phone&style=outline)

**Comment by ellykits** [comment]
Hi @msschroeder So anything that is crossed shouldn't be included in HF app that is for the dropdown menu?

**Comment by msschroeder** [comment]
lgtm
