### ISSUE TITLE
Implement Call widget

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#511]
Same as the [CHW All Families Register](https://github.com/OpenSRP/opensrp-client-chw/issues/25). I have copied the issue here for simplicity.

<img width="386" alt="screen shot 2018-12-03 at 8 50 09 pm" src="https://user-images.githubusercontent.com/3488986/49391621-3dff3000-f73d-11e8-9a70-c1faacf45c0c.png">

- [x] The call widget is opened from the floating action icon on either the family profile page or the client's profile page
- [x] Clicking outside the box or the top right X takes you back to the page you were on
- [x] At most two names are listed, if the family head and primary caregiver are separate family members, but if it's one person, list "family head" and "primary caregiver" roles underneath the same name.
- [x] Put the person's first name, middle name, last name
- [x] "Call {phone_number}" where phone number variable comes from either the family registration form or the family member registration form
- [x] Tapping on the above launches the phone's phone app with the number populated in the dialer.

**Comment by msschroeder** [comment]
QA 16th Aug Build:
Could not test as the FAB was not yet useable

**Comment by msschroeder** [comment]
@ellykits I have noticed that the name of the head of family is {first_name} {middle_name} in all the areas including here, where it says first name, middle name and surname. Are they a related issue?

**Comment by ellykits** [comment]
@msschroeder the issues are related. The same happens on CHW as well will work on the fix. However this happens only for the first person saved when adding family - the family head.

**Comment by msschroeder** [comment]
lgtm
