### ISSUE TITLE
Remove UNICEF from app logo for Togo

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#520]
Refer to this original issue: https://github.com/OpenSRP/opensrp-client-chw/issues/392

The Togo government team is requesting we remove the UNICEF logo from the app logo. UNICEF approves this change as well.

**Comment by rowo** [comment]
![Artboard 1 copy 4](https://user-images.githubusercontent.com/1584163/62234480-c26f8480-b398-11e9-9516-861ae1dd792c.png)

**Comment by cafootitt** [comment]
Thanks @rowo

**Comment by cafootitt** [comment]
@mahmud6390 This issue is now ready for you to implement.

**Comment by cafootitt** [comment]
lgtm
