### ISSUE TITLE
Togo: Change phone number constraint to 8-16 digits

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#521]
For Togo only, we need to change the phone number constraint.

Change from: 10 digits and must start with 0
Change to: 8 to 16 digits (can start with any number)

- [x] Please update this constraint in the Add Family, Edit Family, Add Family Member, Edit Family Member, and ANC Registration forms, {phone_number} and {other_phone_number} fields*
- [x] Please also update this constraint in the change family head and change primary caregiver dialogs as well.

*ANC Registration form does not have the {other_phone_number} field

**Comment by cafootitt** [comment]
@mahmud6390 Can you also update the constraint error message to the following:

en: Number must be 8 to 16 digits.
fr: Le numéro doit être composé de 8 à 16 chiffres.

**Comment by mahmud6390** [comment]
@cafootitt i checked this string comes from fr string file. Which screen showing this at english?

**Comment by cafootitt** [comment]
QA 13 Aug release (Togo apk):

- [ ] Constraint message still not updated (both English and French) in the Add Family and Add Family Member forms (phone number and other phone number fields)

**Comment by cafootitt** [comment]
31 aug release - lgtm
