### ISSUE TITLE
Add Togo app to Play Store before live roll-out in September

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#523]
Reference this issue for Liberia: https://github.com/OpenSRP/opensrp-client-chw/issues/205

~~We need to clear the server url for the versions posted to the play store, so users outside this project don't have access to the project server data entry endpoint. Once the devices are configured and the server url added initially, they should not need to re-enter the server url with each app update. I remember this is how ZEIR worked, but please confirm we can still do this.~~ **CF: Feedback from our team is that this isn't necessary, since data submission is restricted to users.**

- [x] A short description of the apps (up to 80 characters):
Household enumeration, child health, ANC and PNC community workflows

- [x] Full description of the app (up to 4000 characters):
**Togo:**
CFC-RTM was developed for Togo's Ministry of Health, as part of UNICEF’s Child-friendly Communities (CFC) program. The app is used by Community Health Workers (CHWs) and their supervisors to enumerate all households in their catchment area and provide routine child health, antenatal care (ANC), and postnatal care (PNC) services in the community.

**Guinea:**
CFC-RTM was developed for Guinea's Ministry of Health, as part of UNICEF’s Child-friendly Communities (CFC) program. The app is used by Community Health Workers (CHWs) and their supervisors to enumerate all households in their catchment area and provide routine child health, antenatal care (ANC), and postnatal care (PNC) services in the community.
CFC-RTM is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers.

- [x] Hi-res app icon (512x512 pixels)
  ![Artboard 1 copy 4](https://user-images.githubusercontent.com/1584163/62256619-f0bc8680-b3cf-11e9-925d-3edce3df43f7.png)

- [x] Feature graphic for the app. More info on the feature graphic [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en) (1024x500 pixels) 
  ![togo-playstore-feature-graphic](https://user-images.githubusercontent.com/1584163/62261344-f7a0c480-b3e2-11e9-9aa0-857e95ff6710.png)

- [x] 3 screenshots of the app (please use the same 3 screenshots from Liberia play store posting, which you can find here: https://github.com/OpenSRP/opensrp-client-chw/issues/205

**Comment by cafootitt** [comment]
@rowo Now Guinea is planning to roll out soon as well (I just found out this is sooner rather than later), so I've updated this issue to include assets for Guinea as well. Do you mind adding the logo and feature graphic for Guinea as well?

https://github.com/OpenSRP/opensrp-client-chw/issues/391 (Guinea logo at this link)

**Comment by rowo** [comment]
@cafootitt do these work?

![app-icon-guinea](https://user-images.githubusercontent.com/1584163/62708722-f282dd00-b9c1-11e9-86fd-8ffcd1bb871b.png)
![guinea-cfc-playstore-feature-graphic](https://user-images.githubusercontent.com/1584163/62708723-f282dd00-b9c1-11e9-8312-0a1ce7ee17c7.png)

**Comment by cafootitt** [comment]
Thanks @rowo. I'm waiting for the Togo preview server to come back up, so that I can capture French screenshots to send to you.

**Comment by rkodev** [comment]
App has been listed in the playstore: https://play.google.com/store/apps/details?id=org.smartregister.chw.togo

**Comment by cafootitt** [comment]
closing this
