### ISSUE TITLE
Add an icon for the "Refer to facility" in CHW app Member profile FAB

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#553]
- [x] Add the icon for the "Refer to facility" in member profile FAB.

Reference: #269 

@rowo Can you provide the link to the icon that should be used for this?

**Comment by rowo** [comment]
@msschroeder the icon is the last one in https://github.com/OpenSRP/opensrp-client-chw/issues/269#issuecomment-482513201 with the person + arrow. Does that work?

**Comment by msschroeder** [comment]
@rowo Thanks. I must have missed it. That works for me.

**Comment by msschroeder** [comment]
@ellykits Is this done?

**Comment by msschroeder** [comment]
Closing
