### ISSUE TITLE
Implement the referral row in HF client profile

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#558]
<img width="384" alt="profile" src="https://user-images.githubusercontent.com/20777928/62132149-2f294700-b2e5-11e9-9a60-94068fc074a6.png">

- [x] Each referral for a client will appear as a new row in the client's profile 
- [x] Each referral will appear above the client's medical history (as shown in the image above)
- [x] In the event of multiple referrals, each referral will appear as an individual row, with the most recent referral at the top row and older referrals descending in subsequent rows (with medical history below the referral group)
- [x] Clicking this row will take you to the detailed referral (#560 )

**Comment by rowo** [comment]
@msschroeder is this content defined in a referral dictionary?

**Comment by msschroeder** [comment]
The content to go in the detailed referral is defined in the referral data dictionary. @rowo

**Comment by rowo** [comment]
@msschroeder would the first row say "Referred for [type of referral (column A in https://docs.google.com/spreadsheets/d/1uPwajfoBnMrM6NYUyMeFATFQwSisqb8kfGXUG3nySyI/edit#gid=0)]?

And then the second row I guess would just say "View full referral info"?

**Comment by msschroeder** [comment]
@rowo That makes sense to me.

**Comment by msschroeder** [comment]
QA 16th August Build:
- [ ] Remove option to go to family profile from a client's profile page. It should only show medical history as noted in the issue 

![Screenshot_20190820-095302](https://user-images.githubusercontent.com/20777928/63324827-8ee99f80-c331-11e9-9c30-f1197a569df4.png)

**Comment by msschroeder** [comment]
@ellykits I still don't see the medical history. 

I will close this issue and create a new one
