### ISSUE TITLE
Close a referral on the health facility app

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#561]
- [x] When a user selects "MARK AS DONE" in the detailed referral, a confirmation message will appear, "Are you sure that you want to close this referral? The referral will no longer be available to review" choice options of "Yes" and "No".

If "Yes" is selected for the confirm close message:
- [x] The referral will be closed and archived and be removed from the list of referrals in the referral register
- [x] The referral will be closed and archived and the referral row for this referral will be removed from the client's profile
- [x] The user will be directed to the referral register
- [x] If "No" is selected for the confirm close message, the referral will not be closed.

@rowo @cafootitt @mberg Does it make sense to include a confirmation screen in case someone accidentally hits this button, which I think is a likely occurrence? If we do need this, could you provided an updated mock-up to show this Roger @rowo

**Comment by rowo** [comment]
@msschroeder See recommended language for confirmation dialogs: https://material.io/design/components/dialogs.html#alert-dialog, https://material.io/design/communication/confirmation-acknowledgement.html#confirmation. 

So some updates are we could update to not be a yes/no and also the main text could be shortened or supplemented.

**Comment by msschroeder** [comment]
@rowo Thanks, that is really helpful. And I think some of these texts could be a bit more eloquent than a yes/no confirmation. Using https://material.io/design/components/dialogs.html#anatomy, how do you feel about:
Title: Mark as Done?
Text: Referral will be closed and disappear from app
Side by side button: Yes/No

**Comment by rowo** [comment]
I would try to avoid the yes/no options based on this recommendation:
<img width="849" alt="Screen Shot 2019-07-31 at 7 39 45 PM" src="https://user-images.githubusercontent.com/1584163/62261590-dbe9ee00-b3e3-11e9-8d81-0f5c278bea3f.png">

Also the text needs a period and the title should be sentence case:

<img src="https://user-images.githubusercontent.com/1584163/62261644-09369c00-b3e4-11e9-8857-caf9f89cc7da.png" width="300">

**Comment by msschroeder** [comment]
@rowo Thanks, so are you okay with the mock-up of the message above?

**Comment by rowo** [comment]
@msschroeder if you are good with it, I am.

**Comment by msschroeder** [comment]
Text should be "Cancel" instead of "Dismiss" and "Mark done" instead of "Mark as Done"
![Screenshot_20190902-074212](https://user-images.githubusercontent.com/20777928/64090734-644a0e80-cd55-11e9-913b-c5d48aa30d28.png)

**Comment by ellykits** [comment]
> * The user will be directed to the referral page (or is it currently going to the last page @dubdabasoduba )

@msschroeder I think it currently moves back to the last page. Since you can open the referrals details from the client's profile it makes sense to return to the previous page. Or should we navigate to referrals register when the referrals details is opened from profile?

**Comment by msschroeder** [comment]
@ellykits I thin going to the last page is fine. I just wanted to confirm. Thanks

**Comment by msschroeder** [comment]
I think we can close

**Comment by ellykits** [comment]
> * Referral needs to disappear from the client's profile

@msschroeder This works now. Just a point to note when a client has more than one referral then the row will be shown on their profile until all the referrals are closed.

**Comment by msschroeder** [comment]
lgtm
