### ISSUE TITLE
Boresha Afya - Child Health Visit - 10W is not appearing

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#586]
In the last few releases, the child visit has been inconsistent. Many times, it is pulling data in from WCARO flavors.

- [ ] Immunizations (10wk) is still not appearing
![Screenshot_20190806-095408](https://user-images.githubusercontent.com/20777928/62517934-12cf6200-b831-11e9-8a61-275e0075d793.png)
![Screenshot_20190806-095332](https://user-images.githubusercontent.com/20777928/62517967-2084e780-b831-11e9-9919-6af02fbe0824.png)

**Comment by cafootitt** [comment]
@msschroeder What do you mean by "pulling data in from WCARO flavors"? I don't see anything in your screenshots to support this, so I'm a little confused.

Also, you put in August 6th as the 6w vaccine dates, which means the 10w vaccines won't be due until 4 weeks later, which is probably why they're not appearing. Can you try entering a date of more than 4 weeks ago for the 6w vaccines?
