### ISSUE TITLE
BA - Child health visit - 14wk does not have the right immunizations

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#587]
In the last few releases, the child visit has been inconsistent. Many times, it is pulling data in from WCARO flavors.

- [ ] Immunizations (14 wks) should be OPV 3, Penta 3, PCV 3, IPV.
![Screenshot_20190806-095353 (1)](https://user-images.githubusercontent.com/20777928/62518264-d2bcaf00-b831-11e9-8523-6d3d441c539f.png)

**Comment by cafootitt** [comment]
Please check that the 14w immunizations are able to be given, i.e. 4 weeks have gone by since 10w vaccines were given. You can't give Penta 3 if Penta 2 hasn't been given at least 4 weeks ago.
