### ISSUE TITLE
BA - Child Health Visit - 18m immunizations are not showing

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#588]
In the last few releases, the child visit has been inconsistent. Many times, it is pulling data in from WCARO flavors.

- [x] Immunizations at 18m is not showing at all
![Screenshot_20190806-095408](https://user-images.githubusercontent.com/20777928/62518548-845be000-b832-11e9-8779-41705150479f.png)

**Comment by cafootitt** [comment]
This is probably because MR 1 was just given August 6th, so 18m vaccines aren't due yet.
