### ISSUE TITLE
BA - Child Visit - Showing Immunizations at 14 weeks are overdue

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#594]
- [ ] In the Child Visit, Immunizations are shown as overdue, but they are not overdue. It shows they are overdue, but they are at the correct time.

![Screenshot_20191113-112958](https://user-images.githubusercontent.com/20777928/62525213-ac057500-b83f-11e9-87f1-13add9ffe853.png)

**Comment by cafootitt** [comment]
@msschroeder pls check that you reverted your date/time settings on your phone.

**Comment by msschroeder** [comment]
lgtm
