### ISSUE TITLE
Clean up on the WASH check

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#605]
- [x] The French translations are missing in the form. 
- [x] See below. The font size is different from the Child home visit row. We need to keep things like font size, type, etc. consistent throughout the app.
![Screenshot_20190809-124908_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/62771283-8da0b300-baa5-11e9-8694-9d06777df201.jpg)
- [x] See below. The wash check and the no services are due message should never be shown simultaneously. 
Steps to replicate:
- Register a new family (the wash task is shown correctly in due tab)
- Register another family member (the wash task now appears with the no services are due message)
![Screenshot_20190809-121911_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/62771469-f851ee80-baa5-11e9-9e94-54af8ac9ebd7.jpg)
- [x] The data populated into the view-only form on the activity tab is wrong (see below).
Steps to replicate:
- Fill in the wash task and answer all questions with "yes"
- Open the submitted form on the Activity tab. All answers are "no" instead of "yes"

![Screenshot_20190809-125514_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/62771621-51ba1d80-baa6-11e9-832e-4fb332b8074d.jpg)

- [x] The completed WASH check disappears from the Activity list. To replicate, complete the wash check, then from the activity tab, tap on the Members tab, then back to the Activity tab. The wash check is now gone.

**Comment by cafootitt** [comment]
QA 26 Aug release:
This is looking much better, but a couple of issues still need to be addressed:

- [ ] WASH check is still showing along with the no services due icon (see below). To replicate this, register a new family and family head, then register a new adult family member, then go to the Due tab. You will see the WASH check and the no services due icon shown simultaneously.

<img width="364" alt="Screen Shot 2019-08-27 at 10 22 35 AM" src="https://user-images.githubusercontent.com/3488986/63749823-eef1c000-c8b4-11e9-9c15-f4a17f02d093.png">

- [ ] Also, the WASH check doesn't seem to be counted correctly in the Due tab count (see below, the count should be 2, not 1), but please let me know (leave a comment on this issue) if this will be addressed as part of this issue: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/72

![Screen Shot 2019-08-27 at 10 16 25 AM](https://user-images.githubusercontent.com/3488986/63749996-3f691d80-c8b5-11e9-9db3-70cb39bbaedf.png)

**Comment by mahmud6390** [comment]
@cafootitt  right now Wash check due count not replicate in "Home visit due"/"family other member due status". It's showing only in this family profile screen and the count showing adding with other due or overdue count.If we need to update the homevisitdue status in home screen based on Wash check then we need address OpenSRP/opensrp-client-chw-anc#72.otherwise only need to fix in this screen is ok.

**Comment by cafootitt** [comment]
@mahmud6390 Ok, I think you're saying that this can only be addressed after https://github.com/OpenSRP/opensrp-client-chw-anc/issues/72 is addressed, correct? If so, that's fine.

**Comment by cafootitt** [comment]
31 Aug release - lgtm
