### ISSUE TITLE
Altitude and precision are not saved in add family form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#606]
![Screenshot_20190809-103516_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/62772210-972b1a80-baa7-11e9-82de-96dc22e5788d.jpg)

If you fill out the family details section, then go to the family head section, then back to the family details section, the altitude and precision fields are empty.

low priority, putting in icebox.

**Comment by msschroeder** [comment]
This is also an issue on BA - adding to the BA issues Kaneban board

**Comment by cafootitt** [comment]
THis is not happenign anymore, closing.
