### ISSUE TITLE
Can we make the login page not have to scroll?

### ISSUE THREAD

**Issue by cafootitt** [opensrp/opensrp-client-chw#616]
![Screenshot_20190814-140950_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/63019719-da6cfb00-bea4-11e9-9917-84c36dbea7ea.jpg)

The login page for Togo scrolls. Roger, can you help specify the dimensions, spacing, padding, etc. to follow here, so that the page doesn't need to scroll?

Is this something where we can responsively-resize things depending on the device size? If not, then we can optimize this for a 6.2 inch screen, which is the size of the screen for the device they have chosen.

**Comment by rowo** [comment]
@cafootitt I agree, I did not really design the page to scroll. I think it's just an implementation thing. This issue might be better for an Android dev to comment on what changes need to be made so it's not fixed. 

6.2" is a physical size, but what I would need is a pixel size if we were trying to optimize.

**Comment by cafootitt** [comment]
@rowo The pixel size of the device is 720 x 1520 pixels (https://www.gsmarena.com/samsung_galaxy_a10-9580.php).

@rkodev Can you provide your input here please?

**Comment by rowo** [comment]
Looking at the login, would it mean being more prescriptive on what happens when the keyboard comes up so scrolling is not needed there?

**Comment by cafootitt** [comment]
@rowo is that a question for Ronald or me? I don't think I know how to answer that question, apart from agreeing that it would be nice if the page scrolls up to show the input fields.

**Comment by rowo** [comment]
@cafootitt not for you. Trying to highlight a specific point of feedback from @rkodev I'm wondering about.
