### ISSUE TITLE
Child Home Visit refactor

### ISSUE THREAD

**Issue by rkodev** [OpenSRP/opensrp-client-chw#620]
Child Home Visit refactor

<b>Home visit tasks</b>
- [x] Immunization (Add all different weeks)
- [x] Vitamin A service
- [x] Deworming Services
- [x] Child vaccine card
- [x] Observation and Illness
- [x] Exclusive breast feeding
- [x] MNP
- [x] MUAC
- [x] LLITN
- [x] ECD
- [x] Birth Certification Form
- [x] Add implementation specific changes across all flavors
     - [x] BA
     - [x] Chad
     - [x] DRC
     - [x] Guinea
     - [x] Liberia
     - [x] Togo
- [x] Tests / Add visit done, not done and undo are working
- [x] Work on child home visit edit
- [x] Add backward compatibility for old child home visit events
- [x] Verifiy data dictionary mappings on all the forms

<b>Child profile tasks</b>
- [x] Update the child profile to read visit table
- [x] Update Medical History view to use new db
- [x] Verify upcoming services view  is working

<b>Reports</b>
- [x] Verify all reports on child home visit work

https://docs.google.com/spreadsheets/d/11YsEYAXGr8aQUJm2vOKwTogyqj1XKsPwGboT-aKDpZA/edit#gid=0

**Comment by rkodev** [comment]
Tasks to be completed 
- [ ] Vitamin A service
- [ ] Deworming Services
- [ ] Birth certification
- [ ] Observation and Illness
- [ ] MNP

**Comment by mberg** [comment]
is this closed for togo?

**Comment by rkodev** [comment]
@mberg all the issues but the flavor specific changes for the wcaro apps are done. It right now adding and removing the home visit services on the countries is a config. This was left out so testing could be done. But the changes will be enabled on the next release that's why the issues remained open

**Comment by cafootitt** [comment]
Closing this. QA will be on the other issues.
