### ISSUE TITLE
Goes to ANC Register when removing a family member

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#626]
- [ ] When a family member is removed (other family member or child U5), the ANC register appears. I think once a family member is removed, the app should go back to the original page is was on previously - Could be Family Profile or register the user was viewing the profile from

**Comment by cafootitt** [comment]
@msschroeder It depends from where they opened the remove member form. You can also remove a member directly from their profile. E.g. you can go to child register list, open child profile, then remove child. In that case, do you think it makes sense to go back to the child's family's member page?

**Comment by msschroeder** [comment]
@cafootitt That makes sense to me. That the family member should go back to the the original page is was on. However, right now it always goes to the ANC profile. Let me update the issue.

**Comment by msschroeder** [comment]
lgtm
