### ISSUE TITLE
App crashes when changing the primary care giver

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#627]
- [x] App crashes when you try to change the family primary caregiver.

Replicate:
1. Open a family profile
2. Select "Change primary caregiver"
3. App crashes

**Comment by rkodev** [comment]
@msschroeder I have attempted changing the primary caregiver on a few clients multiple times and it works fine. This is possibly from a data error in the previous server. I will close this issue for now but please flag it if it re-occurs

**Comment by msschroeder** [comment]
lgtm
