### ISSUE TITLE
App crashes when changing family head

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#628]
- [x] App crashes when you try to change the family head from the family profile page

Replicate:
1. Go to a family profile page
2. Select "Change family head" from 3 dot drop down
3. App crashes

**Comment by rkodev** [comment]
Could not reproduce this issue. But might have been from a similar reason as the primary care giver
https://github.com/OpenSRP/opensrp-client-chw/issues/627#issuecomment-526277500

**Comment by msschroeder** [comment]
lgtm
