### ISSUE TITLE
Photoshop national ID card for inclusion in info icon in app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#643]
Instructions sent over email. See email titled "Togo National ID - for editing".

**Comment by rowo** [comment]
![pixel-id](https://user-images.githubusercontent.com/1584163/63895973-b9d19480-c9be-11e9-9cdd-8cd308f821ee.jpg)

**Comment by cafootitt** [comment]
Thanks Roger.
