### ISSUE TITLE
Create options that minimize OpenSRP logo on wcaro apps

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#644]
The request was to remove the OpenSRP logo on the app. As a compromise, we discussed ways to minimize the logo and branding for OpenSRP on the app login page. Can you come up with options that we can present to UNICEF? We should consider making the logo smaller and less conspicuous or suggestions for other options are also welcome.

![Screenshot_20190821-090952_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/63406912-ec462500-c3f3-11e9-9923-bd45f9bf6ff9.jpg)

**Comment by rowo** [comment]
@mberg are you saying you are okay with the below?

<img src="https://user-images.githubusercontent.com/1584163/63990435-077af980-cab2-11e9-88f1-91c58ee81c3e.png" width="400">

**Comment by rowo** [comment]
@cafootitt, @mberg  says this is okay.
