### ISSUE TITLE
Modify constraint on family head DOB and age fields

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#647]
Right now, in the Add family form, the constraint on family head age and DOB is 5-120 years, but we are requested to change it to 15-120 years.

- [x] Modify constraint to `>= 15 and <= 120 years of age` on both `dob_entered` and `age_entered` fields in the add family form
- [x] Do this in both English and French json forms
- [x] Do this for all country flavors, i.e. Liberia, Togo, Guinea, Chad, DRC

**Comment by rkodev** [comment]
@cafootitt should this include the family registration form?

**Comment by cafootitt** [comment]
@rkodev Do you mean the family member registration form? If so, the answer is no, we're only making this change in the family/family head registration form.

**Comment by cafootitt** [comment]
V1.0.6

I can still register a head of family at 5 years of age.

**Comment by cafootitt** [comment]
V1.0.6 lgtm
