### ISSUE TITLE
Remove redundant "de" in Vitamin A task

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#678]
![Screenshot_20190826-110223_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/63675351-49294d00-c7f1-11e9-9f78-af351936674f.jpg)
![Screenshot_20190826-110245_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/63675404-6bbb6600-c7f1-11e9-9e83-6927a210a71f.jpg)

**Comment by cafootitt** [comment]
31 August release:

Fails QA, because the "de" in Vitamin A was missed:

![Screenshot_20190901-112305_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/64074178-c56bd680-ccb0-11e9-9f51-082d54ee1a00.jpg)

**Comment by msschroeder** [comment]
lgtm
