### ISSUE TITLE
Change constraint on caregiver/family head to 15 years of age

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#687]
Right now, anybody in the app who is not a child (i.e. they are > 5 years) is allowed to be selected as the family head/primary caregiver. We are requested to change this to 15 years of age. So, in the below to screens, we need to constrain the list of people shown to only those people whose {age} >= 15 years old.

![Screenshot_20190718-170516](https://user-images.githubusercontent.com/3488986/61464107-5f382800-a97e-11e9-8944-d01d2bd5f5f3.png)
![Screenshot_20190718-170458](https://user-images.githubusercontent.com/3488986/61464110-5fd0be80-a97e-11e9-8119-3af1360eec5a.png)

**Comment by msschroeder** [comment]
@cafootitt Wouldn't we want to also add a constraint to the registration form for the head of household?

**Comment by cafootitt** [comment]
Yep - https://github.com/OpenSRP/opensrp-client-chw/issues/647

**Comment by cafootitt** [comment]
V1.0.6

lgtm
