### ISSUE TITLE
Medical History page isn't showing all the history anymore

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#692]
<img width="368" alt="Screen Shot 2019-08-27 at 11 19 26 AM" src="https://user-images.githubusercontent.com/3488986/63755513-84924d00-c8bf-11e9-8578-801f08a6e03f.png">

Please refer to the original implementation issues: https://github.com/OpenSRP/opensrp-client-chw/issues/46, https://github.com/OpenSRP/opensrp-client-chw/issues/416, https://github.com/OpenSRP/opensrp-client-chw/issues/415, https://github.com/OpenSRP/opensrp-client-chw/issues/417

Order of the sections should be:
Last Visit; 
Immunizations; 
Growth and Nutrition;
ECD;
LLITN

**Comment by cafootitt** [comment]
@mahmud6390 said he'll pick this issue up on Saturday

**Comment by cafootitt** [comment]
QA V1.0.4:

Some clean up needed, but hopefully not too big an effort:

- [ ] Clean up:
![Screenshot_20190917-202614_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65066106-6a163580-d98c-11e9-930d-5a6d03f2e848.jpg)

- [ ] Sorry, I forgot to list child vaccine card in the first issue above. We need to add it to the medical history page

- [ ] More clean up:
![Screenshot_20190917-202914_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65066620-5ddea800-d98d-11e9-8a88-aa406659c0e5.jpg)

- [ ] More clean up:
![Screenshot_20190917-205551_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65066947-11e03300-d98e-11e9-86c4-6e5fca513e11.jpg)

- [ ] More clean up:
![Screenshot_20190917-205738_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65067042-481db280-d98e-11e9-9504-49619c50154e.jpg)

**Comment by rkodev** [comment]
@cafootitt This has been resolved. @HusnaHariz We will need to discuss how to handle the event type since the structure is changing

**Comment by cafootitt** [comment]
lgtm, one remaining issue, which I'll move into a new issue
