### ISSUE TITLE
Immunizations for 6 wk Immunizations date error

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#710]
- [x] The date range for immunizations at 6 wks only allows you to enter the current the device date/time: device year, device month, device date and 7 days prior. You should be able to enter today's date and all dates prior up to their DOB.  

When you break it down by each vaccine, Penta 2 is the one that appears to be causing this error.

**Comment by cafootitt** [comment]
Megan, can you elaborate more on this? What is the current date range allowed that you're observing, and what should it be?

**Comment by msschroeder** [comment]
Updated the issue

**Comment by rkodev** [comment]
@msschroeder this might be an issue with a specific child. The date ranges for the group vaccine date picker are bounded by the valid rage for all the vaccines.

**Comment by msschroeder** [comment]
@rkodev I am still getting the incorrect values for the dates for Penta 2 (meaning that the date widget only allows limited values for the date entered such as 01 September 2018 for a child born 01 September 2018). This was for a  on newly created child. And it is happening consistently for 2 children.

**Comment by msschroeder** [comment]
@rkodev I am still getting the incorrect value. 

Replicate:
1. Add a child with 9 months (Born Sept 18, 2016)
2. Do a child visit
3. Add Immunizations at birth (Sept 18, 2016)
4. Add immunizations at 6 weeks (Oct 30, 2016)
5. Add immunizations at 10 weeks 
5a. Try and enter 27 November 2016 - you cannot
5b. Open and add dates for individual immunizations - Enter 27 Nov 2016 for OPV2, PCV 2, Rota 2
5c. Try and enter 27 November 2016 for Penta 2 - you cannot

Below is a screenshot showing you the only way to finish this immunization
![Screenshot_20190918-133351](https://user-images.githubusercontent.com/20777928/65233386-69d88000-dadb-11e9-9bea-fde83e4102ca.png)

**Comment by msschroeder** [comment]
@manutarus This is still an issue. I am going to move this back to the to-do because it needs to get done

**Comment by rkodev** [comment]
@msschroeder the bug on this issue has been resolved

**Comment by msschroeder** [comment]
lgtm
