### ISSUE TITLE
Vitamin A and Deworming are only collecting dose 1

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#711]
- [x] Only dose 1 for Vitamin is being collected in any home visit
- [x] Only dose 1 for Deworming is being collected in any home viist

What I noticed:
- I have visit 1. I enter a date for both Vitamin A and Deworming dose 1
- Vit A/Deworming dose 1 is not saved in the medical history
- I have visit 2. I have to enter both Vitamin A and Deworming dose 1 again

**Comment by rkodev** [comment]
@msschroeder The deworming works fine, as for Vitamin A there was an issue with the service schedule that has been addressed

**Comment by msschroeder** [comment]
lgtm
