### ISSUE TITLE
Enter immunizations at each visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#712]
- [x] You should only have to enter the dates of all the immunizations once. 

Currently, each home visit, it will show the new immunizations, but I have to enter all the immunizations from birth, even if I did it in the last visit. They are saved in the medical history

**Comment by msschroeder** [comment]
QA Sept 1st Build:
@rkodev This is still not working. I still have to enter all vaccinations for all home visits regardless of whether they have been previously

**Comment by cafootitt** [comment]
This doesn't seem to be an issue in Wcaro.

**Comment by rkodev** [comment]
![Screenshot_1567496252](https://user-images.githubusercontent.com/43806892/64153311-448b1700-ce37-11e9-8540-ccca44ac5d2a.png)
![Screenshot_1567496266](https://user-images.githubusercontent.com/43806892/64153312-448b1700-ce37-11e9-8da4-4f3f16d85de1.png)
![Screenshot_1567496295](https://user-images.githubusercontent.com/43806892/64153313-@msschroeder 523ad80-ce37-11e9-9a71-92f04daf0d15.png)
![Screenshot_1567496381](https://user-images.githubusercontent.com/43806892/64153314-4523ad80-ce37-11e9-85ba-630e72b99f3c.png)

@msschroeder as shown above, this issue appears to be resolved. I have recorded a child visit, adjusted the device date to about 6w later and attempted this visit again and it looks fine. I have attempted to reproduce this with multiple children but the vaccines schedule are working fine. Could you kindly give steps that you used to test this issue?

**Comment by msschroeder** [comment]
@rkodev 

Reproduce:
1. Register a child - 1 yr and 11 months
2. Do a home visit - fill in the all the tasks
3. Move your time on device to the next moth
4. Do another home visit

**Comment by msschroeder** [comment]
lgtm
