### ISSUE TITLE
Immunizations at birth are not currently included for a newly added child (0d)

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#716]
- [x] Immunizations at birth should be included after a new child is registered (0d) 

Currently, it is not being added right away.
<img width="316" alt="Screen Shot 2019-08-28 at 11 33 38 AM" src="https://user-images.githubusercontent.com/20777928/63850056-f344d880-c99b-11e9-9f28-321c936f9c00.png">

**Comment by cafootitt** [comment]
Megan, which version of the app are you using? Ronald fixed this recently, so I'm hoping this is already fixed.

@rkodev Can you comment here?

**Comment by msschroeder** [comment]
@cafootitt v0.0.5 (built 28 August 2019)

**Comment by rkodev** [comment]
@msschroeder this should be resolved in this release.

**Comment by msschroeder** [comment]
lgtm
