### ISSUE TITLE
Update text and add image to {national_id} info icon

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#718]
On the {national_id} field in the Add family and Add family member forms, we are requested to add the image below as well as update the text.

- [x] Change the English text in the info icon to "What is their national identity number?"
- [x] Change the French text in the info icon to "Quel est leur numéro d'identité national?"
- [x] Add the below image below the text.
- [x] Make these updates in both the Add family and Add family member forms

![image](https://user-images.githubusercontent.com/3488986/63916280-cac2ea00-ca40-11e9-9ac2-dfc811786c93.png)

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate

Looks good.
