### ISSUE TITLE
Modify ANC referral details page.

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-client-chw#727]
ANC referral details should contain:

"Name: {first_name} {surname}, {age} [age units], Phone: {phone_number}
GA: [gestation_age]
Problem: ANC Danger Signs; Symptoms: [symptoms]
Referral date: [referral date from ANC danger sign referral form]
CHW: {first_name} {last_name}; Phone: {phone_number}
[Link to open ANC's record (if record is already synced to HFW's device)"

**Comment by msschroeder** [comment]
QA Sept 1 Build: 
- [ ] Third line also pulls in answer from the pre-referral treatment. It should only pull in the symptoms (shown below in the screen shot). None is not an option when other symptoms are selected
![Screenshot_20190902-073728](https://user-images.githubusercontent.com/20777928/64090650-de2dc800-cd54-11e9-8991-ff26d61b2839.png)

**Comment by ellykits** [comment]
This has now been addressed.

**Comment by msschroeder** [comment]
lgtm
