### ISSUE TITLE
Immunizations are not appearing for children 2 years and older

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#752]
QA Sept 1:
- [ ] Immunizations (not any of them) are not appearing in the Child Health Task after the child turns 2 years

NOTE: They appear for children up to 1 yr 11 m, but when they turn 2, all the immunizations disappear

**Comment by cafootitt** [comment]
@msschroeder Maybe this is copied over from Togo, because all vaccines expire at 2 years of age for Togo, which is when the EPI program stops targeting them. What should the expiry be for BA?

**Comment by msschroeder** [comment]
@cafootitt I thought this might be an issue. But, when I searched, this did not appear, but maybe it had been closed.

But, no, this should not be up to 2 years. It should go as the service schedule notes: 
https://docs.google.com/spreadsheets/d/1YgkGeMMskTaGVPVR61WSd0jmVw4paDyM9pJEXf17ym8/edit?usp=sharing

**Comment by cafootitt** [comment]
@msschroeder I couldn't understand this comment: 

>> @cafootitt I thought this might be an issue. But, when I searched, this did not appear, but maybe it had been closed.

But, I think what's happening here is the expiry dates for Togo overwrote the ones for BA, so they need to be added. It would be helpful to create a table here in the issue to show the expiries per vaccine, like so:

| Vaccine | Expiry date |
|---------|------------|
| BCG | Child's DOB + 1 year|
| OPV 0 | Child's DOB + 13 days |
| OPV 1 | Child's DOB + 4 years 10 months |
| PCV 1 | Child's DOB + 4 years 10 months |
| Penta 1 | Child's DOB + 4 years 10 months |
| Rota 1 | Child's DOB + 7 months 0 days |
| OPV 2 | Child's DOB + 4 years 11 months |
| PCV 2 | Child's DOB + 4 years 11 months |
| Penta 2 | Child's DOB + 4 years 11 months |
| Rota 2 | Child's DOB + 8 months 0 days |
| OPV 3 | Child's DOB + 5 years |
| PCV 3 | Child's DOB + 5 years |
| Penta 3 | Child's DOB + 5 years |
| IPV | n/a |
| MR 1 | n/a |
| MR 2 | n/a |

**Comment by msschroeder** [comment]
lgtm
