### ISSUE TITLE
Reformat the icons for BA HF and CHW apps

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#762]
- [ ] @rowo  can you help reformat the image so that it can be used for for the CHW BA app
CHW app (WAJA): WAJA.jpg 
HF app (Kituoni): Kituoni.jpg
https://drive.google.com/open?id=1vQv5mzAwWa5D1-8vEdWkNbLp0lElerap

**Comment by rowo** [comment]
@msschroeder here you go. I had to retrace the shapes to vector but these should work

![Kituoni](https://user-images.githubusercontent.com/1584163/64567597-985d9a80-d326-11e9-88a0-b4f0ad434d6e.png)
![WAJA](https://user-images.githubusercontent.com/1584163/64567598-985d9a80-d326-11e9-8d9e-5d5d1ab05aad.png)

**Comment by msschroeder** [comment]
@rowo Thanks. I will update the other issues
