### ISSUE TITLE
Adjust the OpenSRP logo on the login page on all WCARO apps 

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#772]
![63990435-077af980-cab2-11e9-88f1-91c58ee81c3e (1)](https://user-images.githubusercontent.com/3488986/64512230-9972d580-d2ee-11e9-8d95-e9bcd9ba0e3b.png)

- [x] Let's remove the "Powered by"/"Réalisé par" line and just include the OpenSRP logo
- [x] Replace the current OpenSRP logo with the new one (see below comment)

**Comment by rowo** [comment]
![logo-opensrpicon-for-wcaro](https://user-images.githubusercontent.com/1584163/64562057-1ff0dc80-d31a-11e9-8c39-fbb05bbba35f.png)

**Comment by cafootitt** [comment]
lgtm, but it's a bit blurry, but I'll add it to the other issue with the rest of the icons.
