### ISSUE TITLE
Ready the BA app to Play Store before live roll-out in September

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#777]
~~We need to clear the server url for the version posted to the play store, so users outside this project don't have access to the project server data entry endpoint. Once the devices are configured and the server url added initially, they should not need to re-enter the server url with each app update. I remember this is how ZEIR worked, but please confirm we can still do this.~~

We'll need the following:

 - [ ] A short description of the app (up to 80 characters): @cafootitt What are your thoughts?
CHW app (WAJA): 
Household enumeration, child health, ANC, PNC, and Malaria community workflows 
(78 characters)

HF app (Kituoni): Client registration, referral closure, and key health facility events 
(69 characters)

- [ ] Full description of the app (up to 4000 characters) @cafootitt What are your thoughts?

CHW app (WAJA): 
The WAJA App was developed in collaboration with Jhpiego partnering with Tanzanian Government, for the USAID Boresha Afya project in Tanzania's Lake and Western Zone. The app is used by Community Health Workers (CHWs) to enumerate all households in their catchment area and provide routine child health, antenatal care (ANC), postnatal care (PNC), malaria services in the community. 

WAJA is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers.
(501 characters)

HF app (Kituoni):
The Kituoni App was developed in collaboration with Jhpiego partnering with Tanzanian Government, for the USAID Boresha Afya project in Tanzania's Lake and Western Zone. This app is use by the health facility workers to register any clients not registered in the community and to close referrals for child health and antenatal care (ANC).

Kituoni is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers.
(456 characters)

 - [ ] Hi-res app icon (512x512 pixels) @rowo

CHW app (WAJA): WAJA.jpg 
HF app (Kituoni): Kituoni.jpg
https://drive.google.com/open?id=1vQv5mzAwWa5D1-8vEdWkNbLp0lElerap

- [ ] Feature graphic for the apps (CHW app (WAJA) & HF app (Kituoni)). More info on the feature graphic here (1024x500 pixels) @rowo

- [ ] 3 screenshots of the each app @rowo
CHW app (WAJA): 
HF app (Kituoni):

**Comment by cafootitt** [comment]
the app descriptions look fine to me.

**Comment by rowo** [comment]
- I added 512x512 app icons to the other issue (they are full squares and from what I understand, devs will need to set rounded edges to be masked in Android).
- screenshots I requested @msschroeder take. Other OpenSRP projects have examples of what we've used (mainly it's about filling in appropriate user data), but feel free to judge if other screens are better for this project's goals

**Comment by rowo** [comment]
@msschroeder for the feature graphics I generally just use some screenshots or photos from the app and project, so maybe if you can share anything you have, I can use those. Otherwise, I can just use that logo and a tagline I make up from the description. What do you think?

**Comment by msschroeder** [comment]
@rowo Screenshots for the CHW app:
<img width="325" alt="Screenshot 1 - CHW" src="https://user-images.githubusercontent.com/20777928/64596381-7151a800-d3bc-11e9-80e8-93a5b02628b0.png">
<img width="326" alt="Screenshot 2 - CHW" src="https://user-images.githubusercontent.com/20777928/64596388-79a9e300-d3bc-11e9-80e3-802dd9f4bca2.png">
<img width="325" alt="Screenshot 3 - CHW" src="https://user-images.githubusercontent.com/20777928/64596389-7a427980-d3bc-11e9-9e21-56dec1361f90.png">

**Comment by msschroeder** [comment]
@rowo Screenshots for HF app - I have 4 screenshots
<img width="321" alt="Screenshot 1 - HFW" src="https://user-images.githubusercontent.com/20777928/64597623-c7bfe600-d3be-11e9-87b5-b23d9f9a96a6.png">
<img width="320" alt="Screenshot 3 - HFW" src="https://user-images.githubusercontent.com/20777928/64597624-c8587c80-d3be-11e9-8580-51f063cae079.png">
<img width="323" alt="Screenshot 2 - HFW" src="https://user-images.githubusercontent.com/20777928/64597626-c8587c80-d3be-11e9-8c1e-9f372d8d46d0.png">
<img width="322" alt="Screenshot 4 - HFW" src="https://user-images.githubusercontent.com/20777928/64597627-c8f11300-d3be-11e9-8914-e7c611fe0967.png">

**Comment by msschroeder** [comment]
@rowo I liked the feature page you used for WCARO -using the app logo and tagline from the description. That looked nice. I would say let's take that route.

**Comment by rowo** [comment]
@msschroeder here you go. Btw for Kituoni, I noticed the screenshot for a profile has a question mark i.e. "View full referral info?". This question mark should not be there.

![BA-playstore-feature-graphic-Kituonia](https://user-images.githubusercontent.com/1584163/64645683-6a8a5b80-d3e3-11e9-94db-2d379f950e5f.png)
![BA-playstore-feature-graphic-WAJA](https://user-images.githubusercontent.com/1584163/64645684-6b22f200-d3e3-11e9-8ece-17305ad4b095.png)

**Comment by msschroeder** [comment]
I have created new issues for the roll out for each app #810 and #811. Closing
