### ISSUE TITLE
Update CHW app information for BA

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#778]
- [x] Update the app icon for CHW: https://github.com/OpenSRP/opensrp-client-chw/issues/762
- [x] Update the name of the app to 'WAJA'
- [x] Update the text on the login page: USAID Boresha Afya (first line); WAJA app (second line)

**Comment by cafootitt** [comment]
I would recommend not including the word "app" in the app title on the login page.

**Comment by msschroeder** [comment]
@cafootitt That is what Jphiego said they would like.

**Comment by msschroeder** [comment]
@rkodev Here is the icon from #762,
![WAJA](https://user-images.githubusercontent.com/20777928/64594460-b8d63500-d3b8-11e9-9c1e-04505195c661.png)

**Comment by msschroeder** [comment]
lgtm
