### ISSUE TITLE
Fix Swahili translation for Immunisation (at birth) in child visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#783]
- [x] Change 'Chanjo (at birth)' to 'Chanjo (wakati wa kuzaliwa)' in the child home visit
<img width="250" alt="Screen Shot 2019-09-09 at 8 15 52 PM" src="https://user-images.githubusercontent.com/20777928/64552029-0e6dfb80-d33f-11e9-89d0-230e48889abc.png">

**Comment by allan-allay** [comment]
This is now translated to **Chanjo (kuzaliwa)**
@msschroeder Is this still okay or we have it as described above _(wakati wa kuzaliwa)_ ? 

----

![immunisation_at_birth_translation](https://user-images.githubusercontent.com/16164649/69036303-a4d13400-09f6-11ea-9138-f1293f2d3c42.png)

**Comment by msschroeder** [comment]
@allan-allay Is this related to how it is visualized on transifex? Because it has changed, but I am seeing something other than what is noted in the issue.

**Comment by allan-allay** [comment]
@msschroeder Yeah this is as to how it is translated by transifex. I checked and the same string (at birth) is being used in different places.

**Comment by msschroeder** [comment]
@allan-allay Cool. Then, I will change this on Transifex and change accordingly. Closing
