### ISSUE TITLE
Age is not getting saved when you open Edit registration form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#812]
This is happening inconsistently, but I'm noticing that for some family members, the age appears as 0 when you open the Edit family member registration form. See this screencast provided by the client: https://drive.google.com/file/d/1DTY3NF2WyEHCBgxxZhh4nQfw6p940GWd/view

**Comment by rkodev** [comment]
@cafootitt on this issue, I'm working to reproduce it. But I'll investigate further for the source of the error

**Comment by cafootitt** [comment]
Only happening on French version.

**Comment by cafootitt** [comment]
v1.0.11 Togo release candidate

This fails QA. I'm logged in as chaone user. If you change the app to French, then open the Yella Smith Menage/Family, then open the Yella Smith profile, open Edit registration form, the Age is showing as 0.

@AnnieMungai observed that it is only happening for adult family members where DOB is unknown and entered manually. If the DOB is entered, the age is showing.

**Comment by rkodev** [comment]
@cafootitt @AnnieMungai Tried this with Yella Family and its work okay. Also attempted a few more families registered with DOB unknown.
![Screenshot_1575472441](https://user-images.githubusercontent.com/43806892/70154668-f39eef00-16c1-11ea-976e-24ef812cac34.png)
![Screenshot_1575472475](https://user-images.githubusercontent.com/43806892/70154670-f4378580-16c1-11ea-81cf-fb99039f8e72.png)

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate (Dec 4th version)

Looks good.
