### ISSUE TITLE
How to see all contents of the child profile after a visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#855]
@cafootitt @rowo How would you recommend accounting for the long Swahili translations in the child profile? 

Once you complete a child home visit in Swahili version, you can no longer see all the contents on the screen.

I was thinking of adding a scroll?

![Screenshot_20190918-152234](https://user-images.githubusercontent.com/20777928/65241453-3520f480-daec-11e9-92bb-cc23ac369455.png)

**Comment by rowo** [comment]
If possible, this view should scroll and also the text should wrap and be aligned left.

**Comment by msschroeder** [comment]
Closing - Another issue was already created
