### ISSUE TITLE
Build a sample Liberia app for LMH

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-chw#934]
The LMH team would like to demo the liberia app for a sales process.

Steps:

- [x] Create a branch for Liberia
- [x] Update the strings that have the word Togo to Libéria
- [ ] Change the logo on the home screen to be the [Liberia Coat of Arms](https://github.com/OpenSRP/opensrp-client-chw/issues/79)

**Comment by craigappl** [comment]
Here's the branch: https://github.com/OpenSRP/opensrp-client-chw/tree/934-Liberia-Sample

**Comment by rowo** [comment]
I think this is no longer valid
