### ISSUE TITLE
Prevent video title from being cut off

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#937]
See the 3rd video in the screenshot below. Can we spill over the video title to the next line if it's too long to fit in one line?

![Screenshot_20191024-085732_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/67458894-f842a300-f63f-11e9-8b6f-5078eb24fa5a.jpg)

**Comment by msschroeder** [comment]
lgtm
