### ISSUE TITLE
Implement "Tap to pause video download" action

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#939]
In the original implementation [issue](https://github.com/OpenSRP/opensrp-client-chw/issues/774), we had said the workflow should allow a tap to pause action during video download. This wasn't implemented. Can we describe the reason why it wasn't implemented here and assign a LOE to implement it, so we can determine the priority level? See the second video below. It's a spinner that cannot be tapped.

![Screenshot_20191024-085732_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/67459024-448de300-f640-11e9-83d5-524b0f9519db.jpg)

@rowo cc'ing you on this to follow the discussion or contribute.

**Comment by rowo** [comment]
This is meant to be a "stop/cancel" interaction. We could do "pause" too, but then we'd also need a Stop/Cancel but that seemed unnecessary right now.

**Comment by rkodev** [comment]
@cafootitt the ability to pause and resume downloading is 1-2 days work. Having the cancel button should be < 1 day

**Comment by cafootitt** [comment]
Let's just do the cancel button then.

**Comment by cafootitt** [comment]
Lgtm
