### ISSUE TITLE
Hide the refer to facility buttons in the wcaro apps (togo + guinea)

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#953]
They are appearing in the ANC and PNC profiles. Let's make sure we write tests, so that this doesn't pop up again in any wcaro app in future. This has happened another time before.

Marking as high priority because of the confusion this may cause to the end users.

**Comment by msschroeder** [comment]
Guinea lgtm

**Comment by msschroeder** [comment]
Togo lgtm
