### ISSUE TITLE
Fix record appearing in both ANC and PNC profiles

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#954]
Steps to replicate:
- Register a woman who is between 10-49 years in a family
- Do an ANC registration for that woman, make her around 38 or so weeks pregnant
- Complete an ANC visit for the woman
- Then go to her profile and record a pregnancy outcome of live birth

- [x] The woman should not remain in ANC, but she is still there currently (in addition to appearing in PNC):
![Screenshot_20191028-132154_CFC-RTM - Guine](https://user-images.githubusercontent.com/3488986/67671739-922f8600-f987-11e9-9fdd-94629a6acd3d.jpg)
![Screenshot_20191028-132216_CFC-RTM - Guine](https://user-images.githubusercontent.com/3488986/67671743-92c81c80-f987-11e9-91c1-409b3fe389bf.jpg)

- [ ] The pregnant woman icon shouldn't be shown anymore on the family register list page
![Screenshot_20191028-132234_CFC-RTM - Guine](https://user-images.githubusercontent.com/3488986/67671751-9491e000-f987-11e9-9e2d-998cb4e978dd.jpg)

- [ ] The ANC count should go down by one (it should be 0 in this picture):

![Screenshot_20191028-132606_CFC-RTM - Guine](https://user-images.githubusercontent.com/3488986/67671777-9d82b180-f987-11e9-8523-34ba87f25489.jpg)

**Comment by msschroeder** [comment]
lgtm
