### ISSUE TITLE
"days" or "jours" is missing on the Medical history page for children

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#990]
See below. The unit of time is missing on the Medical history page for children.

![Screenshot_20191114-092821_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/68833775-5a357c00-06c5-11ea-9d7b-b058decb3566.jpg)

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate (Dec 4th Version) 

Looks good.
