### ISSUE TITLE
Exclusive bf answer choice needs to be reversed on the child medical history page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#991]
Recall from the child home visit that "No" means the child is exclusively breastfeeding, while "Yes" means they are not, due to the way the question is worded.

This means that on the Medical History page, where the phrase is worded the opposite way, we also need to reverse the answer choice and not just place in the answer choice from the task in the home visit.

Child home visit task:
Yes = Not exclusively breastfeeding
No = Exclusively breastfeeding

Medical history page:
Change "Yes" from above to "No"
Change "No" from above to "Yes"

![Screenshot_20191114-092821_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/68834067-fbbccd80-06c5-11ea-98bd-fc861fd95f0a.jpg)

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate (Dec 4th Version)

Looks good.
