### ISSUE TITLE
Redirect to child's profile after home visit initiated from child register page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#994]
I noticed that if you tap on the child home visit button from the child register list page, complete the home visit, save it, you are redirected back to the child register list page.

Instead, the user should be redirected to the child's profile page I think.

@rowo Is this correct?

**Comment by rowo** [comment]
Yes, I think landing on the profile would be a nice confirmation that you've completed a visit for the right person and it was successfully saved. The back button could then take you back to the child register page.

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate (Dec 4th Version)
Good to go!
