### ISSUE TITLE
Vitamin A, Deworming dose 1 appearing twice on medical history page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#995]
![Screenshot_20191114-094714_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/68834417-c664af80-06c6-11ea-820d-2eda74b0768d.jpg)

**Comment by rkodev** [comment]
@cafootitt This happened because of incomplete visits during development.

**Comment by rkodev** [comment]
Resolved by excluding data submitted incompletely

**Comment by cafootitt** [comment]
ok cool, thanks,
