### ISSUE TITLE
Sort to the top isn't happening after home visit completed

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#996]
In the child register list (as well as all other lists), the records should sort to the top by last updated.

In the child register list, I noticed that after you complete a home visit, the child record is not getting sorted to the top of the list.

Steps to replicate:
- On child register list, scroll below and find a child who has a home visit due
- Tap on the home visit button in the register list, complete home visit
- The child's record remains where it was on the list.

**Comment by AnnieMungai** [comment]
Looks good.
