### ISSUE TITLE
Change abbreviated time units for vaccinations to the full word

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#999]
![Screenshot_20191114-120042_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/68844692-3d0ba800-06db-11ea-9435-39a0c820e907.jpg)

d to days
j to jours
w to weeks
s to semaines
m to months
m to mois

I can't determine which strings these are in Transifex, because the abbreviated time units appear also in the child profile and register list to abbreviate their age.

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate (Dec 4th Version. 

Looks okay.
